### ISSUE TITLE
#1000

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1000]
:champagne:

**Comment by vtikha** [comment]
![img_7047](https://cloud.githubusercontent.com/assets/4537987/20922877/0794332e-bbaa-11e6-8f50-7dfd028763a9.JPG)

**Comment by claudiofantacci** [comment]
![Mille!](http://66.media.tumblr.com/3f98a2fe94096d56a6054a218407f6f3/tumblr_o0sqza3sQ91qzxq63o1_540.gif)

**Comment by drdanz** [comment]
Some statistics:
* 611 issues (124 still open)
* 388 pull requests
* 1 #1000

Thanks to anyone who contributed so far! Please keep up the good work!
