### ISSUE TITLE
Opening single application multiple times shouldn't be allowed in yarpmanager

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#1007]
Hey @apaikan 

@Tobias-Fischer saw that it's possible to open the same application multiple times within the `yarpmanager`.

It shouldn't be an intended behavior, isn't it?

**Comment by apaikan** [comment]
@Tobias-Fischer Right!
So far I remember it was not possible to open multiple instance of an application in the same manager. Probably this bug has been introduced in the new release of manager. Anyway easy to fix :)
