### ISSUE TITLE
There are receiver modifier carriers, but not sender modifier carriers

### ISSUE THREAD

**Issue by paulfitz** [robotology/yarp#102]
It is possible to make carriers that transform incoming data in some way such as:
  http://wiki.icub.org/yarpdoc/carrier_config.html#carrier_config_bayer 
It would be useful to also have a way to transform outgoing data.

**Comment by drdanz** [comment]
I think this was addressed by #168 and can be closed, @apaikan, @paulfitz please reopen if I'm wrong
