### ISSUE TITLE
QT_DEVICE_PIXEL_RATIO is deprecated

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1038]
@claudiofantacci wrote on #837 

> I'm writing here concerning about `QT_DEVICE_PIXEL_RATIO` qtputenv option.
> 
> Under macOS, QT version 5.7.0 (from brew), launching `yaprdataplayer`, `yaprview`, `yarpmotorgui`, the following warning is raised:
> ```
> Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use: 
>     QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors. 
>     QT_SCREEN_SCALE_FACTORS to set per-screen factors. 
>     QT_SCALE_FACTOR to set the application global scale factor.
> ```
> 
> Probably `QT_AUTO_SCREEN_SCALE_FACTOR` set to `1` (boolean true) will make the job done.
> 
> Ref: http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by Nicogene** [comment]
Fixed by #1200
