### ISSUE TITLE
swig 2.0.11 generates faulty bindings for Lua

### ISSUE THREAD

**Issue by elen4** [robotology/yarp#104]
Because of this SWIG bug https://github.com/swig/swig/issues/93 , Lua bindings generated with SWIG version 2.0.11 do not compile (at least on MSVC). Should we add a check on SWIG version?

**Comment by drdanz** [comment]
@elen4, @paulfitz Is this still an issue or can we close this? Do swig 2.0.12 and swig 3 work?

**Comment by paulfitz** [comment]
I'll close this. The lua build passes on all other swig versions (including 2.0.12 and 3). We didn't add code in yarp to detect version 2.0.11 and warn user to upgrade (which is the only action we could take), but that will be less and less of a problem with the passing of time.
