### ISSUE TITLE
Loss of precision when converting string to double inside a yarp::os::Property

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1057]
When a string is converted to a double inside a `yarp::os::Property`, the number of decimal digits is internally truncated.  
```
    Property p1;
    Property p2;
    Property p3;
    p1.fromString("(width 0.00001)");
    p2.fromString("(width 0.000001)");
    p3.fromString("(width 0.0000001)");
    double s1 = p1.find("width").asDouble(); / /ok
    double s2 = p2.find("width").asDouble(); // ok
    double s3 = p3.find("width").asDouble(); // ****** s3 == 0 ******
```
The problem affects also parameters read from file.

**Comment by drdanz** [comment]
Added some related unit tests, see 629b1dfa749555bfaee05d3cd63c15a01739c65d
The issue does not seem to come from `Value`, see [ValueTest.cpp:317](https://github.com/robotology/yarp/blob/629b1dfa749555bfaee05d3cd63c15a01739c65d/tests/libYARP_OS/ValueTest.cpp#L317), it is probably truncated somewhere else
