### ISSUE TITLE
Drop YARP 1 support

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1060]
There are a few places in the code where YARP is still doing stuff for compatibility with YARP 1.
I think that at this point we should drop the compatibility.

See for example [BottleImpl.cpp:516](https://github.com/robotology/yarp/blob/629b1dfa749555bfaee05d3cd63c15a01739c65d/src/libYARP_OS/src/BottleImpl.cpp#L516)

**Comment by barbalberto** [comment]
:+1:

**Comment by Nicogene** [comment]
Closed via #1353
