### ISSUE TITLE
[iCubDarmstadt01] Yarpmanager cannot launch GUIs

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/yarp#1084]
If I try to launch **GUIs**  (`yarpview`, `skinManagerGui` etc) from the **yarpmanager** on `icub19` of the `iCubDarmstadt01`,  they cannot be launched. If I launch from terminal instead, everything works fine.

@Nicogene suggested that there are some problems with `qt`, but we cannot check properly or install any new version of `qt` because internet is not working on the robot laptops.

**Comment by drdanz** [comment]
@giuliavezzani How did you solve this? Please leave some comment when you close an issue to explain why you are doing that.

**Comment by giuliavezzani** [comment]
You are right. Actually I didn't do anything on purpose for solving the issue. The yarpmanager  simply started to work properly. 
The only difference might be that I installed some libraries, that I need for my code .. But I am know sure the two facts are correlated.
