### ISSUE TITLE
Yarpmanager: More informative log when timeout occurs waiting for resources

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/yarp#1095]
Hi @apaikan,
It would be great to see which resources are the ones blocking a resource to run. Right now, the log message just says "Timeout while waiting for some resources", but does not specify which resources are referred to. If there are multiple dependencies, it's sometimes hard to find out which one crashed.

Best,
Tobi

**Comment by apaikan** [comment]
fixed in 2738d8c8759c8f37b1f7bcb7f60ba38cce941fc0
