### ISSUE TITLE
yarp version 2.4

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#112]
"yarp version" still gives 2.3.60 on master branch.
The same happens as output of the cmake macro.

Shall we update it to 2.4?

**Comment by paulfitz** [comment]
@drdanz @lornat75 is it time to make a new release? 2.3.63 was in July of last year.

**Comment by drdanz** [comment]
I *think* we are waiting for Matteo to fix the Qt5 stuff for windows installer before making a new release (2.3.64?)

**Comment by lornat75** [comment]
Also I would love to include robotinterface.
