### ISSUE TITLE
Problems displaying some graphics items

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/yarp#1122]
I recently installed from scratch Ubuntu 16.04, YARP and iCub software. Testing the installation I noticed that the motorgui looks weird, much "bigger" than expected.
![screenshot from 2017-03-08 11-44-17](https://cloud.githubusercontent.com/assets/18591940/23701298/803ebd1e-03f6-11e7-93e9-7936bba3503d.png)
![screenshot from 2017-03-08 11-44-53](https://cloud.githubusercontent.com/assets/18591940/23701320/909a899a-03f6-11e7-9af4-a553027c025f.png)

 The yarpmanager interface instead is ok, while the yarpdataplayer seems to have the same problem for some icons
![screenshot from 2017-03-08 11-53-21](https://cloud.githubusercontent.com/assets/18591940/23701384/d0afd832-03f6-11e7-8c4c-b5659bf1af07.png)

It may be related to #837 and #1038.

**Comment by drdanz** [comment]
Do you have a normal display or a high DPI display?

**Comment by S-Dafarra** [comment]
A normal full HD laptop display. If it may help, I have an NVIDIA GeForce 830M graphic card using the open-source driver X.Org X server.

**Comment by Nicogene** [comment]
Hi @S-Dafarra !

Which version of `Qt` do you have ?

**Comment by S-Dafarra** [comment]
By running ```qmake --version``` I get 4.8.7, but I think to have both ``qt4`` and ``qt5``.

**Comment by S-Dafarra** [comment]
Actually I tried now to install ``qt5-default`` and by performing again ``qmake --version`` it returns  5.5.1, but after recompiling ``icub-main`` I get the same weird visualization.

**Comment by Nicogene** [comment]
The guis are in `yarp` so if you compile only `icub-main` you can't see if qt5 enabled as default does the trick :smile: .
#1200 introduce some changes that could fix this issue.
My advice is to update your `yarp devel` pulling from `origin\devel`, compile and see if the problem persist.
I have your setup (except for the nvidia gpu) and I see the guis normally.
Let me know if the last commit fixed this issue.

**Comment by S-Dafarra** [comment]
Ops :sweat_smile:, newbie error. Now is working fine! Thanks
