### ISSUE TITLE
ENABLE_yarpcar_bayer_carrier, set to ON

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#1126]
@pedrombmachado commented on [Thu Mar 09 2017](https://github.com/robotology/QA/issues/196)

Hi all,
   I am compiling the yarp and I following all the steps described in [icub-wiki](http://wiki.icub.org/wiki/Linux:Installation_from_sources) and [yarp-wiki](http://www.yarp.it/install_yarp_linux.html).
After this step:
CREATE_OPTIONAL_CARRIERS, set to ON 
I should be able to do
 **_ENABLE_yarpcar_bayer_carrier, set to ON_**
however the closest thing to this is:
ENABLE_yarpcar_bayer
Is this the equivalent thing? If so it is probably better to update the wiki.
Best wishes
Pedro

**Comment by drdanz** [comment]
Yes, it is the same thing, the variable name is automatically updated if you use the old name.

I just updated the wiki. Thanks.
