### ISSUE TITLE
Broken IAnalog interfaces

### ISSUE THREAD

**Issue by elen4** [robotology/yarp#113]
Commit 394f752585f845ed7562df5483f99c5a8ee2631c changed the client implementation of the yarp::dev::IAnalog interface, which means that ALL server implementations (i.e., many of iCub drivers) have to be changed accordingly. @EnricoMingo is there a VERY good reason for this change?

**Comment by drdanz** [comment]
@barbalberto Was there any progress on this?

**Comment by barbalberto** [comment]
The code with the refactor of the portname with the new policy is on a branch to be tested.

**Comment by lornat75** [comment]
is anybody going to test it? Can you write down a wiki page with a summary of the policy?

**Comment by barbalberto** [comment]
I'm testing it

**Comment by barbalberto** [comment]
I did a small change to improve back compatibility with the skinManager.
The branch is currently on the red iCub to test it with old code that does not use the analogClient.

The new policy will look for parameter 'name' which will set the full port name (as client already does); if not found will fall back for the old parameters style 'robotName' + 'part' and will write the following warning message:

[WARNING] AnalogServer device:
************************************************************************************************
  AnalogServer is using deprecated parameters for port name! It should be:
       name:         full name of the port, like /robotName/deviceId/sensorType:o
       period:       refresh period of the broadcasted values in ms (optional, default 20ms)
************************************************************************************************ 

The  user code will work as before, just with the warning message.
If the user changes the config file to use the new parameter, he/she will get rid of the message. Note that he/she can still use the same old ugly portnames as before (just by typing it 'as is' in the config file) and the client (when used) will still be able to reach the server.
With the new policy the user can have a better port name as he/she wishes.

Shall I document only the new policy or also the deprecated one?

**Comment by lornat75** [comment]
The new policy is enough.

**Comment by barbalberto** [comment]
I think this issue can be closed due to new policy

**Comment by randaz81** [comment]
I suggest to close this issue after adding the `name` parameter to all the robots in the repos. We are currently having a lot of warning in the log because we are still using the old deprecated mode.
Davide Tome can help running on the repo the same script used for the controlBoardWrappers.

**Comment by barbalberto** [comment]
@randaz81 : can we close this issue now?

**Comment by randaz81** [comment]
@davidetome completed the task succesfully
