### ISSUE TITLE
some files missing license statement

### ISSUE THREAD

**Issue by paulfitz** [robotology/yarp#114]
The following files are missing copyright/author/license information:
```
extern/tinyxml/tinyxml/xmltest.cpp
src/carriers/portmonitor_carrier/lua_swig.h
src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.cpp
src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.h
CTestConfig.cmake
example/ros/add_int_client_v1.cpp
example/ros/CMakeLists.txt
example/ros/listener_v1.cpp
example/ros/add_int_server_v1.cpp
example/ros/add_int_client_v2.cpp
example/ros/talker.cpp
example/ros/listener_v2.cpp
```
@barbalberto can you take care of `AnalogWrapper.*`? @apaikan `lua_swig.h` is a generated file, do you know what the license of the sources it is generated from are?  Is anyone familiar with `xmltest.cpp`? @drdanz could you sort out `CTestConfig.cmake`?  The ros things are mine to fix.

**Comment by drdanz** [comment]
``CTestConfig.cmake`` is actually just a list of variables and was either taken from http://www.cmake.org/Wiki/CMake_Testing_With_CTest or generated from the dashboard, therefore I don't think that any copyright can be claimed... perhaps should be marked as public domain for the scripts?
The other files seem to be fixed...
