### ISSUE TITLE
yarpmanager enhancement

### ISSUE THREAD

**Issue by iron76** [robotology/yarp#115]
A useful feature of the gyarpmanager could be the possibility of starting multiple applications at the same time. This could be implemented by selecting one or more entities on the right column and then start and connect could act on all the selected entities at the same time. This could be useful especially when starting multiple datadumpers simultaneously.

**Comment by apaikan** [comment]
An "application" is the biggest entity which is handled in the yarp managers! In the graphical tools (e.g., `yarpmanager`) they are shown in the separate tabs and are handled  independently. Keeping them separated has the advantages to not intermixing their execution process in case that some of them may conflicts!

However, if someone needs to run multiple applications uniformly, yarp manager offers a better solution: **creating a compound application!** That is, to create e meta application and includes all the applications which user needs to launch together. 

```xml
<application>
    <name>My Compound aplication</name>

    <application>
        <name>Application1</name>
    </application>

    <application>
        <name>Application2</name>
    </application>

   <!-- etc. -->
</application>
```

**Comment by claudiofantacci** [comment]
Cool! I didn't know about **compound applications**.
Worth noting it down :-)
