### ISSUE TITLE
Inconsistency in documentation of IJoypadController::getButton method 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1191]
In the documentation of the method in https://github.com/robotology/yarp/blob/devel/src/libYARP_dev/include/yarp/dev/IJoypadController.h#L97 , it seems that the button output is boolean (true/false) but apparently the output parameter of the method is actually a `float` . 

@aerydna

**Comment by aerydna** [comment]
I've deleted the reference to boolean in documentation. At the early stage of development it was a boolean, by discovering that some joypad uses analog frontal button it became a float.
