### ISSUE TITLE
Documentation duplicated (comments both in cpp and h files)

### ISSUE THREAD

**Issue by aikolina** [robotology/yarp#1202]
The documentation on [yarp::os::Port::read()](http://www.yarp.it/classyarp_1_1os_1_1Port.html#a544b772e62021528bca3697fade7cd18) (and not only) has some information repeated:

> Read an object from the port.
> read something from the port

I guess it's because the function is commented both in the cpp ([Port.cpp](https://github.com/robotology/yarp/blob/master/src/libYARP_OS/src/Port.cpp)) and h ([Port.h](https://github.com/robotology/yarp/blob/master/src/libYARP_OS/include/yarp/os/Port.h)) files.

---

Then I noticed an error in the documentation on [yarp::os::Port::setReader()](http://www.yarp.it/classyarp_1_1os_1_1Port.html#a0211358f074d007b8fbf67c41b24ddc6):
> set an external **writer** for port data

where "writer" should be substituted by "reader".

**Comment by traversaro** [comment]
Yes, I think the problem is the doxygen-style documentation in cpp. 
In general Doxygen blocks should be only used in the headers of the class. 
In particular the comments in the cpp are relatively useless, so I think we can remove them.
