### ISSUE TITLE
Problem in using  Property& Bottle::addDict()

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/yarp#1208]
I found some problems in using the function  `Property& Bottle::addDict()`.

I need to implement the following steps:

**Code-1**
```cpp
RpcClient portRpc;
portRpc.open("name_port");

...

Bottle cmd, reply;
cmd.addString("desired_command");

Property &p=cmd.addDict();
p=extinsting_property;

cmd.addString("other_parameter");

portRpc.write(cmd, reply);

```

Unfortunately, **Code-1** doesn't work and the code blocks when the function `write()` is called.
However, I checked that the format of the `Bottle cmd` obtained with **Code-1** is correct:
```cpp
desired_command ((elem_property_no_1 ( value1 value2)) (elem_property_no_2 (value3 value4))) other_parameter
```
If I build `Bottle cmd` only with `addList()`, `addString()` and `addDouble()` functions, I obtain the same `Bottle cmd` I get from **Code-1** and function `write()` does not block.

Then,  I tried **Code-2**:

```cpp
Bottle cmd, reply;
//cmd.addString("desired_command");

Property &p=cmd.addDict();
p=extinsting_property;

cmd.addString("other parameter");

portRpc.write(cmd, reply);

```

the function `write()` doesn't block.

When I tried **Code-3**:

```cpp
Bottle cmd, reply;
cmd.addString("desired_command");

Property &p=cmd.addDict();
p=extinsting_property;

//cmd.addString("other parameter");

portRpc.write(cmd, reply);


```
 
function `write()` blocked again.

I think there are some problems with the function `addDict()`, is it possible?

**Comment by Nicogene** [comment]
As discussed with @giuliavezzani , the problem was on the server-side. `RpcClient.write()` expect a reply from the `RpcServer` and `addDict()` add extra parenthesis to the property that made fail her parsing on the server side. I close it for now.
