### ISSUE TITLE
URLs of Doxygen Pages are broken

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1218]
Currently all the URL pointing to doxygen documentation are broken. 

For example, the link http://www.yarp.it/tutorials.html in https://github.com/robotology/yarp#tutorials returns 404 error. 
http://yarp.it seems to redirect to http://yarp.it/master , so it would be nice to redirect http://www.yarp.it/tutorials.html to http://www.yarp.it/master/tutorials.html, and so on so forth. 

cc @drdanz @mbrunettini

**Comment by mbrunettini** [comment]
I am working on the documentation.
it's just a work in progress

**Comment by traversaro** [comment]
Ok, let's keep this issue open for anyone that is experiencing the same problem.

**Comment by traversaro** [comment]
Ok, I did not notice that apparently it is working now, closing.
