### ISSUE TITLE
Documentation about IJoypadController::getHat(unsigned int hat_id, unsigned char& value) method

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1222]
The documentation for the `IJoypadController::getHat(unsigned int hat_id, unsigned char& value)`  method do not explains how the `value` parameter should be interpreted . By experimental check on some existing driver, it seems that the activated direction of hat are encoded as bit set to 0 or 1 in the byte. Is this correct @aerydna ?

**Comment by aerydna** [comment]
it is correct. I'll update the documentation, along with other update and fix, before the release.

**Comment by drdanz** [comment]
Already merged. Closing.
