### ISSUE TITLE
move tutorials on RFModule from iCub wiki to YARP online documentation

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#123]

**Comment by drdanz** [comment]
@lornat75 Is this the tutorial that should be moved? http://wiki.icub.org/iCub_documentation/icub_tutorial_module.html

**Comment by lornat75** [comment]
Yes. But if I am not wrong iCub tutorials are also runtime tests. They are useful because they link against yarp in static and dynamic mode. If we move the tutorial we should maintain this as a test.

BTW, iCub tutorials have been moved to robotology/icub-tutorials is the documentation still generated from there?

**Comment by pattacini** [comment]
@lornat75 yes, the documentation is in robotology/icub-tutorials

**Comment by lornat75** [comment]
Added RFModule tutorial in YARP: https://github.com/robotology/yarp/commit/e9d934244c42a0e89c4ad4e0b3071046a5c4c27d

Removed RFModule tutorial in icub-tutorials:

https://github.com/robotology/icub-tutorials/commit/919b3faf88aa5d2597e3f8f39b78b73ebe11f194
