### ISSUE TITLE
Issue editing host value in yarpmanager

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1248]
If I change the value of the `host` parameter by editing the value shown in the gui, yarpmanager fails to check if the module is running, since it still try to connect to host specified in the configuration file (before the edit)
Instead, I'm able to launch modules on the modified host without any problem.

**Comment by Nicogene** [comment]
Are you on `devel` or `master`?

**Comment by Nicogene** [comment]
FIxed by #1251
