### ISSUE TITLE
yarplogger freezes after startup

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/yarp#1252]
After launching the logger from the ``yarpmanager`` or the terminal, the logger freezes when pushing some buttons (for example the refresh one) and it needs to be killed.

@Nicogene @gabrielenava @francesco-romano

**Comment by Nicogene** [comment]
Hi @S-Dafarra ,
I tried from terminal and `yarpmanager` both and it seems to work on my pc.
Are you on windows or linux?

**Comment by francesco-romano** [comment]
We tried on two different linux machines and in both cases `yarplogger` freezes.

**Comment by Nicogene** [comment]
At first glance `YarpLogger` doesn't seem to set any timeout for the connections, probably in the setup there are some dead ports and yarp logger when you press `refresh` awaits forever a reply from those ports

**Comment by S-Dafarra** [comment]
It seems working smoothly now! May some of the latest commits have affected this issue?

**Comment by drdanz** [comment]
Perhaps the same race condition affecting yarpmanager?

**Comment by Nicogene** [comment]
For now I close it, if this happens again, tell us and we will investigate!
