### ISSUE TITLE
More issues with High DPI screen

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1267]
Even after the recent changes, yarpscope and yarpview are not displayed correctly on high DPI screens.

![screenshot_20170613_102336](https://user-images.githubusercontent.com/1100056/27072974-83828456-5022-11e7-81c2-40d4cde8b71f.png)

![screenshot_20170613_102532](https://user-images.githubusercontent.com/1100056/27073013-abaeef6e-5022-11e7-86cd-906716f54f73.png)

CC: @Nicogene

**Comment by Nicogene** [comment]
Fixed by 23df76655ce07ba62472f1c31310b5b0e58e102b
