### ISSUE TITLE
"using namespace std" directive in several headers

### ISSUE THREAD

**Issue by aerydna** [robotology/yarp#1285]
i found the directive `using namespace std;` in 21 headers (libYARP_manager and yarpmanager plus one in the mainwindow.h of yarpdataplayer).

this can cause several problem.. for instance by including `vector` or `map` in ResurceFinder.h arise some ambiguities between std and libYARP_OS.

**Comment by francesco-romano** [comment]
I totally agree.
`using  namespace` (in general, not only `std`) should be prohibited at least in library headers.

**Comment by lornat75** [comment]
should --> must be prohibited! Please fix all library header files which contain the `using` directive.

**Comment by Nicogene** [comment]
Fixed by #1294

**Comment by pattacini** [comment]
it's not compiling... just fixing

**Comment by pattacini** [comment]
the problem was present only in `devel` after merging.
Fixed.

**Comment by drdanz** [comment]
@pattacini Thanks!
