### ISSUE TITLE
Java version problem in installing yarp for MATLAB in Ubuntu 16.04

### ISSUE THREAD

**Issue by Hteja** [robotology/yarp#1297]
Hi,
My ubuntu 16.04 system has  java 1.8 version in it. While I try to install the MATLAB bindings by following the instructions from the webpage, the LoadYarp and YarpImageHelper class files are built. But, when I run the LoadYarp command in matlab by adding the paths to the classpath.txt and also librarypath.txt, I get the following error

Java exception occurred:
java.lang.UnsatisfiedLinkError: /home/hari/yarp/bindings/build/libjyarp.so:
/usr/local/MATLAB/R2017a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not
found (required by /home/hari/yarp/bindings/build/libjyarp.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(Unknown Source)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at LoadYarp.<init>(LoadYarp.java:18)

I could not work around the issue. Most probably, the problem is due to the different java version that the yarp plugins need, but i'm not sure.

Thank you very much.

**Comment by traversaro** [comment]
Hi @Hteja , I don't think this error is Java-specific. 
See https://github.com/robotology/codyco-superbuild/issues/141 for a similar issue.
