### ISSUE TITLE
Clock not initialized for yarp command line suite

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#1319]
Upon merging #1316, warnings started showing up anytime I use the yarp command line suite.

The warning is the one related to the use of the system clock:

![capture](https://user-images.githubusercontent.com/3738070/29271345-3a178852-80fb-11e7-9bb2-a0681706cc56.PNG)

**We should also fix the warning message**:
- The clock is not ~~been~~ initialized
- or call~~ing~~ yarp::os::Network::init()

Affected commands I saw the warning for at the time being:
- `yarpserver`
- `yarp name list`
- `yarp rpc`

**Comment by barbalberto** [comment]
Ops, the message was printed too much... now fixed.
Thanks
