### ISSUE TITLE
Java bindings not compiling with YARP devel

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1327]
While fixing https://github.com/robotology/yarp/issues/1325 , I noticed that Java Bindings are currently not compiling on the YARP devel branch.

**Comment by drdanz** [comment]
Are they building on master?
This is getting out of control, we need someone working full time on CI 😭

**Comment by traversaro** [comment]
Yep they are working on master, the problem seems something related to https://github.com/robotology/yarp/pull/1277 .

**Comment by traversaro** [comment]
It will be fixed by https://github.com/robotology/yarp/pull/1372 .
