### ISSUE TITLE
yarp devel is not compiling in projects that do not compile using explicitly the C++11 flags

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1334]
It seems that https://github.com/robotology/yarp/blob/devel/src/libYARP_OS/CMakeLists.txt#L415 is not working as intended.

**Comment by claudiofantacci** [comment]
We should try with target_compile_features(<TARGET> PUBLIC cxx_std_11).

**Comment by traversaro** [comment]
The problem was fortunately more simple, i.e. a missing link libraries that was working fine because it was a static library, see https://github.com/robotology/codyco-modules/pull/241 .

**Comment by drdanz** [comment]
> We should try with target_compile_features( PUBLIC cxx_std_11).
@claudiofantacci cxx_std_11 is CMake 3.8 or 3.9, so we cannot use it yet...

**Comment by claudiofantacci** [comment]
>@claudiofantacci cxx_std_11 is CMake 3.8 or 3.9, so we cannot use it yet...

🙃
