### ISSUE TITLE
IPositionDirect::setPositions(const int, const int *, double *) should be setPositions(const int, const int *, const double *)

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1351]
`IPositionDirect::setPositions(const int n_joint, const int *joints, double * refs)` is never meant to modify the  `refs` buffer, so its signature should actually be `IPositionDirect::setPositions(const int n_joint, const int *joints, `**`const`**` double * refs)`.

This is indeed the signature of other similar three parameters set methods, such as:
* `virtual bool positionMove(const int n_joint, const int *joints, const double *refs)`
* `virtual bool relativeMove(const int n_joint, const int *joints, const double *deltas)`
* `virtual bool velocityMove(const int n_joint, const int *joints, const double *spds)`

**Comment by damn1** [comment]
As discussed, this issue seems not to be solvable without compatibility problems. Should it be a "won't fix"?

**Comment by traversaro** [comment]
Unfortunately I am afraid this is the only option, unless we change the name of the methods (not desirable as well because it is too destructive).

**Comment by drdanz** [comment]
:-1:
At some point we will have to break something...

**Comment by drdanz** [comment]
The option described [here](https://stackoverflow.com/questions/49011990/) seems to be the less invasive option. Still we cannot get a build time warning when overriding the function, but we can add a runtime warning instead.

**Comment by lornat75** [comment]
looks like a mistake while writing the function :(

**Comment by drdanz** [comment]
Fixed in #1704
