### ISSUE TITLE
On Windows "yarpdev --list" command results in segmentation fault.

### ISSUE THREAD

**Issue by damn1** [robotology/yarp#1357]
The program is blocked while trying to split the text describing devices:
```
Device "test_motor", C++ class yarp::dev::TestMotor, wrapped by "controlboard"
Device "remote_grabber", C++ class yarp::dev::RemoteFrameGrabber, wrapped by "grabber"
Device "grabber", C++ class yarp::dev::ServerFrameGrabber, is a network wrapper.
...
```
into lines with single device. It stops on the invocation of  getline function from ConstString class:
```
    inline std::istream& getline(std::istream& is, yarp::os::ConstString& str, char delim) {
        return getline(is, (std::string&)str, delim);
    }
```
where `is` seems to be void.

**Comment by barbalberto** [comment]
Any update on this issue?

**Comment by damn1** [comment]
I searched about this the day we discovered it, but in the end I was not able to solve the problem, it seems to be something non trivial. If you want we can discuss the details about this issue f2f.

**Comment by drdanz** [comment]
On which Visual Studio version have you tried this?

**Comment by damn1** [comment]
VS2015, sorry I didn't write it in the description of the issue. I remember @aerydna also tested it.

**Comment by randaz81** [comment]
Also VS2013 Ultimate

**Comment by francesco-romano** [comment]
@drdanz in `ConstString` there is the cast defined:
`operator std::string()`.
