### ISSUE TITLE
Anomaly in computational load?

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#137]
Repeatable situation (I'm talking about iCubGenova01 but I think that this applies to other robots as well):

- Turn on the iCub (robotInterface, gyarpmanager, etc)
- Turn on Calib_Cameras, iCubStartup, Skin_Gui_All_V2, iCubGui (just to test a standard startup)
- Do the "top" command on some of the machines (screenshot below - right terminal is icub15 [core i7 + SSD], left terminal is icub13 [core i7 + SSD], bottom terminal is icub-b1)
![cpu](https://f.cloud.github.com/assets/4378663/2321934/fe600aea-a3aa-11e3-8cf0-398b8d21366a.png)
- Most of the processes - started moments before - are firing up their respective cpu.

I can expect higher cpu load from modules like wholeBodyDynamics, but I think that mere viewers such as yarpview an iCubSkinGui shouldn't burden the machines they belong to so much. In my opinion, even the skinManager/camCalib's load is too high.

Unfortunately, I don't have any comparison with the past, but I suppose that this is a recent bug (otherwise, someone else would have noticed before me).

**Comment by drdanz** [comment]
@alecive Is this still an issue or can we close this?

**Comment by alecive** [comment]
Sorry I got the notification only now. Closing.
