### ISSUE TITLE
SWIG bug with Debian Jessie 

### ISSUE THREAD

**Issue by valeriosperati** [robotology/yarp#1380]
Hi, I found a little bug trying to compile Python bindings in Linux.
The suggested swig package  
[http://www.yarp.it/yarp_swig.html#yarp_swig_linux](url)
installs swig 2.0 which, on my system (Debian Jessie 8.9 ), involves an error while compiling yarp.
Installing swig 3.0 solves the problem.

(not sure it is the right place to advise a bug)
Valerio

**Comment by traversaro** [comment]
Thanks, this is indeed a documentation bug. 
Of the Debian-based distro that we support in http://wiki.icub.org/wiki/YARP_Supported_Distributions , 
we have that in Ubuntu >= 16.04 and Debian >= Stretch `swig` is indeed the correct package (it depends on `swig3.0`). The only supported Debian-based distribution in which it is necessary to install explicitly `swig3.0` is indeed Jessie, so we should add a note about this.
