### ISSUE TITLE
 yarp/example/matrix/gsl_example.cpp is not compiling

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1395]

**Comment by Nicogene** [comment]
#896 removed `getGslVector` and `getGslMatrix`. Should we remove this example?

**Comment by traversaro** [comment]
I think we can migrate it to be an example for the `libYARP_gsl` library, that provide similar facilities to use GSL-methods with YARP matrices.

**Comment by Nicogene** [comment]
Ok I'm on it!
