### ISSUE TITLE
The "Check All" function of the Cluster Management Window in yarpmanager doesn't check if the yarprun port is still active

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/yarp#1401]
If we launch ``yarprun`` on the robot's head (using ``yarpmanager``) and then we shut the head down, the status in the ``Cluster Management Window`` remains green, even if we press ``Check All``.

@Nicogene @gabrielenava

**Comment by Nicogene** [comment]
The nameserver runs on the head?

**Comment by francesco-romano** [comment]
@S-Dafarra have you tried a `yarp clean`?
Usually `yarprun` creates a port, and that port is checked by the manager

**Comment by Nicogene** [comment]
@francesco-romano  is right, if you do not perform yarp clean, the port with the `yarprun` property is still registered in the nameserver, so for the cluster is still there.

**Comment by S-Dafarra** [comment]
> The nameserver runs on the head?

Nope
> @S-Dafarra have you tried a yarp clean?

Nope :grin:. But it was not necessary with the old cluster if I remember well.

**Comment by Nicogene** [comment]
The old cluster did "Network::exists()" so I think that it is the same case. If the cluster continues to see "green" the head also after the `yarp clean` then there is a bug, otherwise I think it is correct as it is. Eventually I can add a `yarp clean` button in `yarpmanager` :wink:

**Comment by S-Dafarra** [comment]
I see, thanks. If we can then talk about enhancements, 
- is it possible to do the check automatically? I.e. can we comunicate with the specific port to see whether it is still active (similar to what ``yarp clean`` does)?
- can ``Stop Selected`` or ``Kill Selected`` make it "red" in case of no response. Otherwise one may be wondering why ``yarprun`` refuses to close while instead it is already dead :grin:

**Comment by Nicogene** [comment]
Ok for the first point, I don't think it is a big problem to implement it.
About the second point `Stop Selected` `Kill Selected`  are simply : `ssh user@node killall yarprun` and `ssh user@node killall -9 yarprun`, if the node is shut down it doesn't do nothing :sweat_smile: 
Thanks for the feedback!

**Comment by S-Dafarra** [comment]
> Ok for the first point, I don't think it is a big problem to implement it.

 Great! :smiley: 
>if the node is shut down it doesn't do nothing 

Maybe if the first point can be achieved, after the ``ssh user@node killall -9 yarprun`` command, the same check could be performed to turn the state to "red". 
>Thanks for the feedback!

Thank you for supporting :wink:

**Comment by Nicogene** [comment]
Fixed by #1414
