### ISSUE TITLE
arbitrary ip adress with yarpserver --read (ubuntu)

### ISSUE THREAD

**Issue by aerydna** [robotology/yarp#1404]
in ubuntu, despite configuring yarp on a arbitrary unexistent ip adress, the command `yarp server --read` start the server instead of fail (as it should because of unexistent configured adress).

example:

launch:
`yarp conf <arbitrary unexistent ip here> <arbitrary port here>`

then launch:
`yarp server --read`

problem: it seems yarp server to start correctly.

**Comment by claudiofantacci** [comment]
I don't understand this issue. Could you please rephrase the problem and provide an example?
In particular, I don't understande
> `yarpserver` with the --read param print on the terminal a (obviously false) correct start.

**Comment by drdanz** [comment]
Fixed in #1404

**Comment by randaz81** [comment]
There exists a very limited and specific use case in which the user wants to start the yarp server using the --read option even if the specified ip address is not currently available (for example when using a wi-fi)
#1457 forbids it. We need to reformulate this fix.

**Comment by valegagge** [comment]
@randaz81 just out of curiosity....why when we use wifi we don't know the ip address?

**Comment by randaz81** [comment]
Additional use cases include yarp usage with DMZ and NAT.
commit 7ec99a6c73729 has been reverted: the original behavior of yarp --read has been restored.
