### ISSUE TITLE
ImageOf - FlexImage conversion on read

### ISSUE THREAD

**Issue by aerydna** [robotology/yarp#1408]
by sending a `yarp::sig::ImageOf<PixelRgb>` and receiving it as a `yarp::sig::FlexImage`, some of the metadata of the original image are lost. the metadata tested at the moment are `pixelsize` and `padding`.

for example code see #1409

**Comment by drdanz** [comment]
Padding can be calculated if you know the quantum...
I think that the problem is just that they are not *restored*, but all the information necessary to calculate them is probably already there...

**Comment by aerydna** [comment]
(will be) fixed by #1426
