### ISSUE TITLE
YARP cannot read correctly the ROS topic `\tf` 

### ISSUE THREAD

**Issue by aikolina** [robotology/yarp#1419]
I have noticed that when running the following commands:
* `roslaunch robotStatePublisher.launch`
* `yarpdev --device transformServer --ROS::enable_ros_publisher 1 --ROS::enable_ros_subscriber 1 --transforms_lifetime 0.5`

I obtain a different outcome according to the order in which I run them.

If the order is:
1. `transformServer`
2. `robotStatePublisher`

then everything is all right and I can read both the data published in `\tf` and `\tf_static`.

On the contrary, if the order is:
1. `robotStatePublisher`
2. `transformServer`

there is something wrong and I can read only the data published in `\tf_static`. :disappointed: 

I am not sure if it is somehow related, but also the order with which they are closed seems to matter. If I stop first `robotStatePublisher` and then `transformServer`, then the `transformServer` hangs up and I need to kill it. If I do the opposite, both of them are stopped correctly.

**Comment by randaz81** [comment]
I'm going to close this issue and split it into multiple issues. The problem described here is actually not related to /tf topic. Indeed, this is a generic issue affecting all ROS topics and yarp::os::Subscribers. The order in which the executables are started by the user is not important. On the contrary, we suspect that killing a yarp Subscriber without calling close() might affect the sanity of future connection performed on the same topic.
A list of the new issues originated from this topic will be reported below.
