### ISSUE TITLE
yarp server & localhost

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#142]
I found this behaviour happening a few times and I think it is a small bug, but still quite confusing for newbies.

Let imagine you have 2 PCs, where PC1 is running the yarp server and some yarp applications while the PC2 is running other yarp applications.

At the start-up PC1 had no internet connection, but someone nevertheless run the yarp server on it. Since it has no valid ethX, the yarpserver binds to the localhost 127.0.0.1. After that the connection goes up and PC1 gains its eth0 ip address, e.g. 10.0.0.1.
A simple test case can be done (for linux user) in this way:
   sudo ifconfig eth0 down
   yarpserver
   sudo ifconfig eth0 up
We open a port on the PC1 using 
   yarp read /read. 

PC2 does an yarp detect and it correctly finds out the yarp server on the PC1; the yarp name list will say:
registration name /read ip 127.0.0.1 port 10001 type tcp

meaning that it is able to talk to the name server and get back the port list, but the ip address of the port is obviously not correct!!

In fact if I try to connect to this port
   yarp write /write
   yarp connect /write /read
the connect command will hang up, neither succeding nor failing and the connection won't be established. PC2 tries to connect to itself, instead of connecting to PC1.

This is a wrong usage of the server, and we could simply blame the user, but the worst thing is that, for some reasons (probably good ones, I don't know), the yarp server will write the last used ip in the yarp conf file, therefore the next time it is started, EVEN IF this time the connection is up and working, the yarp server will still prefer the localhost, falling back in the very same not-working configuration. This I think should not happen.

The very same happens if there is a virtual machine player installed on the machine because the ip address of the virtual device can be took in place of localhost. The result is the same.

My suggestions are:
- If it is not strictly needed, the yarp conf should not be modified without the user knowledge
- If no "real interface" are available and the yarpserver will falls to use localhost, then the server SHOULD NOT START AT ALL. I means, a server that cannot connect to anything is quite useless, isn't it? To force the behaviour if I'm playing just on my laptop we can start it like
 yarpserver --localhost  -> in this case the server will run ONLY using localhost, even if other interfaces are available. (This will also avoid conflicts in case of multiple servers on the same subnetwork.)
- Ideally we shoul also put virtual mechine interfaces on a "black list" unless we want to use them on purpose.

**Comment by drdanz** [comment]
@paulfitz @barbalberto Is this still an issue or can we close this?

**Comment by paulfitz** [comment]
I'll close. There is more that could be done, but it all comes at a cost. E.g. port registrations could be automatically cleaned up at the price of more administrative network traffic that could cause tiny periodic delays in message transmission for users. Would that matter? For most people, no, for some people, yes. On balance, not something to be sorted out just in a github issue.
