### ISSUE TITLE
Release of drdanz v1.38.0

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#1428]
DRDANZ 1.38.0 (2017-10-24) Release Notes                                {#v1_38_0}
======================================

Important Changes
-----------------

### Libraries

* A lot of refactoring was performed in order to improve c++11 usage and to
  simplify porting to other platforms without ACE

#### `DANZ_family`

* Added new daughter `Marta`.

#### `DANZ_work`

* Added three new slaves : @Nicogene,  @aerydna, @damn1.

#### `DANZ_fun`

* Increased abilities with Kirby in Super Smash Bros.
* Added `Nintendo Switch`. 

@drdanz  is the **maintainer** that `YARP` deserves, but not the one it needs right now.

Happy BDAY  :tada: :tada:

**Comment by aerydna** [comment]
this release looks almost good to me.. it seems something is missing

**Comment by aerydna** [comment]
ah.. there is a pr still under test.. i think it will finish by October 27th

**Comment by Nicogene** [comment]
This PR will be an **odissey** ....

**Comment by randaz81** [comment]
UH this PR has been already closed but I didn't have the chance to review it?!

**Comment by drdanz** [comment]
Merged, thanks.
