### ISSUE TITLE
Enable multicore compilation on windows VS

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1448]
CMake should add /MP option in each generated project. It seems off by default (at least on VS2013 TBC)

e.g.
https://stackoverflow.com/questions/1422601/how-do-i-turn-on-multi-cpu-core-c-compiles-in-the-visual-studio-ide-2008

**Comment by drdanz** [comment]
This is not something that can be resolved in YARP, please report a bug upstream in CMake if you want to support this.
