### ISSUE TITLE
YARP-ROS communication fails with ROS running on WSL

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1474]
Tested on Windows 10, build 16299 (Fall Creators Update). 
WSL Running Ubuntu 16.04.03 with ROS lunar.

ROS fails to perform connections due to a suspected bug in **ros_comm** `1.13.2-0xenial-20171012-115727-0800`. A simple test case is rviz failing to display any /tf, published either by ROS or YARP. 
Requires more investigation on next ROS release.

**Comment by randaz81** [comment]
Relevant infos:

- https://answers.ros.org/question/238646/installing-ros-on-ubuntu-bash-in-windows-10/
- https://github.com/ros/ros_comm/pull/1050
- https://github.com/ros/ros_comm/pull/1202

**Comment by drdanz** [comment]
This does not look like a bug in YARP...

**Comment by randaz81** [comment]
Indeed. It is not. I put the issue here so if someone searches WSL in the YARP issues can know that someone has already tested it and that some problems have been found.

**Comment by drdanz** [comment]
Closing then... 😉
