### ISSUE TITLE
Dashboard warnings

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#148]
YARP [dashboard](http://dashboard.icub.org/index.php?project=YARP) gives a lot of warnings, and every time you commit, it sends emails like this to the author of the commit.

```
A submission to CDash for the project YARP has build warnings.
You have been identified as one of the authors who have checked in changes
that are part of this submission or you are listed in the default contact
list.
```

We should clean the dashboard of all the warnings.

**Comment by drdanz** [comment]
Update: dashboard is now clean on all supported linux versions.

@paulfitz Can you have a look at this warning on windows?

```
12>e:\sources\yarp\src\carriers\wire_rep_utils\WireTwiddler.cpp(871): warning C4244: '=' : conversion from 'yarp::os::NetFloat64' to 'yarp::os::NetFloat32', possible loss of data
```

about the other warnings (always on windows) are [``src/idls/thrift/src_gen/parser.cc``](https://github.com/robotology/yarp/blob/master/src/idls/thrift/src_gen/lexer.cc) and [``src/idls/thrift/src_gen/parser.cc``](https://github.com/robotology/yarp/blob/master/src/idls/thrift/src_gen/lexer.cc) generated automatically? Perhaps we can just turn off these warnings on them.

**Comment by paulfitz** [comment]
Made the WireTwiddler cast explicit, it is legitimate. The `thrift/src_gen` stuff is indeed generated code, and I think turning off warnings is the right thing to do in this case. There appears to be a fork of flex/bison http://sourceforge.net/projects/winflexbison/ that generates codes with less (no?) warnings under msvc. But just turning off the warnings for this section seems saner.

**Comment by drdanz** [comment]
Also windows now is really quiet :+1: 

About mac, I just had a very quick look, and I noticed this one that looks interesting:

> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/semaphore.h:55:5: note: 'sem_init' has been explicitly marked deprecated here
> int sem_init(sem_t *, int, unsigned int) __deprecated;

Looks like that Apple deprecated unnamed semaphores for some reason, here you can find some further explaination.

https://stackoverflow.com/questions/27736618/why-are-sem-init-sem-getvalue-sem-destroy-deprecated-on-mac-os-x-and-w

Anyway, the only call to sem_init seems to be in POSIXSemaphoreImpl.h, that this should be included only in ``__linux__``, but this warning seems to be coming from ace/OS_NS_Thread.inl

**Comment by paulfitz** [comment]
On OSX the semaphore implementation we use should be the one in MachSemaphoreImpl.h, which uses the native api. So I think we're already doing all we can here within yarp itself. And without taking control of how ace is compiled, I don't know what we can do there. We could fiddle with the homebrew ace formula (which we contributed to in the first place) if there are options that can be set. ACE upstream will take reasonable patches for OSX issues.

**Comment by drdanz** [comment]
The dashboard was dismissed. Closing this
