### ISSUE TITLE
Do a new minor release of YARP including https://github.com/robotology/yarp/pull/1465 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1486]
This is necessary to fix https://github.com/robotology/homebrew-formulae/issues/9 .

**Comment by drdanz** [comment]
Planned for this afternoon...

**Comment by drdanz** [comment]
Sorry, I had to reschedule this, I want to ensure that master is still building after the last commits.
I will try to do it this week end or, more likely, next week.

**Comment by drdanz** [comment]
Done. See https://github.com/robotology/QA/issues/267
