### ISSUE TITLE
CMP0071 compliancy

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/yarp#1494]
Compiling `YARP` on `devel` with `CMake >=3.10`, several [CMP0071](https://cmake.org/cmake/help/latest/policy/CMP0071.html?highlight=cmp0071) are thrown.

I'm investingating this, but I think we can take care of this before the next release.

cc @drdanz

**Comment by drdanz** [comment]
Fixed in devel (bc4f3e2f30342df01acc7cd91fca28672522c53b) and cherry-picked in master (46ca57cec82718dbe9061bdd6a3a51481b1b895b), will be in YARP 2.3.72.1
