### ISSUE TITLE
Icub_SIM image processing:

### ISSUE THREAD

**Issue by muhammadbilalababsi** [robotology/yarp#1511]
Hi everyone. i am currently working on image processing for icub_SIM and i got a sample code for it. can anyone please help me that what is purpose of this line of code in python. as This symbol(<>) seems strange to me. 

if left_eye_yarp_image.getRawImage().__long__() <> left_eye_img_array.__array_interface__['data'][0]:

Thanks

**Comment by drdanz** [comment]
Issue moved to [robotology/icub-main #485](https://github.com/robotology/icub-main/issues/485) via [**ZenHub**](https://www.zenhub.com/)
