### ISSUE TITLE
Setting yarpserver ip and port within code

### ISSUE THREAD

**Issue by dcam0050** [robotology/yarp#1514]
More of a request for help rather than an issue.

I have compiled Yarp in C# to integrate it with the Unity Game Engine and it works well however I would like to deploy the game without requiring the user install yarp on their device.

The device will however be present on a local network that has a yarpserver running on another computer. My question is how do you set the ip address and port for yarpserver in the code such that it can be found during a Network.init()?

**Comment by Nicogene** [comment]
Hi @dcam0050 !
check this : http://yarp.it/classyarp_1_1os_1_1NetworkBase.html#a68a57b1493c8d9ce73b22801a6c32f85 .
I never used it but it could it what you are looking for.
Let me know if it solves your problem!

**Comment by francesco-romano** [comment]
@dcam0050 you can also take a look [here](https://github.com/francesco-romano/iYarp/blob/master/libs/yarp_iOS/yarp_iOS/Utilities/IITYarpNetworkConfiguration.mm#L67)
even if I wrote that code almost 3 years ago

**Comment by dcam0050** [comment]
@Nicogene The setNameServerContact method works perfectly. Thanks!
