### ISSUE TITLE
yarp_prepare_device deprecated

### ISSUE THREAD

**Issue by amaroyo** [robotology/yarp#1533]
Hey there, 

I wrote an [issue](https://github.com/robotology/speech/issues/17) in speech/svox regarding ```yarp_prepare_device``` however I am not sure whether it should go here. Please, let me know!

**EDIT: ```yarp_prepare_device``` is changed properly, however I still have a linking problem between ```YARP``` and ```SVOX```.**

Thanks!

**Comment by traversaro** [comment]
Closing as we are already addressing the issue in https://github.com/robotology/speech/issues/17 . 

@amaroyo Consider that in GitHub, if you edit a message instead of posting a new reply no one receives a notification that the issue was updated.
