### ISSUE TITLE
macOS travis build broken

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1539]
macOS builds on travis currently are failing with this error.

```
$ if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```

I think the science tap was required for opencv.

**Comment by drdanz** [comment]
related issue: robotology/homebrew-formulae#12

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/yarp/pull/1535 .

**Comment by drdanz** [comment]
Cherry-picked the 2 commits. Thanks
