### ISSUE TITLE
getDirectorySeparator() and getPathSeparator() should be constexpr

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1550]
`yarp::os::NetworkBase::getDirectorySeparator()` and `yarp::os::NetworkBase::getPathSeparator()` are good candidates to be changed to `constexpr`.

**Comment by Squadrick** [comment]
@drdanz Currently `yarp::os::NetworkBase::getDirectorySeparator()` and `yarp::os::NetworkBase::getPathSeparator()` have a return type of `std::string`, and can't be made into `constexpr`. One possible solution is to make the return type `std::string_view` which exists only in C++17.

**Comment by drdanz** [comment]
@Squadrick Thanks for pointing that out. That's the main reason we didn't change it, we do not support C++17 yet...

**Comment by Nicogene** [comment]
Related PR https://github.com/robotology/yarp/pull/2062
