### ISSUE TITLE
Include directories and namespaces for yarpidl_rosmsg generated files

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1564]
The files generated by yarpidl_rosmsg are corresponding to the files for ros messages. Also the namespace is the same. This could cause issues in case one should include both yarp and ros in the same project. Also installing these files will cause issues, since these will clash with ros ones. I suggest we move them in a `yarp` or `yarp::ros` namespace, i.e.

* `<yarp/std_msgs/Header.h>` or <yarp/ros/std_msgs/Header.h>` instead of `<std_msgs/Header.h>`
* `yarp::std_msgs::Header` or `yarp::ros::std_msgs::Header` instead of `std_msgs::Header`

What do you think?

**Comment by Nicogene** [comment]
:+1:

**Comment by drdanz** [comment]
Maybe `yarp::rosmsg::std_msgs::Header`?

**Comment by drdanz** [comment]
Fixed in #1574
