### ISSUE TITLE
License for generated files

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1576]
Generated files currently don't have a license. Usually it is assumed that files without a license statement are "all right reserved", and it would mean that the files are not BSD, and therefore YARP_dev binary could not be BSD.

I think we should modify the idl generators so that they add a BSD boilerplate to those files, to make it clear that you can use them in your code.

CC @lornat75

**Comment by drdanz** [comment]
Fixed in a39f09ef19969b1412bc4318ed0559174e489358 for `yarpidl_rosmsg`, still needs to be fixed for `yarpidl_thrift` and a few other files generated by cmake

**Comment by Nicogene** [comment]
Closed by #1714
