### ISSUE TITLE
Include examples in the main build

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1585]
Many examples are outdated and probably no longer build.
I think that we should add them to the main build (with some flag `YARP_COMPILE_EXAMPLES` disabled by default), so that we can easily notice when some of them should be updated.

**Comment by traversaro** [comment]
Instead of adding them to the main build, adding them as a separate project, and just adding in Travis/AppVeyor/Jenkins the code to build them externally would ensure that the YARP CMake config machinery is always working.

**Comment by drdanz** [comment]
Another big problem is that the documentation contains full examples inside the doxygen files. Instead they should include files from examples, so that they are easier to test and we can ensure that they are updated.
