### ISSUE TITLE
yarp-config triggers homebrew warning

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#1630]
Typing: `brew doctor` I get this warning:

```bash
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/nicologenesio/robotology/yarp/build/bin/Debug/yarp-config
```
@claudiofantacci @vtikha @traversaro can I safely ignore it or is it an issue?

**Comment by Nicogene** [comment]
Yet Another Question, what is `yarp-config` ? 😅

**Comment by pattacini** [comment]
Here's a link: [yarp-config](http://www.letmegooglethat.com/?q=yarp-config) 😛

**Comment by claudiofantacci** [comment]
> can I safely ignore it or is it an issue?

You can safely ignore it.

A side note: `brew doctor` is a command used by `brew` maintainer to debug issues reported by the users. The output of the command does not strictly imply any error in your configuration.

**Comment by Nicogene** [comment]
ok thanks for the tip :wink:
