### ISSUE TITLE
TcpConnector::connect is blocking with a remote nameserver

### ISSUE THREAD

**Issue by damn1** [robotology/yarp#1636]
When compiled without ACE `TcpConnector` is used over `ACE_SOCK_Connector`.

https://github.com/robotology/yarp/blob/89570fc159c20e8584b7a5778e71f518275fc3a9/src/libYARP_OS/src/SocketTwoWayStream.cpp#L29-L47

While `ACE_SOCK_Connector::connect()` accepts a timeout parameter, `TcpConnector::connect()` seems to be blocking when the nameserver is remote. So every call that attempts to make a connection with the nameserver (example `Network::checkNetwork()`) blocks for ~1 minute if the nameserver is not open.
This is the blocking line:

https://github.com/robotology/yarp/blob/89570fc159c20e8584b7a5778e71f518275fc3a9/src/libYARP_OS/src/TcpConnector.cpp#L84

**Comment by drdanz** [comment]
This might help: https://stackoverflow.com/questions/2597608
