### ISSUE TITLE
 idl::rosmsg::demo::run and  idl::thrift::demo::run take one minute each to run on Windows, slowing down AppVeyor

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1643]
This two tests take one minute to run on Windows, probably due to the fact that they actually invoce CMake and Visual Studio to build a demo project. I think we should fine a way to disable them, at least on some AppVeyor  builds

**Comment by drdanz** [comment]
I don't know, these tests and thrift used to be broken on windows because they were disabled.
IMHO, the problem is not the number of tests but the testing infrastructure.

**Comment by traversaro** [comment]
>  IMHO, the problem is not the number of tests but the testing infrastructure.

That's true, but I think that even fixing some immediate problems would be also good, until we have something better. 
However, I was not proposing of removing those tests from all the jobs, but at least from some of them.

**Comment by traversaro** [comment]
However, this was just a suggestion based on my observation of the AppVeyor build, we can just ignore it and close the issue, no problem.

**Comment by drdanz** [comment]
We could have this test only on one build, and skip it on the others... This would improve build time by ~7 minutes, total build time is at the moment 2 hours and 12 minutes, hence not a great improvement, I'm not sure if it is worth to spend time on it...

**Comment by traversaro** [comment]
Ok, it make sense, closing.
