### ISSUE TITLE
YARP tutorials CMakeLists corrupt text

### ISSUE THREAD

**Issue by mebbaid** [robotology/yarp#1653]
Simple tip for new people like myself, when ```.\cmake```, make sure to write the ```CMakeLists.txt``` rather than copy/paste , corrupt text from the YARP tutorials section on this tends to generate config errors, e.g. ```ADD_EXECUTABLE called with incorrect number of arguments``` , and writing things down, besides learning value, tends to eliminate such unknown errors

**Comment by traversaro** [comment]
Hi @mebbaid , do you think there is any way to improve the existing tutorial to address or warn the user about the problem that you area mentioning? 
If you want to try to improve them yourself, the tutorial "source code" is available (for example) in https://github.com/robotology/yarp/blob/e0ca8e6f73c37286734d06e3afb8015529ee36b9/doc/yarp_cmake_hello.dox , and the whole yarp.it website can be generated locally on your PC (if you have Doxygen ( http://www.doxygen.org/ , `doxygen` package on Debian/Ubuntu ) installed on your machine) just by running the `make dox` target on your YARP build directory (`build/robotology/YARP` if you are using the robotology-superbuild).

**Comment by mebbaid** [comment]
@traversaro I think the simple thing would be to replace "Save the following as" with "write the following in <Your_filename.extention>" whenever it occurs in tutorials, specially in the (using Cmake) and (getting started with your devices) sections.
I will make a note of following your instructions on doxygen and the website, and trying to improve this myself, but probably not right-away

**Comment by traversaro** [comment]
Ok! Feel free to ask if you need any help in preparing the Pull Request. The general procedure for contributing changes in YARP is documented  in  https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md .
