### ISSUE TITLE
Proposal of improvements on bindings/lua/tests/test_string.lua

### ISSUE THREAD

**Issue by jgvictores** [robotology/yarp#1656]
Proposals on current [bindings/lua/tests/test_string.lua](https://github.com/robotology/yarp/blob/09202172baa31a7ae3639e52dea9c7d55f757f75/bindings/lua/tests/test_string.lua):
1. Rename to more representative `test_port.lua`
1. The structure of `bindings/lua/tests` is asymmetric, and the justification from [here](https://github.com/robotology/yarp/blob/09202172baa31a7ae3639e52dea9c7d55f757f75/bindings/lua/tests/CMakeLists.txt#L5) reads: `test_string.lua uses the yarpserver, so for now it is not include in the CTest infrastructure`. It seems like it could benefit from `yarp::os::NetworkBase::setLocalMode(true)` as done in many C++ tests.

Does this sound reasonable/doable?

cc: @traversaro

**Comment by traversaro** [comment]
I think it make sense, even if I do not know if `yarp::os::NetworkBase::setLocalMode(true)` is wrapped in the bindings and if there is strange detail of the implementation that will prevent this to work. I think the only way to know for sure is to try and see if some problem arise! : )

**Comment by drdanz** [comment]
I think that the `yarp::os::NetworkBase::setLocalMode(true)` will only work if you create a `NameStore` and use `yarp.queryBypass(store)`, please have a look at https://github.com/robotology/yarp/blob/c23b8d3944bb0a2cb64f03910e888e2954fa987a/tests/libYARP_OS/harness.cpp#L39:L44

**Comment by drdanz** [comment]
I don't know if these methods are wrapped for the bindings though...

**Comment by jgvictores** [comment]
It turns out that `setLocalMode` is wrapped and can in fact be invoked in several ways (statically or through an object, and through `Network` or `NetworkBase`).

It's interesting to know about `NameStore`, but I've never required touching it for working in `setLocalMode(true)`.

BTW, `setLocalMode(true)` is pretty interesting. Ports are open on `localhost`: you can actually register them on a `yarpserver` and then communicate with them from a different program. Intuitively, I thought ports got restricted to the process, not to the machine... of course accessing them becomes less straightforward. : )

PR at #1674.

**Comment by drdanz** [comment]
Fixed by @jgvictores in #1674.
