### ISSUE TITLE
yarp::os::Value constructors should be explicit

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1667]
These constructors

```c++
    Value(int x, bool isVocab = false);
    Value(double x);
```

allow to do *evil* things, I believe they should be explicit, forcing the user to call `Value` constructor when assigning stuff.

Unfortunately this is a breaking change, and I believe that this is used in several places outside YARP (and in YARP unit tests).

**Comment by pattacini** [comment]
I'm in favor of making them explicit!

**Comment by drdanz** [comment]
Will be fixed in https://github.com/robotology/yarp/pull/1677

**Comment by drdanz** [comment]
Fixed in https://github.com/robotology/yarp/pull/1677
