### ISSUE TITLE
Deprecate IAmplifierControl in YARP 3? 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1694]
Given that we are heavy cleaning up the interfaces available in YARP,  what do you think of also deprecating/removing the `IAmplifierControl` interface? As far as I understand, this interfaces as been superseded and subsumed by `ICurrentControl`, `IControlMode2`, `IPIDControl` and so it can be deprecated/removed now. 

cc @randaz81 @lrapetti @Nicogene

**Comment by Nicogene** [comment]
Unfortunately I have no knowledge about the interface `IAmplifierControl`, if you say that it is abandoned I think we can deprecate it :wink:

**Comment by barbalberto** [comment]
A few methods, I think, can be deprecated like:
```
virtual bool enableAmp(int j)=0;
virtual bool disableAmp(int j)=0;
virtual bool getAmpStatus(int *st)=0;
virtual bool getAmpStatus(int j, int *v)=0;
```
@randaz81 are they still used on can or are they superseded by `SetControlMode(idle/run)`?

The other methods are still in use, for example:

```
 virtual bool setPeakCurrent(int m, const double val) {return false;};
 virtual bool setPWMLimit(int j, const double val) {return false;};
 virtual bool getPowerSupplyVoltage(int j, double* val) {return false;};
```
are used to get/set values related to the last stage of firmware motor control.

PWM values here are different from PidOutput, if I remember correctly.

**Comment by randaz81** [comment]
> As far as I understand, this interfaces as been superseded and subsumed by ICurrentControl, IControlMode2, IPIDControl

None of these methods should be deprecated.
Simply keep `enableAmp`&C unimplemented on our robot. Simulators can implement them. 
The meaning is the following: irrespective of the control mode, if the amp is enabled, the output of the controller is applied to the joint, otherwise zero is applied.

**Comment by traversaro** [comment]
> The meaning is the following: irrespective of the control mode, if the amp is enabled, the output of the controller is applied to the joint, otherwise zero is applied.

So if we have a joint in POSITION_CONTROL control mode, calling `disableAmp` set the PWM input of the motor to zero, but **without** changing the control to IDLE?
