### ISSUE TITLE
opencv grabber

### ISSUE THREAD

**Issue by mike-talmage** [robotology/yarp#1720]
opencv_grabber compiles fine but when i try to use it it says

yarpdev: symbol lookup error: /usr/local/lib/yarp/yarp_opencv.so: undefined symbol: _ZN2cv12VideoCaptureC1Ev

tried it several times every time it does this

**Comment by traversaro** [comment]
On which OS are you experiencing this? If Debian/Ubuntu, which version?

**Comment by mike-talmage** [comment]
ubuntu 16.04

**Comment by Nicogene** [comment]
Did you forget to do `make install` after compiling?

**Comment by mike-talmage** [comment]
no every thing works did make install and it went perfect

**Comment by mike-talmage** [comment]
no errors or warnings

**Comment by mike-talmage** [comment]
using yarp 2.3.70

**Comment by mike-talmage** [comment]
if I have to go up its going to be hard my iot only compiles this version

what can I do

**Comment by PeterBowman** [comment]
What is the output of `ldd /usr/local/lib/yarp/yarp_opencv.so | grep opencv`?

**Comment by drdanz** [comment]
This is something related to your configuration, YARP does not compile if one of the symbols is missing.
Please try again with a clean build...

**Comment by Nicogene** [comment]
@mike-talmage any news?
The problem is solved? Shall we close it?

**Comment by Nicogene** [comment]
Closing for now, @mike-talmage  feel free to reopen it.
