### ISSUE TITLE
Consider moving away from github

### ISSUE THREAD

**Issue by nico202** [robotology/yarp#1732]
GitHub has never been free software. But [now](https://blog.github.com/2018-06-04-github-microsoft/) [microsoft](https://blogs.microsoft.com/?p=52553832) is buying it.

The biggest problem is about privacy and security, since micro$oft will have our logins. Then there's the possibility for them to censor specific repositories to their likes.

YARP is free GPL'd software, it deserves a good place to live in, I'd propose moving away from GitHub. I, personally, am going to delete my account in the near future, and I hope others will do the same

Thanks, Nicolò

**Comment by recruit-jp** [comment]
We just completed the migration from github to bitbucket.  Run for your life.
