### ISSUE TITLE
IJoypadEventDriven deprecated

### ISSUE THREAD

**Issue by mebbaid** [robotology/yarp#1747]
**Describe the bug**
When clean building yarp, and invoking `IJoypadController` from a walking module the following error apears:
```
In file included from /usr/local/src/robot/yarp/build/src/libYARP_conf/include/yarp/conf/api.h:13:0,
                 from /usr/local/src/robot/yarp/src/libYARP_OS/include/yarp/os/api.h:13,
                 from /usr/local/src/robot/yarp/src/libYARP_OS/include/yarp/os/LogStream.h:16,
                 from /usr/local/src/robot/element_capture-point-walking/code/cpp/Joypad_module/src/main.cpp:10:
/usr/local/src/robot/yarp/src/libYARP_dev/include/yarp/dev/IJoypadController.h:257:33: error: expected unqualified-id before ‘[’ token
     explicit IJoypadEventDriven(YARP_DEPRECATED_MSG("Use IJoypadEventDriven(double)") int rate);
                                 ^
/usr/local/src/robot/yarp/src/libYARP_dev/include/yarp/dev/IJoypadController.h:257:33: error: expected ‘)’ before ‘[’ token
Joypad_module/CMakeFiles/WalkingJoypadModule.dir/build.make:62: recipe for target 'Joypad_module/CMakeFiles/WalkingJoypadModule.dir/src/main.cpp.o' failed
make[2]: *** [Joypad_module/CMakeFiles/WalkingJoypadModule.dir/src/main.cpp.o] Error 1
```
However if i remove the `YARP_DEPRECATED_MSG` from the corresponding file and build yarp again, and then re-build my walking module, the error doesn't appear.

**To Reproduce**
* You have to have the `element_capture-point-walking` module, precisely the `virtualizer/CVirt` Fork/branch. or any code that uses that class.
* Build the source code and you will get the error.

**Configuration (please complete the following information):**
 - OS: ubuntu
 - yarp version: latest devel 3.0.0
-  compiler: gcc 5.4.0

@aerydna

**Comment by Nicogene** [comment]
@drdanz the placement of `YARP_DEPRECATED_MSG` seems give problems.

**Comment by traversaro** [comment]
I guess to reproduce it is sufficient to compile any example that includes `yarp/dev/IJoypadController.h` using C++14 .

**Comment by drdanz** [comment]
Probably we need yet another macro... something like `YARP_DEPRECATED_CONSTRUCTOR`?

**Comment by jeljaik** [comment]
Same problem here for our project. We will just get rid of it manually. It doesn't appear when compiling with clang.
