### ISSUE TITLE
Negative VOCAB in Image.h

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1749]
As noticed by @jgvictores (https://github.com/robotology/yarp/commit/185a9c36334860c5f655cf25b3766a7c680cf215#r29116913) there is a negative `VOCAB` in Image.h

https://github.com/robotology/yarp/blob/185a9c36334860c5f655cf25b3766a7c680cf215/src/libYARP_sig/include/yarp/sig/Image.h#L63-L65

@aerydna is this wanted or just a typo?

**Comment by Nicogene** [comment]
I checked and it is there since `yarp 2.3.65` :scream: 
But I think it was a typo.
@barbalberto what do you think about?

**Comment by barbalberto** [comment]
Negative pixelsize were allowed for "custom weird types", but negative `VOCAB` does not make sense to me.
I agree, probably that's a typo.

**Comment by jgvictores** [comment]
Yes, it seems it was introduced way back at 0a193e5... only issue here is that the fix definitely breaks b/w compat.
