### ISSUE TITLE
[RFModule] several instances in the same process

### ISSUE THREAD

**Issue by stephane-lallee** [robotology/yarp#175]
It appears that there is a limitation on the RFModule class that forbids to run more than one instance of them in a single process.
This limitation is coming from the catching of CTRL-C signal.

I would like to have a RFModule composed of other RFModule as threads. What would be the effect of this CTRL-C limit on such a system ?

**Comment by pattacini** [comment]
It's a message warning the user that somehow there's still the attempt to create more than one single instance of `RFModule`.
