### ISSUE TITLE
cmake fails when no yarp_devices are selected

### ISSUE THREAD

**Issue by arrenglover** [robotology/yarp#1758]
**Describe the bug**
cmake fails when no "yarpmod" devices are selected
Error:

`` CMake Error at src/devices/CMakeLists.txt:93 (list):``                                                           
``list sub-command REMOVE_DUPLICATES requires list to be present.``

**To Reproduce**
pull the latest master
mkdir build && cd build
ccmake ..
set "OFF" to all devices with the prefix "ENABLE_yarpmod"
configure

**Expected behavior**
Cmake should still work without yarp devices    

**Configuration (please complete the following information):**
 - OS: ubuntu 16.04
 - yarp version: 3.0.0 (3.0.0+13-20180615.9+gitf23f86b) 
 - CMake: 3.5.1
-  compiler: GNU 5.4.0

**Additional context**
Google result here: https://cmake.org/pipermail/cmake/2009-January/026581.html
seems that it can be fixed by changing how the list variable is referenced.

**Comment by Nicogene** [comment]
Thanks for reporting, it should be fixed by #1759
