### ISSUE TITLE
Import USBCamera from iCub

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1803]

**Comment by barbalberto** [comment]
Just a side note:
usbCamera device has a dependency from opencv and has some optional flags specific for iCub's event driven camera.

**Comment by drdanz** [comment]
> usbCamera device has a dependency from opencv and has some optional flags specific for iCub's event driven camera.

@barbalberto Thanks for pointing that out... The OpenCV dependency is not a big deal, since we already have opencv dependencies in YARP, but I will pay particular attention to the event driven-related stuff when I perform the migration

**Comment by Nicogene** [comment]
Once we import it we should expand the `usbcamera` with `macOS` and `win32` implementations:

- `macOS` : see https://github.com/ktossell/libuvc
- `win32` :  see https://github.com/ktossell/libuvc or something else if someone that uses windows knows a better library for handling usb devices (cc @randaz81, @pattacini )

**Comment by drdanz** [comment]
Fixed by #1995
