### ISSUE TITLE
Using GazeEvent callback in Python

### ISSUE THREAD

**Issue by ddetommaso** [robotology/yarp#1824]
**Describe the bug**
I am trying to use the event callback for the IGazeControl class but without success. Whenever I call the method registerEvent I got the following error:

TypeError: in method 'IGazeControl_registerEvent', argument 2 of type 'yarp::dev::GazeEvent &'

**To Reproduce**

> import yarp
> 
> class GazeMotionDone(yarp.GazeEvent):
> 
>     def __init__(self):
>         pass
> 
>     def gazeEventCallback(self):
>         pass
> 
> class GazeController:
> 
>     def __init__(self):
>         self.iGaze = None
>         props = yarp.Property()
>         props.put("device","gazecontrollerclient")
>         props.put("local","/gaze_client")
>         props.put("remote","/iKinGazeCtrl")
>         self.driver = yarp.PolyDriver()
>         self.driver.open(props)
>         self.iGaze = self.driver.viewIGazeControl()
>         a = GazeMotionDone()
>         self.iGaze.registerEvent(a)

**Expected behavior**
I would expect that GazeMotionDone class is derived from yarp.GazeEvent

**Configuration (please complete the following information):**
 - OS: Ubuntu 16.04
 - yarp version: 2.3.72
-  compiler: gcc 5.4.0

Please let me know if I am missing something.

**Comment by pattacini** [comment]
Issue moved to [robotology/QA #317](https://github.com/robotology/QA/issues/317) via [**ZenHub**](https://www.zenhub.com/)
