### ISSUE TITLE
Implementation of a RPC helper for Yarp Module.

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp#184]
During the development of a controller we usually come up with the requirement of setting its parameters through the .ini file and later through the RPC port. This task is time consuming and error prone.

One way to automate this process is [the paramHelp project](https://github.com/robotology-playground/paramHelp)

After some discussions with @lornat75 @drdanz @traversaro we think this facility can be improved and integrated in Yarp.

I now write here the summary of the discussion we had today, together with a sketch of the architecture of the library and the issues remained open.

We would like to use `thrift` to generate automatically getters and setters for the module.
In the `thrift` file we can specify a new statement of this kind (name, and syntax can be changed of course)

```cpp
property __type__ __name__ (__attribute_list__)
```
This statement will generate automatically a pair of getter and setter with the following signature:
```cpp
virtual const __type__& get__Name__();
virtual void set__Name__(const __type__&);
 //using camel case for the method names, with first letter lowercase
```
The real advantage of the autogeneration is that the two methods are not simply stubs to be implemented, but already implemented methods.
I would like to list now the three use cases that guided our design:

* the user does nothing a part from writing the `thrift` file. All the communication through RPC is handled by the utility. When the user needs to use a parameter, he simply invoke the relative getter and he will use the most recent value for the parameter.
* the user wants to be notified when a value changes so that he can update its behaviour, e.g. some gains in the controller. (This use case is motivated by the fact that we think the communication logic should stay in the module, or at least, separate from the controller logic)
* the user implements the setter and/or the getter to perform some functionality he can't perform with the callback.

Some more details on the implementation.

Requirements on the object type:

* The type specified should have a default constructor, so to easily allocate the storage variable, and be assignable (or copy contructable).

Discussion about the callback process.
There is one callback per parameter, and not a global one, which would force the user to implement a long switch in it.
@lornat75  suggested the creation of two callbacks: one before the actual set (e.g. `willSet__Name__`), and one after the set (e.g. `didSet__Name__`).
I also suggested the addition of a validation method. It can be implemented with the following method:
```cpp
bool validate__Name__(const __type__& newValue);
```
which by default return `true`, but can be overloaded by the user.
The actual implementation of the callback mechanism can be done with interfaces, or function pointers.

Attribute list:
At this point we thought about the following possible attributes:

* atomic/nonatomic: the implementation uses (or does not use) a mutex to access the variable
* readonly: only the getter will be generated
* storage=__name__: explicitly specify the name for the backing variable (otherwise a default one is given, e.g. a_name, or something else).
* nostorage: no backing variables are used: the setter and getter are pure virtual functions and they must be implemented by the user.
* vector: specify that the type is a vector type. If thrift is able to detect this, we can avoid this property. 

Last notes on the vector type.

We must be able to support vector types (as they are very common).
This opens another feature of the utility and one possible issue we must resolve.
If the object is a vector we would like to be able to set one particular object in the vector.
To do this, only if the type is a vector, the utility generates two other methods:
```cpp
virtual const __type__& get__Name__AtIndex(int index);
virtual void set__Name__AtIndex(const __type__&, index);
```
To be able to directly access an element in an array we could add another requirement: the type must implement the `operator()` (or `operator[]`).

The last issue, which is related to vector type, currently open is: how to specify the size for it, in order to perform a proper allocation and range checking during assignment and element retrieval?

**Comment by pattacini** [comment]
Seems `thrift` implementation addressed this issue.
Closing.
