### ISSUE TITLE
YARP_FORWARD_LOG_ENABLE=1 triggers an assertion failure on closure

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1851]
The environment variable YARP_FORWARD_LOG_ENABLE=1 allows to use yarp logs without yarprun.

On Linux everything is ok.

On Win32, all yarp modules crash on closure (assertion failure) and hangs-up (CTRL_C does not work, you need to  terminate the process from the task manager). The behavior is similar to the one reported in #492.

git bisect showed that the issue has been triggered by commit 9343869495d9.

To reproduce the issue, just set YARP_FORWARD_LOG_ENABLE=1 on a Win32 machine and type _yarpdev --list_

@Nicogene is currently investigating the issue, discovering that the issue could be triggered by a faulty behavior of method void yarp::os::BufferedPort::waitForWrite()

**Comment by Nicogene** [comment]
The thing that I noticed during my tests is that if inside the destructor of the `LogForwarder` I replace `waitForWrite()` with `yarp::os::Time::delay(0.1)` everything works fine.

It makes me think that something is not working in `waitForWrite` in windows, but I'm not sure I have to check it better.

This function is it tested in unit tests??
