### ISSUE TITLE
ovrheadset/TextureBattery.cpp doesn't compile because of getRate method

### ISSUE THREAD

**Issue by mebbaid** [robotology/yarp#1859]
**Describe the bug**
When updating to YARP 3.1, and compiling in windows the `TextureBattery.cpp` throws an undefined identifier error.

**To Reproduce**
Update to YARP 3.1 and enable the ovrheadset device on a windows machine.

**Expected behavior**
Changes to the respective `PeriodicThread` method fixes this issue.

**Screenshots**
![getrate error](https://user-images.githubusercontent.com/36491318/45555040-fe106700-b837-11e8-97ed-01589bde8630.JPG)

**Configuration (please complete the following information):**
 - OS: Windows 10
 - yarp version: 3.1
-  compiler: VisualStudio 2017

**Comment by traversaro** [comment]
>  Changes to the respective PeriodicThread method fixes this issue.

Great, can you submit a PR with this change? Thanks!
