### ISSUE TITLE
Doxygen documentation missing for yarp::dev::RGBDSensorParamParser

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1863]
`yarp::dev::RGBDSensorParamParser` was added in https://github.com/robotology/yarp/pull/1634 , but not documentation is present at all. It would be good to have at least a brief description of the class and what is its purpose.

**Comment by Nicogene** [comment]
I'm working on a new feature about generating pointcloud from depth images that required a big refactoring for the `yarp::dev::RGBDParamParser` and its structures.

I will open soon a PR including these new feature including the documentation that I actually forgot, my bad ! :sweat_smile:

**Comment by traversaro** [comment]
Great!

**Comment by Nicogene** [comment]
Closed via #1865
