### ISSUE TITLE
Refactor image horizontal concatenation logic 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1870]
**Is your feature request related to a problem? Please describe.**
Combining two images as one single image in which the images are horizontally concatenated is  a technique that is frequently used in YARP, for example to transmit two images in a synchronous way, as supported for example by the `grabberDual` device. However,  the code for horizontally concatenate is currently duplicated in two points of YARP, i.e. https://github.com/robotology/yarp/blob/f5e903f58cd4550504d6f6643e0bb3f91ece2ffe/src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp#L1001 and https://github.com/robotology/yarp/blob/3d550be4ea1f51f7903a88f2279eaa85948f44df/src/devices/realsense2/realsense2Driver.cpp#L1495 . Given that the code is far from intuitive (I am not sure I totally got it) and I will copy once more time now, [I guess](https://en.wikipedia.org/wiki/Rule_of_three_%28computer_programming%29) we should refactor it as a free function. 
Any opinion on the suitable header that should host this function?  

**Describe the solution you'd like**
Have that  a code in reusable function. 

**Describe alternatives you've considered**
Copy-paste the code.

**Comment by claudiofantacci** [comment]
I totally agree 😄 It can be very useful also for visualization purposes 👍 

cc @barbalberto @Nicogene

**Comment by Nicogene** [comment]
I agree, since it has not particular dependencies this code could be moved in `YARP_sig` as a sort of extension of `Image` functionalities.
Good catch, code duplication is evil :imp:

**Comment by Nicogene** [comment]
Fixed by #1880
