### ISSUE TITLE
Allow to specify a different name for the node name and the yarprun server name in the yarpmanager

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/yarp#1893]
The problem is that usually the computer's name is long and not easy to understand, like ``icub@iiticublap123``. This does not hold for the ``yarprun`` server name, which can be called simply ``icub29``. Usually to overcome this problem we have either to change the machine name or to add a host in ``/etc/hosts``. This can clash with internal IT policies, while it may be not ideal to modify a system file. 

Wouldn't it to be possible to specify also the IP address in the ``cluster-config.xml``, something like
```xml
<node display=":0.0" address="10.0.0.29">icub29</node>
```
or
```xml
<node display=":0.0" address="iiticublap123">icub29</node>
```
?

cc @Nicogene @mbrunettini @hu-yue @nunoguedelha @DanielePucci

**Comment by Nicogene** [comment]
Closed by #1894
