### ISSUE TITLE
Issue with Interrupting a port

### ISSUE THREAD

**Issue by ali-khalili** [robotology/yarp#190]
Hi

I want to use interrupt for two communicating ports. I have one writer thread which writes into a port and one reader thread which reads from a port (and off course they are synchronous as they are using not buffered port). After the reader stops, the writer becomes blocked and I suppose interrupting the writer port will make it unblocked where as in my code, IT SEEMS THAT the interrupt thread gets blocked itself.

As an example, code of writer:
```C++
void * Writer(void *)
{
     while(true)
     {
         yarp::os::Bottle bot;
         bot.addInt(0);
         writerPort.write(bot);
         yarp::os::Time::delay(1);
     }
}

void * Interruptor(void *)
{
    yarp::os::Time::delay(40);
    writerPort.interrupt();
   cout<<"the interrupt thread is done";
}

int main(int argc, char *argv[]) {
    yarp1=new Network();
    writerPort.open("/writerP");

    pthread_attr_t attr;
    pthread_t* instance =new pthread_t[1];
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
    pthread_create(instance, NULL, Writer, NULL );
    pthread_create(instance, NULL, Interruptor, NULL );

    pthread_attr_destroy(&attr);
    while(true);
}
```
and:
```C++
int main(int argc, char *argv[]) {
    finish=false;
    Network * yarp1; yarp1=new Network();
    cout<<"First, you should have started the writer!\n";
    readerPort.open("/readerP");
    yarp::os::Network::connect("/writerP","/readerP");
    while(true);
}

```
First executing the writer and then executing the reader (which doesn't do anything), the the interrupt thread starts but will never finish.

**Comment by pattacini** [comment]
We've lost focus on this long-standing issue.
Closing.
