### ISSUE TITLE
Wrong measurement unit for focal lenghts in realsense2 driver

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#1949]
See robotology/gazebo-yarp-plugins#407.

The `realsense2` driver should perform the conversion from pixel unit to mm.

**Comment by drdanz** [comment]
Fixed in #1960

**Comment by Nicogene** [comment]
Actually it is more a `wontfix` since in #1960 we decide to change the unit measure from mm to pixel, no changes are required to the `realsense2` device driver.
