### ISSUE TITLE
Units of camera parameters in `yarp::dev::IRgbVisualParams`

### ISSUE THREAD

**Issue by jchevrie** [robotology/yarp#1956]
See https://github.com/robotology/gazebo-yarp-plugins/issues/407.

In short, the current interface `yarp::dev::IRgbVisualParams` specifies that the parameters `focalLengthX` and `focalLengthY` should be expressed in millimeters.
More specifically in this function https://github.com/robotology/yarp/blob/47e8ae58889789465b15d90f85e1863aeab4c2c5/src/libYARP_dev/include/yarp/dev/IVisualParams.h#L155
This does not seem really useful in practice and values in pixels should be preferred.

Also the `realsense2` driver already returns these values in pixels, which is currently considered as a bug (see https://github.com/robotology/yarp/issues/1949).

The best would be to change the unit of these two fields from mm to pixels in the interface and the documentation, and to add one parameter expressed in meters to still keep the physical focal length in the list (named `nominalFocalLength` for example).

Before I try to fix this, are you aware of any camera driver implementation that would be broken by such a change?

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/yarp/pull/1960  ?
