### ISSUE TITLE
Make yarp::sig::Vector movable

### ISSUE THREAD

**Issue by valegagge** [robotology/yarp#1965]
I think the Vector class should be movable, that is modernize it by writing move constructor and a move assignment operator.

**Comment by barbalberto** [comment]
I'd suggest to implement also iterators and `begin()` `end()` functionalities, so that we could use `yarp vectors` within std algorithms.

**Comment by Nicogene** [comment]
Already done here: #1908 😎

**Comment by valegagge** [comment]
Hi @Nicogene,

if i'm not wrong the movable costructor and operator= are not implemented. 
I think there is a good reason for this. Could you explain to me?

thanks!!

**Comment by Nicogene** [comment]
Sorry I badly explained myself, #1908 implements `begin()` and `end()`.
#1974 instead implements the move constructor and operator. Unfortunately there are some memory leaks that I didn't find out how to fix it.
