### ISSUE TITLE
fromCvMat in camcalib produce segFault

### ISSUE THREAD

**Issue by gonzalezJohnas** [robotology/yarp#1979]
This bug has been found and solve with the help of  Andrea Ruzzenenti (@aerydna) 

**Describe the bug**
When running `camCalib` from `icub-main` and more specifically  in the `PinholeCalibTool::apply` function produce a null image after `fromCvMat<PixelRgb>` resulting in a segfault.

We found that the issue is in reality in  `libYARP_sig/src/Image.cpp` for the function `Image& Image::operator=(Image&& other)`.

**To Reproduce**
Connect `camCalib` module to `yarpdev` (`grabberDual`)

**Expected behavior**
The image returned from `fromCvMat<PixelRgb>` after applying the calibration with remap is not valid so accessing is pixel produce a segfault.

**Configuration :**
 - OS: Ubuntu 18.04
 - yarp version: 3.0 branch `devel`
-  compiler: gcc, g++ version 7.3.0

**Temporary fix**
The actual bug happen in the `libYARP_sig/src/Image.cpp` : 
```c++
Image& Image::operator=(Image&& other) {
    Image moved(std::move(other));
    std::swap(moved.implementation, implementation);
    synchronize();
    return *this;
}
```
When performing the swap if *moved.implementation* is not set to `nullptr`, the Image destructor is called on *moved*  destroying also the implementation of the current object (this).

A way to fix it is to explicitly set `moved.implementation` to `nullptr` before the synchronize or before the `swap`.

For more details you can contact me or Andrea Ruzzenenti (@aerydna)

**Comment by drdanz** [comment]
Thanks for reporting this.
It's fixed in `devel` now.

**Comment by Nicogene** [comment]
The move operators were correct, the commit that add `nullptr` has been reverted since it introduced memory leak.

The bug was in `camCalib`, it has been fixed by https://github.com/robotology/icub-main/pull/572
