### ISSUE TITLE
#2000

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2000]
:champagne:

**Comment by drdanz** [comment]
See also #1000

**Comment by aerydna** [comment]
Time Flies.. sniff..

**Comment by lornat75** [comment]
roughly 3 issues/day without counting the closed ones...?

**Comment by drdanz** [comment]
Hmm, that sounds too much, 1000 issues / 2 years and 4 months is a bit more than 1 issue/day...
Anyway, I think we were struggling to stay around 100 open issues at the time, this means that, even if the open bug count increased, we closed about 850 issues in this period, I think it's a good result.

**Comment by PeterBowman** [comment]
Let me point this out: 400 issues and 600 PRs, more or less :).
