### ISSUE TITLE
Deprecate Chicken Scheme and Allegro Common Lisp support

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#2018]
The recently release SWIG 4 ( https://sourceforge.net/p/swig/news/2019/04/swig-400-released/ ) dropped support for Chicken, that is explicitly supported in YARP build system. I guess this means that we should start deprecating the YARP-Chicken bindings.

**Comment by drdanz** [comment]
+1 From me, probably the same should be done for allegrocl since it was removed as well.

**Comment by Nicogene** [comment]
+1 also for for me, we should support the languages actually used, I'm pretty sure that the bindings of `chicken`, `allegro` and `tcl` are used by nobody.

**Comment by drdanz** [comment]
I opened #2019, that just removes both languages, without actually deprecating them, I don't think it is worth to waste time on them...

**Comment by traversaro** [comment]
If somebody actually complains we can always add them back easily for a proper deprecation cycle. : D

**Comment by drdanz** [comment]
> +1 also for for me, we should support the languages actually used, I'm pretty sure that the bindings of chicken, allegro and tcl are used by nobody.

TCL bindings might be unused, but at least they are tested on travis :wink:

**Comment by Nicogene** [comment]
Closed by #2019
