### ISSUE TITLE
Several interface headers doesn't include what they use

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#2020]
Here is the list of interfaces that doesn't include `yarp/os/Vocab.h` but they use it:
- [ ] `IPositionDirect.h`
- [ ] `IVelocityControl.h`
- [ ] `IRGBDSensor.h`
- [ ] `IControlCalibration.h`
- [ ] `IAxisInfo.h`
- [ ] `IAmplifierControl.h`
- [ ] `FrameGrabberInterfaces.h`

**Comment by PeterBowman** [comment]
Might be already solved in devel thanks to https://github.com/robotology/yarp/pull/2006, see https://github.com/robotology/yarp/commit/864c3f851d36ad28b5d5dded442ef857477ffcb6#diff-fbcecfd8df1807946df81405a4ab316a.

**Comment by Nicogene** [comment]
> Might be already solved in devel thanks to #2006, see e.g. 864c3f8#diff-fbcecfd8df1807946df81405a4ab316a.

:+1: 

I opened it for people like me that have a robot on `master` and maybe are experiencing this issue. Closing after the release.
