### ISSUE TITLE
.ini files (plugins description file) generated in build/src are problematic

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#2025]
When starting a visual studio debug session, this path is used as `current directory`, so the plugin description file is found by resource finder, hiding files with the same contained in the context.

**Comment by drdanz** [comment]
Fixed by a676e8d60bcc6b416eba9ba5af56022f8a6157fd

**Comment by drdanz** [comment]
@randaz81 obviously you will have to remove the old .ini files.
