### ISSUE TITLE
imuBoschBNO055 has wrong conversion formulas for gyro and magnetometer

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#2038]
In the `imuBoschBNO055` [implementation](https://github.com/robotology/yarp/blob/master/src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp) there are these conversion formulas:
```c++
        // Fill in accel values
        data_tmp[3] = (double)raw_data[0] / 100.0;
        data_tmp[4] = (double)raw_data[1] / 100.0;
        data_tmp[5] = (double)raw_data[2] / 100.0;


        // Fill in Gyro values
        data_tmp[6] = (double)raw_data[6] / 100.0;
        data_tmp[7] = (double)raw_data[7] / 100.0;
        data_tmp[8] = (double)raw_data[8] / 100.0;

        // Fill in Magnetometer values
        data_tmp[9]  = (double)raw_data[3] / 100.0;
        data_tmp[10] = (double)raw_data[4] / 100.0;
        data_tmp[11] = (double)raw_data[5] / 100.0;
```
Looking in the Bosch documentation the unit measure are for **gyro**:
![image](https://user-images.githubusercontent.com/19152494/58949608-23aa1b80-878d-11e9-8de6-73b20ca10ef6.png)

and for **magnetometer**:
![image](https://user-images.githubusercontent.com/19152494/58949664-40465380-878d-11e9-955a-6d90afef144f.png)

Then it seems that the values have to be divided by 16.0 instead 100.0.

I ran a simple test moving the joint 0 of the head up to 20 deg @ 20 deg/s recording the gyro

# BEFORE (using 100 as scaling factor)
![image](https://user-images.githubusercontent.com/19152494/58945028-52bb8f80-8783-11e9-8c35-803ac76d9aef.png)
# AFTER (using 16 as scaling factor)
![image](https://user-images.githubusercontent.com/19152494/58948035-8e595800-8789-11e9-9d79-ffd9387c7c69.png)

**Comment by traversaro** [comment]
How do you know that the `AFTER` plot is correct?

**Comment by traversaro** [comment]
cc @prashanthr05 @nunoguedelha

**Comment by traversaro** [comment]
**This bug affects all the iCub robots containing an `imuBosch_BNO055`. In particular, the gyro and magnetometer data contained in `/icub/inertial` have been always not correct, for all YARP/icub-main releases.** 
The problem does not affect  older iCub that use an XSens IMU.

**Comment by Nicogene** [comment]
Another confirmation using the `iKinGazeCtrl`:
# BEFORE
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/19152494/57684046-45542f00-7635-11e9-85c2-40ffb8b8ade8.gif)

# AFTER 
![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/19152494/58950549-59500400-878f-11e9-9dd2-94778f384bf6.gif)

**Comment by traversaro** [comment]
There are a few issue that could be actually caused by this: 
* https://github.com/robotology/icub-support/issues?utf8=%E2%9C%93&q=iKinGazeCtrl
