### ISSUE TITLE
Current YARP devel (future YARP 3.2) does not correctly install with CMake 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#2048]
**Describe the bug**
If you configure and install the latest YARP devel, the following error is printed during installation:
~~~
-- Installing: /usr/local/share/yarp/cmake/ycm-0.10.4/3rdparty/FindQCustomPlot.cmake
CMake Error at extern/ycm/cmake_install.cmake:79 (file):
  file INSTALL cannot find
  "/home/travis/build/robotology/idyntree/yarp/extern/ycm/ycm-0.10.4/cmake-3.8/Modules/CMakeParseArguments.cmake".
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)
~~~

**To Reproduce**
Configure and install the current YARP devel on a Xenial system, without using an external YCM installation

**Expected behavior**
The installation should be successful, or if CMake 3.5 is not supported this should be properly annotated using the `cmake_minimum_required` CMake function.

**Screenshots**
See the output in https://travis-ci.org/robotology/idyntree/jobs/543704445#L6438 .

**Configuration (please complete the following information):**
 - OS: Ubuntu Xenial
 - yarp version: https://github.com/robotology/yarp/commit/cf4db200471b4a58151f502013d1e9e4d07722bf

**Comment by drdanz** [comment]
Should be fixed now, please reopen if the issue persists.

CC @PeterBowman
