### ISSUE TITLE
yarpdataplayer timestamps not consistent

### ISSUE THREAD

**Issue by lrapetti** [robotology/yarp#2049]
**Describe the bug**
The same dataset dumped with `yarpdatadumper` played multiple time seems to be played with different timing, and in particular this time seems to be related with the computational work that the machine is doing. 

**Expected behavior**
I would expect to be able to replay offline the same dataset with the real/same timestamp.

**Screenshots**
In particular I'm running [this dataset](https://drive.google.com/open?id=1Kvy-zZQpdnBeixCQFzh8lFQ2oTDvCDnV) , and the data are meant to be read from a consumer device ([human state provider](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/HumanStateProvider)).
As you can see from the data, they were collected with both tx and rx time, so I have tried to play the data using one or the other, but the same behaviour seems to be present.
From the following screenshots you can see the different duration of the same dataset by checking the `Time Taken` coloumn in the `yarpdataplayer` interface (the same duration was double-checked with a clock):
- `yarpdataplayer --withExtraTimeCol 1`
  - just playing the data
    ![Screen Shot 2019-06-10 at 16 54 34](https://user-images.githubusercontent.com/35487806/59204713-7cb8eb80-8ba1-11e9-8536-7996fc1b4738.png)
  - data + consumer device
    ![Screen Shot 2019-06-10 at 16 57 42](https://user-images.githubusercontent.com/35487806/59204654-5eeb8680-8ba1-11e9-887b-d11e953b8016.png)
- `yarpdataplayer --withExtraTimeCol 2`
  - just playing the data
    ![Screen Shot 2019-06-10 at 16 58 58](https://user-images.githubusercontent.com/35487806/59204737-8b070780-8ba1-11e9-8bae-b108e0f20c40.png)
  - data + consumer device
    ![Screen Shot 2019-06-10 at 17 00 18](https://user-images.githubusercontent.com/35487806/59204742-922e1580-8ba1-11e9-986c-2fc187ae8763.png).

**Configuration:**
 - OS: `MacOS 10.13.6`
 - yarp version: `3.1.1+10-20190514.4+git96bad8480`

@kouroshD

**Comment by DanielePucci** [comment]
@drdanz @Nicogene may probably help us with this?

**Comment by Nicogene** [comment]
It seems a clock drifting, I will give a look to this. 👍 
But maybe @vtikha , that is the author of `yarpdataplayer`, has some hints about what should be the problem here.

**Comment by vtikha** [comment]
@Nicogene Yes, I had a f2f talk with @vvasco and I have started to look at it. It only happens with rxTime and not txTIme.

**Comment by Nicogene** [comment]
Fixed by #2074
