### ISSUE TITLE
yarpmanager - cluster doesn't run /pc104 node

### ISSUE THREAD

**Issue by davidetome** [robotology/yarp#2070]
**Describe the bug**
running selected nodes in cluster tab they becomes green but in the application resource tab is in red.
If I run manually yarp run --server /pc104 it works

**Screenshots**
see attached screenshot
![Screenshot from 2019-08-01 11-05-19](https://user-images.githubusercontent.com/6638215/62283229-5e5cc700-b451-11e9-93cc-bd33be05be86.png)

**Comment by davidetome** [comment]
@pattacini @vtikha any suggestion? I should  fix it on the laptop of the iCubShenzen01 who's leaving the lab

cc @Fabrizio69

**Comment by Nicogene** [comment]
>  I should fix it on the laptop of the iCubShenzhen01 who's leaving the lab

When it should be sent?

if it is urgent I can come and see what's wrong late this evening(after 17.30) or next week.

**Comment by davidetome** [comment]
@Nicogene yes it's very urgent,  it should be sent yesterday!! 
if you come this late afternoon is ok; i can stay until 18.30/19.00.

**Comment by drdanz** [comment]
This issue was closed by @Nicogene, but was this fixed?

**Comment by davidetome** [comment]
yes, thanks to @Nicogene  who fixed&closed

**Comment by Nicogene** [comment]
> This issue was closed by @Nicogene, but was this fixed?

Yes fixed by 14946eb
