### ISSUE TITLE
Make YCM a hard dependency

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2078]
Handling YCM in YARP is complicated, and takes lots of time, YCM should just be a hard dependency

**Comment by drdanz** [comment]
icub-main now has a hard dependency on YCM, I think it is time to fix this...
Anyone against this? CC @pattacini, @traversaro, @vtikha, @randaz81, @Nicogene, @lornat75

**Comment by traversaro** [comment]
Ok for me!

**Comment by Nicogene** [comment]
In `icub-tech` repos is almost everywhere an hard dependency, so I completely agree :+1:

**Comment by drdanz** [comment]
Fixed by #2232
