### ISSUE TITLE
yarp::os::Property segfault

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#2084]
When using YARP::os::Property in a multi-thread environment,I get the following **segmentation fault:**

`#16 0x00007f7edcbff6ea in yarp::os::Property::operator= (this=0x7f7ecc00d2e0, rhs=...) at /yarp/src/libYARP_OS/src/Property.cpp:957`

originated by recent changes (probably commit 42dcf2b7).
 
Unfortunately, I'm able to reproduce it only while running a Docker container... :/

**Comment by drdanz** [comment]
Fixed by #2085
