### ISSUE TITLE
ControlBoardWrapper2 ROS topic

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#209]
Since some people uses both YARP and ROS, we tought to have the controlBoardWrapper2 optionally create a ROS topic along the usual yarp port.

I've done a first implementation of this and now it is able to create a topic publiching a sensor_msgs/JointState message which is one of the 'native' ROS messages documented here http://docs.ros.org/api/sensor_msgs/html/msg/JointState.html

I used a .msg file to generate the class that will be sent through the topic
The data sent are
- list of joint name (useless on yarp, but needed on ROS)
- vector of encoders
- vector os velocities
- vector of torques

For now the data is filled with dummy names and numbers just to see if it works as expected.

I pushed the code on a branch called ControlBoardWrapper2_NewOutputPort.
The CMake flag CBW2_USE_ROS_MSG has to be enabled in order to compile the needed code and generate this topic.

It has been tested with a simple subscriber create by following the tutorial on ROS webpage (http://wiki.ros.org/ROS/Tutorials/ExaminingPublisherSubscriber) so not using yarp code, btw yarp read is able to read the data back if the yarpidl_rosmsg service is running like explained in the page http://wiki.icub.org/yarpdoc/yarp_with_ros.html

TODO: 
- define exactly with type of ros message could be more useful to implement
- fix segfault while closing (it is still WIP ... )

**Comment by barbalberto** [comment]
ROS message is created with the following fields

name;
position;
velocity;
effort;

Where name is filled with "rosNameTest" plus joint number. How do we get the joint name? From config file I guess... 
Suggestion @arocchi @EnricoMingo? Should this name match the one in Gazebo? @traversaro

**Comment by traversaro** [comment]
In my opinion, we should get the name of the joint (Axis) from the [IAxisInfo]([http://wiki.icub.org/yarpdoc/classyarp_1_1dev_1_1IAxisInfo.html) interface. If this interface is not available, we should fallback to the current solution.

In this way we will continue to decouple the wrapper and the underlying device. 
For CanBusMotionControl and embObjMotorControl I propose we use the joint names that are present in http://wiki.icub.org/wiki/ICub_joints ( more discussions on this topic in https://github.com/robotology/icub-main/issues/57 ).

**Comment by barbalberto** [comment]
Pull request merged into master. 
Good point the IAxisInfo interface, I'll open a issue on that.
