### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/_yarp.so: undefined symbol: _ZNK4yarp3sig10VectorBase12getFormatStrEi

### ISSUE THREAD

**Issue by Urheen** [robotology/yarp#2095]
Dear all,
I follow the instructions for installing python bindings for yarp on http://wiki.icub.org/wiki/Python_bindings

Then when I open a python console, type import yarp, the error occurs. Does anyone can help me to solve this problem?

ImportError: /usr/local/lib/python2.7/dist-packages/_yarp.so: undefined symbol: _ZNK4yarp3sig10VectorBase12getFormatStrEi

**Comment by drdanz** [comment]
Sorry, for the very long delay... did you manage to solve this issue? This looks like a problem that can be solved by rebuilding yarp...
