### ISSUE TITLE
Typo in clusterWidget UI within yarpmanager

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp#2113]
**Describe the bug**
The title label of the Cluster widget within `yarpmanager` contains a typo, namely the text contains `Cluster Managerment Window` instead of `Cluster Management Window`

https://github.com/robotology/yarp/blob/e28da21babaace57aa55507fa8c291459a113737/src/yarpmanager/src-manager/clusterWidget.ui#L71

**Configuration:**
 - yarp version: latest devel

**Comment by drdanz** [comment]
Thanks for catching this! Are you brave enough to try and make a pull request?

**Comment by Nicogene** [comment]
Fixed by #2114
