### ISSUE TITLE
yarpdatadumper produces files with name that are not allowed on exfat partitions

### ISSUE THREAD

**Issue by bemilio** [robotology/yarp#2116]
**Describe the bug**
The LaCie 4TB d2 Professional hard drives that we have do not allow to copy folders that contain :o or :i at the end of the name. They are formatted with `exfat` filesystem. This conflicts with the names that are usually given to the yarp device ports and it renders more difficult to copy dumped datasets (since the folders are created with the ports names)

**To Reproduce**
Copy a dump of the robot data into one of the LaCie hard drives in the lab

**Expected behavior**
A correct copy

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - yarp version:  3.2.1
-  compiler: g++

**Comment by traversaro** [comment]
>  Copy a dump of the robot data into one of the LaCie hard drives in the lab

Which lab? : )

**Comment by bemilio** [comment]
> Which lab? : )

The best lab :D 
DIC lab at CRIS building, IIT Genova

**Comment by drdanz** [comment]
By `logger` you mean `yarpdatadumper`?

**Comment by bemilio** [comment]
> By `logger` you mean `yarpdatadumper`?

yes

**Comment by drdanz** [comment]
@bemilio If I understand correctly, the issue is that the `:` character is not allowed on exfat partition file names?

**Comment by drdanz** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/ExFAT)


> Allowed characters in filenames | all Unicode characters except U+0000 (NUL) through U+001F (US) / (slash) \ (backslash) : (colon) * (asterisk) ? (question mark) " (quote) < (less than) > (greater than) and \| (pipe)(encoding in UTF-16LE)

**Comment by bemilio** [comment]
> @bemilio If I understand correctly, the issue is that the `:` character is not allowed on exfat partition file names?

Exactly

**Comment by drdanz** [comment]
Thanks.
For the dumping part, it should be a trivial issue to rename the files, but this might require also some extra work for the dataplayer side since, i believe, the port name is taken from the file name.
CC @vtikha

**Comment by pattacini** [comment]
The port name is also reported plain within `info.log` as stated in the documentation: http://www.yarp.it/yarpdatadumper.html.

Don't know if `yarpdataplayer` reads that info though.

**Comment by vtikha** [comment]
the ```yarpdataplayer``` get initialized with the the ```info.log``` file

**Comment by pattacini** [comment]
I'm on it.

**Comment by pattacini** [comment]
PR created (see #2122).

Anyway, `yarpdatadumper` can rely on the `--dir` command-line option to override dir names.

**Comment by pattacini** [comment]
Done in #2122.
