### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by davidetome** [robotology/yarp#2128]
just cloned on a clean VM (pop_os - ubuntu 19.10), on master branch. See picture below
![Screenshot from 2019-11-28 12-03-30](https://user-images.githubusercontent.com/6638215/69802862-d312f880-11da-11ea-9855-7dbbd77bf971.png)

cc @mbrunettini

**Comment by traversaro** [comment]
Hi @davidetome, the issue has been already reported in https://github.com/robotology/yarp/issues/2125 . There you can also find a possible solution/workaround in https://github.com/robotology/yarp/issues/2125#issuecomment-556036924 , if you could test it it would be great (I do not have any Ubuntu 19.10 to quickly test the problem).

**Comment by traversaro** [comment]
If it is ok for you, I would close this issue as a duplicate of https://github.com/robotology/yarp/issues/2125 .

**Comment by davidetome** [comment]
> Hi @davidetome, the issue has been already reported in #2125 . There you can also find a possible solution/workaround in [#2125 (comment)](https://github.com/robotology/yarp/issues/2125#issuecomment-556036924) , if you could test it it would be great (I do not have any Ubuntu 19.10 to quickly test the problem).

added **if statement** at line 276; i get the following:

![Screenshot from 2019-11-28 14-21-05](https://user-images.githubusercontent.com/6638215/69809906-fd6cb200-11ea-11ea-8720-e5aa97ed1051.png)
