### ISSUE TITLE
[yarpdataplayer] Provide status flag to check if player has finished playing a loaded dataset

### ISSUE THREAD

**Issue by prashanthr05** [robotology/yarp#2140]
**Is your feature request related to a problem? Please describe.**

When trying to control the yarpdataplayer through a CPP application using the RPC commands,  there is no possibility to check if a single run of an entire loaded dataset has completed, while using the *play* command. 

The application prints the following line to the console while the seek bar reaches the end,
*asking utils to stop thread*.

Additionally, it would be helpful if yarpdataplayer exposed flags like *isStopped*, *isStoppedAtTheEnd*, *isRunning*, etc.

**Describe the solution you'd like**

A desirable solution could be adding thrift-based functions to check the status flags through the same RPC interface, while internally updating the required status flags hidden from the user.

**Describe alternatives you've considered**

An alternative that I've considered so far is to use the RPC command *step* and advance until a boolean false is returned. However, I have not fully understood the implications this might have on the sampling periods of multi-rate sensors datasets.

**Comment by drdanz** [comment]
Fixed by #2442
