### ISSUE TITLE
yarp v3.2.1 - fails to compile on a clean installation of ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by davidetome** [robotology/yarp#2149]
server installed using, as usual,  the @mbrunettini 's script (https://git.robotology.eu/MBrunettini/icub-scripts/blob/master/provision_icub_machine.sh)  

![Screenshot from 2019-12-10 08-19-08](https://user-images.githubusercontent.com/6638215/70504393-fd8f7a80-1b25-11ea-9282-089702c8c281.png)

cc @pattacini @Fabrizio69

**Comment by pattacini** [comment]
Closing as it was most likely a glitch.
BTW, we're now using `YARP-3.3.0`.
