### ISSUE TITLE
iCub bindings errors?

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/yarp#2156]
http://wiki.icub.org/wiki/Python_bindings
iCub bindings
iCub bindings are located in $ICUB_ROOT/main/bindings. Pick a build directory, run cmake, enable CREATE_PYTHON and compile.

> mkdir build 
> cmake ../

CREAT_PYTHON set to ON

> make 

![Screenshot from 2019-12-18 20-23-37](https://user-images.githubusercontent.com/55526431/71082492-89636f80-21d4-11ea-9a75-106dc1451d67.png)

**Comment by drdanz** [comment]
Which YARP version are you using?

**Comment by YANGGANG1971** [comment]
Yarp version 3.2.1

**Comment by YANGGANG1971** [comment]
I fixed it. Due to the cmake version.
