### ISSUE TITLE
Bindings version of Python?

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/yarp#2160]
By default, the python version is Python2. 
But, the instructions blow suggest Python3.x? So how to change the bindings version of Python?
http://www.icub.org/software_documentation/icub_python_imaging.html

**Comment by drdanz** [comment]
Just pass the `-DYARP_USE_PYTHON_VERSION=3` option to CMake

**Comment by drdanz** [comment]
Closing, please reopen if this doesn't work for you.
