### ISSUE TITLE
problem with comunication tcp/ip

### ISSUE THREAD

**Issue by szewc12** [robotology/yarp#2165]
When I send messages in MATLAB to a YARP port:

```matlab
clc;
clear all;
close all;

% Configuration and connection
t = tcpip('191.161.8.101',10002);

% Open socket and wait before sending data
fopen(t);
pause(0.2);

% Send data every 500ms
for i=0:10    
    DataToSend=[i;i]
    fwrite(t,DataToSend);
    pause (0.5);
end

% Close and delete connection
fclose(t);
delete(t);
```

I stumble upon this error:

```sh
yarp: Could not find carrier for a connection starting with: 0 0 1 1 2 2 3 3 [........]
```

**Comment by pattacini** [comment]
Hi @szewc12 

If you aim to explore the use of the **MATLAB Instrument Control Toolbox** together with YARP, you could have a look at the tutorial I made available on this topic here: https://github.com/pattacini/yarp2IC.

It's 4 years old and thus I didn't run it for quite long but it should contain some helpful hints.
