### ISSUE TITLE
yarpdatadumper --type video not working

### ISSUE THREAD

**Issue by alessiav** [robotology/yarp#2193]
I tried to dump a video from a webcam with:
`yarpdev --device grabber --subdevice usbCamera --d /dev/video0`
`yarpdatadumper --name /webcam --type video`
`yarp connect /grabber /webcam`

but it did not work (the dumper saves just data.log and info.log files), while everything goes fine with --type image or --type image_jpg (so the dumper correctly saves all the images as well).

We debugged it and it seems the segfault is at line 153 of main.cpp of datadumper:
`const cv::Mat &getImage()`

**Comment by pattacini** [comment]
Hi @alessiav 

Thanks for reporting 👍 

PR #2194 addresses this.
