### ISSUE TITLE
How to communicate for BufferedPort<Bottle>, port<Bottle> between python and c++

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/yarp#2225]
I read the Python Tutorials 
http://www.icub.org/software_documentation/icub_tutorials.html 

This tutorial taught me how to use python to receive the image from Yarp (C++) and send the image to Yarp (C++).  It is very great. 

But, if I just send and receive the type of BufferedPort<Bottle>, port<Bottle>, how should I do?
Do you have any tutorial or guide for me?

Thanks for your patient interpretation each time.

**Comment by jgvictores** [comment]
Hi!

There's a great introduction on classes related to `Port` and `Bottle` at: http://www.yarp.it/port_expert.html

The corresponding C++ source code is at: https://github.com/robotology/yarp/tree/master/example/port_power ([perma](https://github.com/robotology/yarp/tree/b31820e287b86e8daaed8f20c73f03a5f2111b01/example/port_power))

Any C++ example can seamlessly connect to its Python counterpart and vice-versa.

Python examples are currently not abundant, but here you have an example with a `BufferedPortBottle` (pythonic equivalent to C++ `BufferedPort<Bottle>`) that implements a write loop: https://github.com/robotology/yarp/blob/master/bindings/python/examples/example.py ([perma](https://github.com/robotology/yarp/blob/b31820e287b86e8daaed8f20c73f03a5f2111b01/bindings/python/examples/example.py))

Please inform if there is any other YARP example code with which you would need help in translation from C++ to Python!
