### ISSUE TITLE
CopyPortable is unable to convert from float64 to float32

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#2227]
It'is not easy to explain this problem.

Please give a look to the following gist.
https://gist.github.com/randaz81/9526161b3ffc71cf872d556da881a34c

The example compiles and runs successfully. But if you try to read data from port `/port6432` you'll notice that values are corrupted.

This bug may affect the correct handling of all ROS messages that use float32 datatype, e.g. Laserscan.

**Comment by drdanz** [comment]
Thanks for the test. I'm on it

**Comment by drdanz** [comment]
Fixed by 841852272a283fd65b02980d4f4cc215ee52bc25

**Comment by drdanz** [comment]
Unfortunately we found out a series of related issues... I'm trying to understand them exactly...
