### ISSUE TITLE
Using logger: compile warning

### ISSUE THREAD

**Issue by triccyx** [robotology/yarp#2243]
**Describe the bug**
Using yDebug() the warning appears:
```bash
format not a string literal and no format arguments
```
**To Reproduce**
```c++
std::string test{"Test"};
yDebug(test.c_str());
```
**Expected behavior**
The warning should not appear

**Screenshots**

**Configuration (please complete the following information):**
 - Ubuntu 19.10
 - yarp version: YARP version 3.3.103+20200317.2+git9d6a196c7
-  compiler:g ++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

**Additional context**
Minor

**Comment by drdanz** [comment]
This is not a bug, it is the same that you would get when using printf(). Printing a string in this way is unsafe. The warning is actually avoiding a potential security issue.

The correct syntax is
```c++
yDebug("%s", test.c_str());
```

or you can use:

```c++
yDebug() << test;
```
