### ISSUE TITLE
Refactoring in progress: all lidar devices will derive from Lidar2DDeviceBase

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#2280]
This issue keeps track of several PRs which have the common goal to make all lidar devices deriving from yarp class `Lidar2DDeviceBase`. This will allow to remove duplicate (and sometimes bugged/inconsistent) code in the configuration parser and limits checker.

The following components, belonging to different repos, need to be tested:

**yarp base class:**
- [x] Lidar2DDeviceBase https://github.com/robotology/yarp/pull/2205

**yarp virtual sensors:**
- [x] fakeLaser https://github.com/robotology/yarp/pull/2205 
- [x] laserFromDepth https://github.com/robotology/yarp/pull/2205
- [x] laserFromExternalPort https://github.com/robotology/yarp/pull/2205
- [x] laserFromPointCloud https://github.com/robotology/yarp/pull/2205

**yarp physical sensors:**
- [ ] laserHokuyo
- [ ] rpLidar (osbolete)
- [x] rpLidar2 https://github.com/robotology/yarp/pull/2281

**cer:**
- [x] cerDoubleLidar https://github.com/robotology/cer/pull/117
   - [x] R1 configuration files depending on  cerDoubleLidar (cer->moved to robots-configuration) https://github.com/robotology/robots-configuration/pull/183

**gazebo-yarp-plugins:**
- [x] laserSensor https://github.com/robotology/gazebo-yarp-plugins/pull/488
- [x] doublelaser (only minodr modifications) https://github.com/robotology/gazebo-yarp-plugins/pull/488
   - [x] R1 configuration files depending on  laserSensor (cer-sim) https://github.com/robotology/cer-sim/pull/21

**Comment by drdanz** [comment]
@randaz81 Is this task still in progress or can we close this issue?

**Comment by randaz81** [comment]
Task is now complete
