### ISSUE TITLE
Next Yarp Release 

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#2286]
As mentioned in:
* https://github.com/robotology/gazebo-yarp-plugins/pull/488
* https://github.com/robotology/yarp/issues/2280

it is important to release Yarp 3.4 before August 2020  to avoid incompatibilities with the upcoming release of gazebo-yarp-plugins

**Comment by Nicogene** [comment]
Blocking issue : https://github.com/robotology/yarp/issues/2279

**Comment by drdanz** [comment]
YARP release schedule is independent by iCub, if YARP is not ready, you will have to base your release on YARP 3.3 branch
