### ISSUE TITLE
segmentation fault on using yarpcar_h264  

### ISSUE THREAD

**Issue by ddetommaso** [robotology/yarp#2289]
**Describe the bug**
The yarpcar_h264 plugin seems not working properly.

**To Reproduce**
Following instructions at [url](https://www.yarp.it/carrier_h264_howto.html)
I got segmentation fault typing the following command:

`yarp connect /gst /yarpview/img:i h264`

I checked and both the gstreamer server and client work correctly.

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04/20.04
 - yarp version: v3.3.2

**Comment by ddetommaso** [comment]
Hi guys,

in case you still couldn't fixed this or reproduced the issue, can you post here a version of YARP that works with yarpcar_h264  ?

Thanks

**Comment by Nicogene** [comment]
@valegagge is the main author of that carrier and unfortunately she will be not available for months. 
I have no experience with that carrier maybe some other @robotology/yarp-developers with more experience can handle this issue.

Sorry for the troubles

**Comment by randaz81** [comment]
`h264 `carrier replaced by `gstreamer `carrier: https://github.com/robotology/yarp/pull/3127. See updated documentation.
