### ISSUE TITLE
os/Stamp should be using a fixed size type for counter

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2365]
The `yarp::os::Stamp` class uses `int` to represent the counter.
Since `int` has a different representation depending on the system, it should be using a fixed size type, for example `int32_t`.

Also it should probably use an unsigned type, i.e. `uint32_t`

**Comment by drdanz** [comment]
cc @Nicogene @traversaro

**Comment by pattacini** [comment]
@drdanz there are conditions where a negative counter (specifically `-1`) is employed to mean "invalid" or "not-available".

**Comment by Nicogene** [comment]
> @drdanz there are conditions where a negative counter (specifically -1) is employed to mean "invalid" or "not-available".

Exactly, if the Stamp is not defined it has -1 has seq number and 0.0 has ts, changing it would be a break of ABI

**Comment by drdanz** [comment]
Technically, if only `-1` is used, it could be possible to use `uint32_t` and define

```
getMaxCount() == std::numeric_limits<uint32_t>::max() - 1;
```

since `-1` has the exact representation as `std::numeric_limits<uint32_t>`

(btw `getMaxCount` should be `constexpr`)

**Comment by pattacini** [comment]
>since -1 has the exact representation as std::numeric_limits<uint32_t>

Yeah, but then how this relates to checks like this below:

https://github.com/robotology/yarp/blob/71097ed9b24369d2709dc37298120130cc5c4868/src/libYARP_os/src/yarp/os/Stamp.cpp#L41-L44

If `sequenceNumber` is unsigned, then we need to change the check.
I'm afraid that similar checks might be spread around.

**Comment by drdanz** [comment]
This was fixed in `yarp::os::Header` which will gradually replace `yarp::os::Stamp`. There is no longer need to change it in Stamp as well.
