### ISSUE TITLE
Move realsense2 YARP devices to a separate standalone repository.

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2371]
The realsense2 device depends on the `realsense2` library that is not available by default in debian/ubuntu.
In order to simplify the installation using binary packages, we should move this device in a separate repository.

**Comment by drdanz** [comment]
I imported the realsense2 device here:
https://github.com/robotology/yarp-device-realsense2

There are probably still a couple of things to fix, but the code is officially there, and the `src/devices/realsense2` in YARP is therefore frozen.
Also the documentation in [`doc/subdevice_realsense.md`](https://github.com/robotology/yarp/blob/303a8f5dea8ea214e343772f8b97f9dacb7b082f/doc/subdevice_realsense.md), should probably be moved in the new repository (cc @aikolina)

I will remove it from YARP as soon as I am sure that it works properly.

**Comment by xEnVrE** [comment]
> I will remove it from YARP as soon as I am sure that it works properly.

Fyi, I tested the new repository and everything seems ok. I tested with a D415 only.

![realsense](https://user-images.githubusercontent.com/6014499/95360399-99ffe600-08cb-11eb-9483-de2ac26e412c.png)

**Comment by drdanz** [comment]
Thanks @xEnVrE for testing!

**Comment by PeterBowman** [comment]
Also successfully tested with a D435i (*realsense2* device), YARP 3.4.1, RealSense SDK 2.39.0.

**Comment by drdanz** [comment]
Thanks @PeterBowman 
I think we are ready to remove the driver from master then...

**Comment by drdanz** [comment]
>  Also the documentation in [`doc/subdevice_realsense.md`](https://github.com/robotology/yarp/blob/303a8f5dea8ea214e343772f8b97f9dacb7b082f/doc/subdevice_realsense.md), should probably be moved in the new repository

We should still figure out what to do with this documentation page, since if we move it out of YARP it will no longer be generated, but it doesn't make sense to leave it there, since the device is no longer there.
Perhaps we can convert it to markdown, and adapt it to be the `README.md` file in the new repository?

**Comment by traversaro** [comment]
For small repos, a well written README is definitely the most accessible and maintainable form of documentation.

**Comment by drdanz** [comment]
Done, updated the PR
