### ISSUE TITLE
ACE used on appveyor old (6.3.4)

### ISSUE THREAD

**Issue by jwillemsen** [robotology/yarp#2378]
**Describe the bug**

The ACE version used on the appveyor CI is old, it is 6.3.4 which is from 2016, see https://github.com/DOCGroup/ACE_TAO/releases/tag/ACE%2BTAO-6_3_4. It was formally never tested for Visual Studio 2017 and 2019.

Would recommend to upgrade ACE on appveyor, maybe use the conda or vcpkg packaged version as alternative?

See https://github.com/robotology/yarp/blob/f8773835064a25848010a934d9366711a0fc305c/.appveyor.yml#L58

**Comment by drdanz** [comment]
Fixed in fbc3bbd1e2f969b4bd2f45a21e23605961d5f3aa (now using ACE 6.5.6)

**Comment by jwillemsen** [comment]
FYI, with github actions there is build in support for vcpkg caching, we are using that for ACE, see https://github.com/DOCGroup/ACE_TAO/blob/643377c9a6a544c7fde64a56aff3c31c55bb8813/.github/workflows/windows.yml#L99.
