### ISSUE TITLE
Access to timestamp not protected with mutex

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2396]
I think that this write access to the `time` variable should be protected using the `timeMutex` which, from my understanding, is there just to protect this variable.

https://github.com/robotology/yarp/blob/a64b8f96ab1957c3fa7ec298eebc718886877834/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L894

This might cause some invalid timestamp or similar random issues.

Can anyone who knows the code check if I'm right? Perhaps @randaz81 or @traversaro?

**Comment by drdanz** [comment]
https://github.com/robotology/yarp/blob/a64b8f96ab1957c3fa7ec298eebc718886877834/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L4330-L4335

**Comment by drdanz** [comment]
https://github.com/robotology/yarp/blob/a64b8f96ab1957c3fa7ec298eebc718886877834/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L935

**Comment by drdanz** [comment]
https://github.com/robotology/yarp/blob/a64b8f96ab1957c3fa7ec298eebc718886877834/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L943

https://github.com/robotology/yarp/blob/a64b8f96ab1957c3fa7ec298eebc718886877834/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L964

**Comment by traversaro** [comment]
I agree, the unprotected access of time is a bug.
