### ISSUE TITLE
yarpdataplayer closes immediately after loading data with --hidden flag is used

### ISSUE THREAD

**Issue by arrenglover** [robotology/yarp#2401]
**Describe the bug**
immediately after loading data in the `yarpdataplayer` when the `--hidden` flag is used, the `yarpdataplayer` closes. The data is successfully loaded, but then the application exits.

**To Reproduce**
each command in a separate terminal:
```
yarpserver --write
yarpdataplayer --hidden
echo "load /home/aglover/data/attention/exp1/" | yarp rpc /yarpdataplayer/rpc:i
```

![image](https://user-images.githubusercontent.com/9265237/98376720-2ecd3f00-2044-11eb-80ce-cae71ce29d69.png)

**Expected behavior**
using the same steps, but using `yarpdataplayer` without the `--hidden` flag successfully loads the data and the application stays open. I would expect the `--hidden` version to also stay open.

**Configuration (please complete the following information):**
 - OS: Windows 10 19042 + ubuntu 20.04 on WSL2
 - yarp version: 3.4.1
-  compiler:

-- CMake: 3.16.3 (/usr/bin/cmake)
-- C Compiler: GNU 9.3.0 (/usr/bin/cc)
-- CXX Compiler: GNU 9.3.0 (/usr/bin/c++)

**Comment by vtikha** [comment]
This has been resolved in the full refactoring as discussedi in #2400 . The PR can be found here done: [here](https://github.com/robotology/yarp/pull/2442)
cc @arrenglover
