### ISSUE TITLE
Support yarp::sig::VectorOf<int> in Python

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp#2411]
**Is your feature request related to a problem? Please describe.**

I would like to use `yarp::sig::VectorOf<int>` in Python. It seems that [yarp.i](https://github.com/robotology/yarp/blob/master/bindings/yarp.i) is missing the specialization of `yarp::sig::VectorOf` for integers.

**Additional context**

I tried to replicate all the recipes already implemented in `yarp.i` to support the `yarp::sig::VectorOf<double>` and I was able to make it work (I only tested in Python though). The changes are in [this commit](https://github.com/xEnVrE/yarp/commit/fd3a09b10a1088fada06b4accd4db8382729540a). However, I am not sure whether all these changes are required and sound.

Is it ok if I open a PR?

**Comment by xEnVrE** [comment]
cc @drdanz @diegoferigo

**Comment by traversaro** [comment]
> However, I am not sure whether all these changes are required and sound.

Assessing that is exactly the point of opening a PR, so I would say go forward and let's see the changes in a PR, thanks (even if probably given the state of the CI @drdanz could have other ideas).

**Comment by drdanz** [comment]
The CI using github actions is *almost* working, feel free to open the PR, I will eventually test it locally, or delay it for a couple of days in order to test it properly... Thanks!
