### ISSUE TITLE
about the use of 'localhost' in gyarpmanager

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#244]
it seems that if the .xml of an application specifies that  module will run 'localhost', this module will always run on localhost, no matter if you (later) edit the text box in the GUI. This seems true both in gyarpamanger-gtk and gyarpmanager-qt. Is there a special reason for this misleading behavior?

**Comment by apaikan** [comment]
It seems this issue has been fixed over the time. Basically there were two confusing issues: 

- When a module assigned to run on localhost within the xml file, it cannot be changed via GUI. Now it has been made clear by coloring the localhost in gray (Thanks to @alecive) 

- A module which is not running on the localhost cannot be attached to the gui stdout window. This has also been cleared by using different color.
