### ISSUE TITLE
Replace XmlRpcCpp with the one available on Debian

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2460]
The xmlrpcpp library is available on debian (`libxmlrpcpp-dev`), we have a customized version in the `extern/xmlrpcpp` folder.
AFAIK the changes are just for
 * Building on windows
 * Move the library in a namespace to avoid conflicts

This library is used only for the xmlrpc carrier.

We should:

- [ ] Investigate if the "official" library works on windows now.
- [ ] Find out if it is available on Windows and distributed with some package manager (vcpkg, conda)
- [ ] Check if we have some special bugfix, and eventually propose them upstream
- [ ] Port the xmlrpc carrier to the "official" library.

**Comment by randaz81** [comment]
xmlrpc is going to be removed in the upcoming yarp releases, so I'm closing this issue
