### ISSUE TITLE
Unable to launch YARP network with yarp@master on Windows

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#2536]
**Describe the bug**
❌I'm unable to launch the YARP network using `yarp@master` on Windows.
✔Everything works as expected with `yarp@v3.4.3`.

**To Reproduce**
- `yarpserver` --> seems starting ok ✔
- `yarp where` --> no detection of the server ❌
- `yarp detect` --> server correctly detected ✔

**Expected behavior**
`yarp where` shall detect the server properly.

**Configuration (please complete the following information):**
 - OS: Windows 10 Pro 20H2 19042.870
 - yarp version: current `master`, which is now at https://github.com/robotology/yarp/tree/302898628b30fb87d51b74c3809f162f940c0c4d.
-  compiler:
  Microsoft Visual Studio Enterprise 2019
  Version 16.9.2
  VisualStudio.16.Release/16.9.2+31112.23
  Microsoft .NET Framework
  Version 4.8.04084
  Installed Version: Enterprise
  Visual C++ 2019   00434-00052-67056-AA269
  Microsoft Visual C++ 2019

**Additional context**

Interestingly enough, I'm getting the following error message while issuing `yarp conf [IP] [port]` correctly:
```console
Configuration file:
  C:\Users\upattacini\AppData\Roaming\yarp\config\_ugo.conf
[ERROR] is not valid!
[ERROR] Expected:
[ERROR]   yarp conf [ip address] [port number]
[ERROR]   yarp conf [ip address] [port number] [yarp|ros]
[ERROR] For example:
[ERROR]   yarp conf 192.168.0.1 10000
```
No error message shows up w/ `yarp@v3.4.3` instead.

**Comment by pattacini** [comment]
cc @traversaro

**Comment by traversaro** [comment]
I double checked in my Windows machine with conda, and 3.4.3 works fine:
~~~
conda create -n yarp2536
conda activate yarp2536
conda install -c conda-forge -c robotology yarp
~~~
and this is the output with `yarp conf`
~~~
(yarptest)
STraversaro@IITICUBLAP102 MINGW64 ~
$ yarp conf 0.0.0.0 1234
Configuration file:
  C:\Users\STraversaro\AppData\Roaming\yarp\config\yarp.conf
Stored:
  host 192.168.1.200 port number 10000 (yarp name server)
Now stores:
  host 0.0.0.0 port number 1234 (yarp name server)
(yarptest)
~~~

**Comment by drdanz** [comment]
There was a regression in `yarp conf` that I fixed a couple of minutes ago in master, please check now and let me know if that was fixed, or if you are having some other issue with multicast detection or similar...

**Comment by pattacini** [comment]
Tested it right now and it's working correctly.
Thanks 👍🏻
