### ISSUE TITLE
yarp connect error

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#258]
we recently see a strange error. When we try to connect 2 buffered ports. The port in initialized with just the name and no other parameters for what I can see.

The context is the following: there are many different modules connecting togheter, and we found out that one particular module (called attentionPrioritizer) is failing when connecting TO other 2 modules.

yarp connect output is

yarp connect /attPrioritiser/icub/cmd:o /gazeArbiter/icub/cmd:i 
Failure: Cannot connect to 0.516828:/tcp://gazeArbiter/icub/cmd:i
icub@icub14:/usr/local/src/robot/attention (master)$ yarp connect /attPrioritiser/icub/cmd:o /gazeArbiter/icub/cmd:i 
Failure: Cannot connect to 0.516828:/tcp://gazeArbiter/icub/cmd:i
icub@icub14:/usr/local/src/robot/attention (master)$ yarp connect /attPrioritiser/icub/cmd:o /gazeArbiter/icub/cmd:i 
Failure: Cannot connect to 0.000000:/tcp://gazeArbiter/icub/cmd:i
icub@icub14:/usr/local/src/robot/attention (master)$ yarp connect /attPrioritiser/icub/cmd:o /gazeArbiter/icub/cmd:i 
Failure: Cannot connect to 0.963911:/tcp://gazeArbiter/icub/cmd:i
icub@icub14:/usr/local/src/robot/attention (master)$ yarp connect /attPrioritiser/icub/cmd:o /gazeArbiter/icub/cmd:i 

The number before :/tcp changes from time to time, it is not a fixed number.

The yarp server output is;
* query "/attPrioritiser/icub/cmd:o"
 * query "/gazeArbiter/icub/cmd:i"
 * query "tcp://gazeArbiter/icub/cmd:i"
-> announce "/gazeArbiter/icub/cmd:i" 0
 * query "/attPrioritiser/icub/database:o"
 * query "/workingMemory"
 * query "tcp://workingMemory"
-> announce "/workingMemory" 0
 * query "/attPrioritiser/icub/database:o"
 * query "/workingMemory"
 * query "tcp://workingMemory"
-> announce "/workingMemory" 0
 * query "/attPrioritiser/icub/database:o"
 * query "/workingMemory"
 * query "tcp://workingMemory"
-> announce "/workingMemory" 0

There is this additional query for tcp://port and announce that I do not understand

The attPrioritiser module, give this error:  
Note: those messages comes from different runs so the number / port names in this case does nor match, but when an error appears, the number listed here as carrier is the same preponed to yarpserver error message.

yarp: No .ini file found for plugin: 0.936999
yarp: Failed to find library (null) with carrier 0.936999
yarp: Could not find carrier "0.936999"
yarp: Removing output from /attPrioritiser/icub/protoObject:o to 
/blobFinder/icub/left_cam
yarp: No .ini file found for plugin: 0.936999
yarp: Failed to find library (null) with carrier 0.936999
yarp: Could not find carrier "0.936999"
yarp: No .ini file found for plugin: 0.936999
yarp: Failed to find library (null) with carrier 0.936999
yarp: Could not find carrier "0.936999"
yarp: Removing output from /attPrioritiser/icub/highLoop:o to 
/attPrioritiser/icub/cmd:i
yarp: Removing input from /attPrioritiser/icub/highLoop:o to 
/attPrioritiser/icub/cmd:i
yarp: No .ini file found for plugin: 0.936999
yarp: Failed to find library (null) with carrier 0.936999
yarp: Could not find carrier "0.936999"
yarp: Removing output from /attPrioritiser/icub/direct:o to /iKinGazeCtrl/mono:

In the module receiving the connection somtime we see the message
[debug]broken index but I don' t know if it is related or not.

**Comment by paulfitz** [comment]
Any update on this? I propose closing.

**Comment by barbalberto** [comment]
We tested again yesterday and the problem didn't show up anymore. (We didn't changes the user code).
I dig into the PortCore and now the cmd.get(2) (the one that was returning the strange numbers) now correctly returns an empty string and therefore the code is able to connect again.
Maybe some changes in the meantime fixed this problem...
I'll close it, should it happen again we have this trace to look for. 
Thanks for your support @paulfitz
