### ISSUE TITLE
[legal] libYARP_math is released as LGPL but it should be GPL

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#266]
[GSL](https://www.gnu.org/software/gsl/) is licensed as GPL. This means that the YARP_math library [should be released as GPL](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL).

All the other components that optionally use the YARP_math library (priority_carrier, logger, manager) and all the iCub modules that use the YARP_math library should probably be GPL.

Finally, since linking the init library is linking to the math library, it should be GSL, and therefore almost _everything_ in YARP and iCub should be GPL

**Comment by drdanz** [comment]
I think that to simplify everything we should just have a CMake switch to choose YARP license between ``GPL`` and ``LGPL``, instead of switches like ``CREATE_LIB_MATH`` that do not expose this issue.

* If ``GPL`` is selected, CMake will search for GSL and Readline and will create ``libYARP_math`` and the tools will be built with readline support if the libraries are available. Binary releases are released as ``GPL``. Using/redistributing files taken from such a release require a ``GPL`` compatible license. 
* If ``LGPL`` is selected, then ``libYARP_math`` will not be generated and all tools will be created without readline support. Binary releases (if any) are ``LGPL`` and therefore can be linked/redistributed, etc. with proprietary stuff.

It would be nice to have a dual-licensed release (i.e. if you use ``YARP_math`` you are forced to be compatible with ``GPL`` otherwise if you use other YARP libraries you can use any license compatible with ``LGPL``), but unfortunately I don't think is possible... for example ``libYARP_OS`` optionally uses ``Readline``, therefore if you distribute this version, the library is ``GPL``. Moreover there are the ``libYARP_init`` issues. Therefore I believe that the only solution is to distribute 2 different installers.

About file licensing (from what I understand from the GPL license and the [GPL FAQs](https://www.gnu.org/licenses/gpl-faq.html)):

* Files that cannot be built without ``GPL`` must be ``GPL``.
* Files that don't use any ``GPL`` library can be ``LGPL``.
* I don't know about files that can optionally use some ``GPL`` library, but I *think* that
```c++
#ifdef WITH_READLINE
  // This part must be released under the ``GPL``
#else
  // This part could technically be released under the ``LGPL``
#endif
```
Therefore I believe that these files could be dual-licensed, adding some extra comment to the header.

**Comment by lornat75** [comment]
We can clearly print in cmake a warning about the type of license and change the license on the binary distributions. Distributing two different versions of the binaries is too complicated.

Do we have alternatives for readline?

For GSL I think we should consider changing the implementation using eigen.

**Comment by paulfitz** [comment]
On the readline issue, we could easily move its use out of `YARP_OS` and into the `yarp` program where it belongs. The current organization makes no sense.

**Comment by paulfitz** [comment]
big +1 for a GPL/LGPL flag in cmake

**Comment by drdanz** [comment]
Would it be legal, in order to release just one binary that can be both GPL and LGPL, if we opened readline using `dlopen` and eventually use it?

**Comment by drdanz** [comment]
@lornat75 Yet another serious licensing issue. I found out that yarpview-qt uses [QCustomPlot](http://www.qcustomplot.com), that is GPL, this means that the yarpscope-qt plugin should be GPL, but instead it is LGPLv2.1

I don't know if the executable that loads the plugin is supposed to be GPL as well or not, but I think it is.

An option for the future could be to switch to [Qt Charts](http://doc.qt.io/QtCharts/) or [Qt Data Visualization](http://doc.qt.io/QtDataVisualization/index.html) that according to [this announcement](http://blog.qt.io/blog/2016/01/13/new-agreement-with-the-kde-free-qt-foundation/) by Lars Knoll are going to be released as LGPL starting with Qt 5.7, but it will be a long time before all our supported releases will include it...

**Comment by lornat75** [comment]
what about yarpscope-qt?

**Comment by lornat75** [comment]
In any case, these are executables they can have GPL license. What matters more is the libraries. I think we have to change the license on the binaries and add a flag in cmake as suggested above by Paul.

**Comment by drdanz** [comment]
> what about yarpscope-qt?

I'm not sure... it opens a plugin that is (supposed to be) GPL through a QML file (that I have no idea about the license that is supposed to have) that is handled by a library that is LGPL (Qt5).

I have no idea but my opinion is that it something like this:

```
       ?              LGPL          ?                   (GPL)                  GPL
       |               |            |                     |                     |
yarpscope-qt   ----   Qt5   ---- QML File   ----  QtYARPScopePlugin  ----  QCustomPlot
           \-main only----------/
```

I think this is a borderline case, see [GPL faqs](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#GPLAndPlugins).

**Comment by drdanz** [comment]
#896 and #892 were merged, I think the big issues are now solved, but we still need to check and fix all the headers of all the files, and we need to remove the CREATE_LIB_MATH_USING_GSL flag and get rid of GSL completely from YARP_math

**Comment by traversaro** [comment]
IANAL, but I think this issue is already solved if `CREATE_LIB_MATH_USING_GSL` is set to OFF.

**Comment by drdanz** [comment]
GSL is no longer used or linked anywhere in YARP, except for the `YARP_gsl` compatibility library.
I think we can close this now.
