### ISSUE TITLE
Use `mkdir_p` in lieu of `mkdir` within `getHomeContextPath`

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#2676]
**Describe the bug**
Unable to automatically create the path to `getHomeContextPath` when calling that function.

Have a look at:
https://github.com/robotology/yarp/blob/0c5873cdf02a6cb4bea0d375049399dd0f556a90/src/libYARP_os/src/yarp/os/ResourceFinder.cpp#L686-L694

Because of

https://github.com/robotology/yarp/blob/0c5873cdf02a6cb4bea0d375049399dd0f556a90/doc/release/v3_5_0.md#L127-L129

I think that the function `yarpdatahome` no longer creates the desired path and we use the fallback `mkdir`.
However, the correct function for creating the directory should be `mkdir_p` instead.

**To Reproduce**

This [snippet](https://github.com/robotology/icub-main/blob/master/src/tools/depth2kin/src/module.cpp#L1182-L1188) should work out also in case the dir `~/.local/share/yarp/contexts` is not available.

Anyway, I discovered that in one of the latest YARP versions the path doesn't get created. 

**Expected behavior**
When calling `getHomeContextPath`, we should be able then to open a file therein.

**Configuration (please complete the following information):**
 - OS: Linux
 - yarp version: `3.4.101~dev`

**Comment by pattacini** [comment]
cc @traversaro

**Comment by drdanz** [comment]
Fixed in #2678
