### ISSUE TITLE
[Manager] Missing icons

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#268]
<a href="https://github.com/drdanz"><img src="https://avatars.githubusercontent.com/u/1100056?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [drdanz](https://github.com/drdanz)**
_Monday Feb 24, 2014 at 13:58 GMT_
_Originally opened as https://github.com/robotology-legacy/qtyarp/issues/2_

----

The following icons are missing:
- Open File
- Help
- New
- Save
- Save As
- Quit
- Export Graph
- About
- Load Application (context menu)
- Reopen (context menu)
- Remove (context menu)
- Attach to stdout (context menu)
- Connect (context menu)
- Disconnect (context menu)

**Comment by alecive** [comment]
The manager now has new icons in scalable `.svg` format. Moreover, I added a central folder in `yarp` (called `yarpgui-icons`) in which every yarp gui can draw from.
