### ISSUE TITLE
Window menus do not open at the first click

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#282]
<a href="https://github.com/lornat75"><img src="https://avatars.githubusercontent.com/u/1403333?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lornat75](https://github.com/lornat75)**
_Friday Apr 11, 2014 at 12:10 GMT_
_Originally opened as https://github.com/robotology-legacy/qtyarp/issues/16_

----

I noticed the following problem with the menu.

If I click on the window bar on top and then on the menu, I need to click two times. The first time nothing happens, the second time the menu opens correctly. I can then change item in the menu.

This is a problem that happens also in the qtgyarpmanager so it is intrinsic to the menus in the applications.

**Comment by alecive** [comment]
We (me and @aitek4iit ) cannot reproduce the bug either. @lornat75 is this still open or can we close it?

**Comment by drdanz** [comment]
It works for me now, and it's probably an issue in the qt5 version that you were using.
Closing this.
