### ISSUE TITLE
yarpmotorgui set custom positions of only certain parts of the robot

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/yarp#2839]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

We use `yarpmotorgui` to set the robot joints to custom positions. But sometimes we are interested in setting the custom positions only to some parts. We update the `.ini` file such that only the desired parts are included. `yarpmotorgui` then throws error messages (see screenshot), with the number of parts not included. However, it still does the function as expected.

**Describe the solution you'd like**

It would be nice to set the custom positions without the error messages.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/45564317/166215150-76326299-cd44-43f8-8a34-6699f3b88cfc.png)

**Comment by HosameldinMohamed** [comment]
CC @gabrielenava @FabioBergonti @Giulero @affafjunaidMOMIN @antonellopaolino @traversaro

**Comment by elandini84** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
> 
> We use `yarpmotorgui` to set the robot joints to custom positions. But sometimes we are interested in setting the custom positions only to some parts. We update the `.ini` file such that only the desired parts are included. `yarpmotorgui` then throws error messages (see screenshot), with the number of parts not included. However, it still does the function as expected.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> It would be nice to set the custom positions without the error messages.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> ![image](https://user-images.githubusercontent.com/45564317/166215150-76326299-cd44-43f8-8a34-6699f3b88cfc.png)

This PR should fix the issue: [2853](https://github.com/robotology/yarp/pull/2853)

**Comment by HosameldinMohamed** [comment]
Thanks @elandini84
