### ISSUE TITLE
Doxy online documentation is out of date

### ISSUE THREAD

**Issue by mbrunettini** [robotology/yarp#2848]
**Describe the bug**
the [Online Documentation ](https://www.yarp.it/latest/) is stopped at version 3.5.1

The website is updated daily using by updating repository [yarp-documentation](https://github.com/robotology/yarp-documentation.git) and branch called `yarp_it_pages` and itrs last update was on [on 31 Dec 2021](https://github.com/robotology/yarp-documentation/commit/a9a43a8e1cab5b907b8017f1203641a1a6f55be2) 

I suspect some GH Action is broken

**Expected behavior**
the GH action updates the above branch

**Comment by randaz81** [comment]
fixed
