### ISSUE TITLE
`IMURosPublisher` publishes rpy data in wrong format

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#2892]
**Describe the bug**
The imu msg represents the orientation as a quaternion (see [here](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/Imu.html)) `IMURosPublisher` publishes the data  seems to publish it as rpy:

https://github.com/robotology/yarp/blob/f03dd5d71a78db86486dd006d8855af993874b9a/src/devices/multipleAnalogSensorsRosPublishers/IMURosPublisher.cpp#L64-L66

**To Reproduce**

**Expected behavior**
The orientation is published as quaternion

**Screenshots**

**Configuration (please complete the following information):**
 - OS: WSL2 - Windows 11
 - yarp version: `3.7.2+1-20220630.8+gitc8450ac9e`
-  compiler:

**Additional context**

cc @traversaro @randaz81 @elandini84

**Comment by traversaro** [comment]
Another related piece of code: https://github.com/robotology/yarp/blob/f03dd5d71a78db86486dd006d8855af993874b9a/src/devices/multipleAnalogSensorsRosPublishers/PoseStampedRosPublisher.cpp#L53 .

**Comment by randaz81** [comment]
Fixed as suggested by @traversaro
