### ISSUE TITLE
Add the possibility to specify the window title of a yarpview

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp#2894]
**Is your feature request related to a problem? Please describe.**

Sometimes it is useful to give a title to the window of a `yarpview` that is different from the input port name.
Hence, I am opening this issue to ask for this feature request.

**Describe the solution you'd like**

An additional CLI option of the `yarpview` executable, such that it is possible to specify the window name. E.g.

```console
yarpview --title <the_title>
```

**Comment by xEnVrE** [comment]
cc @randaz81

**Comment by elandini84** [comment]
@xEnVrE this PR should cover your request: [#2900](https://github.com/robotology/yarp/pull/2900)
