### ISSUE TITLE
Cannot run the yarpserver from the Cluster Management Window of yarpmanager

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp#2896]
**Describe the bug**
I cannot run the `yarpserver` from the `Cluster Management Window` of the `yarpmanager`.

![image](https://user-images.githubusercontent.com/6014499/203022713-90c3b91b-cdcf-4167-a9a8-774ca333b521.png)

Whenever I try to press the green button, I get the following in the terminal when I run the `yarpmanager`:

```console
[ERROR] ClusterWidget: yarpserver is not running
```

**To Reproduce**

Run the `yarpmanager` and try to run the `yarpserver` from the  `Cluster Management Window` of the `yarpmanager`.

**Expected behavior**

The `yarpserver` starts after pressing on the green button of the  `Cluster Management Window` of the `yarpmanager`.

**Configuration (please complete the following information):**
 - OS: `Ubuntu 20.04` (running inside Docker)
 - yarp version: `YARP version 3.7.2`
-  compiler: `g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`

**Additional context**

I am running the latest distro that has been installed using the `robotology-superbuild`. `git status` executed within the superbuild folder reads
```console
HEAD detached at v2022.09.1
```

**Comment by xEnVrE** [comment]
I also tested with the latest yarp `YARP version 3.7.2+92-20221116.5+git90cbb8697` and I got the same result.

**Comment by randaz81** [comment]
Not sure about this issue, it could be also setup-dependent.
Can you check if you ssh iiticublap202 and verify also if xenvre is a valid username (and its permissions)?

**Comment by xEnVrE** [comment]
Hi @randaz81, it was a connectivity issue, such that the ssh connection was not working properly.

Closing then.
