### ISSUE TITLE
sender rate

### ISSUE THREAD

**Issue by laurafbec** [robotology/yarp#2910]
Hi everyone
I'm starting testing YARP and I would like to know if is there a way in the simple_sender example, to establish the sent messages rate.
I tried to use RateThread class but it seems to be out in the last version.
Thanks in advance

**Comment by randaz81** [comment]
The correct class to use is yarp::os::PeriodicThread, https://yarp.it/latest/classyarp_1_1os_1_1PeriodicThread.html
