### ISSUE TITLE
yarpmotorgui - add Select/Deselect all parts Button

### ISSUE THREAD

**Issue by davidetome** [robotology/yarp#2914]
It could be nice to have a button to select/deselect all parts of the robot in the `yarpmotorgui`

@randaz81 , I can work on this today and open a PR when done.

cc @pattacini

**Comment by davidetome** [comment]
Ciao @randaz81 ,

 I've opened a PR for this : 

- https://github.com/robotology/yarp/pull/2915

cc @pattacini

**Comment by pattacini** [comment]
Hi @davidetome 

A couple of points:
- Probably, the CI complains about these [empty lines](https://github.com/robotology/yarp/pull/2915/files#diff-6be8b80defb22a8c45022fde9535305d1c65ff748365d6ab40982df8497de32cR12-R13).
- We would need to address this [comment](https://github.com/robotology/yarp/pull/2915#issuecomment-1359462838) as well.
