### ISSUE TITLE
There is confusion on what you can do with localhost and with a normal node (through yarprun).

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#297]
<a href="https://github.com/lornat75"><img src="https://avatars.githubusercontent.com/u/1403333?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lornat75](https://github.com/lornat75)**
_Wednesday Jul 23, 2014 at 12:41 GMT_
_Originally opened as https://github.com/robotology-legacy/qtyarp/issues/31_

----

There is confusion on what you can do with localhost and with a normal node (through yarprun), especially regarding stdio.

For example with localhost you can't use stiod but you can right click and "attach to stdio".

With yarprun you can use stdio.

**Comment by alecive** [comment]
Closing because multiple issues are referring to this, e.g. https://github.com/robotology/yarp/issues/244
