### ISSUE TITLE
`serialPort_nws_yarp` doesn't seem to work ok for face expressions

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#2973]
**Describe the bug**
Following up on https://github.com/robotology/icub-tech-support/issues/1539, we replaced the deprecated device `serial` (which has been removed in `yarp-3.8`) with the latest one `serialPort_nws_yarp`.

However, we didn't manage to make the face expressions work on iCubGenova11.

**To Reproduce**

We launched it this way:
```console
yarpdev --name /icub/face/raw --device serialPort_nws_yarp --subdevice serialport --context faceExpressions --from serialport.ini
```

Is that correct?

**Expected behavior**

To be able to control the face expressions normally.

**Screenshots**

**Configuration (please complete the following information):**
 - OS:
 - yarp version: `yarp-3.8` out of distro `2023.02.3`.
-  compiler:

**Additional context**
Hi @randaz81 

Did you make some tests with `serialPort_nws_yarp` paired with `faceExpressions`?

cc @martinaxgloria @Nicogene @traversaro @xEnVrE

**Comment by randaz81** [comment]
That specific nws needs to be launched through yarprobotinterface because yarpdev does not perform the attach operation on that specific device.
Issued fixed by https://github.com/robotology/icub-main/pull/883
