### ISSUE TITLE
QtYARPView port name showing partially

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#302]
<a href="https://github.com/kt10aan"><img src="https://avatars.githubusercontent.com/u/1415279?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kt10aan](https://github.com/kt10aan)**
_Thursday Aug 28, 2014 at 20:32 GMT_
_Originally opened as https://github.com/robotology-legacy/qtyarp/issues/36_

----

In QTYARPView, the port name at the bottom of window is "clipped", i.e., the lower part of the characters are not showing as the window ends. Resizing the window does not help.

**Comment by aitek4iit** [comment]
The issue #302 should have been solved. Please try it

**Comment by vtikha** [comment]
Closing...
