### ISSUE TITLE
[wish][doc] documentation of controlboardwrapper2 device 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#310]
More of a wish then a bug, but I was using a bit the controlboardwrapper2 device and its behaviour with respect to input configuration is quite a black magic (even checking on the `open(..)` source code!).  
When you have some time @barbalberto could you push some documentation on the used parameters? Thanks a lot! 

Some random points that would be nice to be addressed in documentation:
* is `subdevice` parameter supported or is supported only for running legacy code in `iCub_SIM`?

**Comment by barbalberto** [comment]
Documentation now is in doxygen with examples and quite accurate.
Can we close this?

**Comment by traversaro** [comment]
I remember that at some point you wrote the documentation. But I can't find the device documented in http://www.yarp.it/group__dev__impl__wrapper.html . 

Something went wrong in doxygen generation? 
This class seems not to be a device, but it appears to have the controlboardwrapper documentation: http://www.yarp.it/classyarp_1_1dev_1_1impl_1_1MultiJointData.html .

**Comment by barbalberto** [comment]
Yes, it looks like the documentation is generated in the wrong place :-(
should be fixed by eb9878, waiting for online doxygen updated to close the issue
