### ISSUE TITLE
Simplify Matlab bindings compilation and installation

### ISSUE THREAD

**Issue by arocchi** [robotology/yarp#314]
Installation of Matlab bindings should be automatic, similarly to the case for Python.
Steps missing:
[ ] the CMake should detect whether a Java compiler is installed
[ ] The FindMatlab should detect which version of Java Matlab currently uses
[ ] the CMake should use the previous information to automatically generate the .class files
[ ] the CMake should install those .class files in the appropriate directory structure somewhere (maybe a jyarp context?), and prompt a message to the user to help him setup the Matlab class path, or provide a load_yarp.m that can be created during compilation (this file should contain a command that adds a proper directory to matlab classpath, without the need to edit classpath.txt, and call LoadYarp)
[ ] the CMake should install jyarp.so (the same way it installs _yarp.so for Python)
see issue #309 from @edoardofarnioli

**Comment by traversaro** [comment]
Just to notify the people that may be interested in this: for iDynTree matlab bindings (https://github.com/robotology/idyntree#matlab) we are using an highly experimental SWIG branch that directly support Matlab classes generation, without passing per Matlab. 
To avoid requiring the user to have this recent SWIG version we are committing the generated code in the repo. This would not be feasible for YARP, but it may anyway be an interesting path to investigate for people interested in this. The CMake file for generating and compiling Matlab bindings in this way is available at https://github.com/robotology/idyntree/blob/master/bindings/matlab/CMakeLists.txt .

**Comment by lornat75** [comment]
this can be nice in fact

**Comment by traversaro** [comment]
Super-experimental version available at : https://github.com/robotology-playground/yarp-matlab-bindings

**Comment by traversaro** [comment]
Some of the points are addressed https://github.com/robotology/yarp/pull/572?w=1 .

**Comment by traversaro** [comment]
If no one volunteers for solving this issue, I think we can close it because in https://github.com/robotology/yarp/pull/572 the documentation should have been updated to permit to the average user to install the Matlab/Java bindings without much trouble.

**Comment by traversaro** [comment]
cc @francesco-romano
