### ISSUE TITLE
Homebrew yarp formula migrated to homebrew/x11 tap

### ISSUE THREAD

**Issue by kt10aan** [robotology/yarp#339]
Not really an issue, just an update:

The yarp formula was moved to the homebrew/x11 tap, as part of a move that saw all formulas in the main homebrew, with a hard X11 dependency, migrated to that tap.

I have updated the documentation accordingly in the wiki, as the users have to tap the homebrew/x11 tap first. Just a suggestion though: Shouldn't the homebrew/science be a more appropriate home for the yarp formula?

**Comment by vtikha** [comment]
This can be closed now. It is all included in the yarp installation documentation.
