### ISSUE TITLE
remote_controlboard getEncoders consistently returns false

### ISSUE THREAD

**Issue by jgvictores** [robotology/yarp#343]
Tested on Ubuntu 14.10 with updated yarp (e.g. Jan 8 2015, 7052a493228a6dbe44cb797614019e3eed00781a)
Tried on a different Ubuntu 14.10 machine, older yarp (Nov 24 2014, b27d466a10fadce549a9500452e4427123998495), getEncoders returned true. Updated repo and getEncoders started to consistently fail as in other machine.

The state:o stream outputs the correct values, so the issue should be on the remote_controlboard side. Maybe something happened on e42b9fa6ca7c6230dff395d7ae6f488780fb66c1 Merge branch 'ControlBoardWrapper2_NewOutputPort'?. I'm pretty puzzled as modules/RemoteControlBoard seems pretty intact since Nov 24 2014...

Though it happens in C++ (no intention to blame bindings), just for compactness, here's an example output from "ipython" vs "yarpdev --device test_motor" using the latest yarp:
In [1]: import yarp
In [2]: yarp.Network.init()
In [3]: dd = yarp.PolyDriver()
In [4]: p = yarp.Property()
In [5]: p.put("device","remote_controlboard")
In [6]: p.put("remote","/controlboard")
In [7]: p.put("local","/py")
In [8]: dd.open(p)
yarp: Port /py/rpc:o active at tcp://2.2.2.50:10007
yarp: Port /py/command:o active at tcp://2.2.2.50:10008
yarp: Port /py/state:i active at tcp://2.2.2.50:10009
yarp: Port /py/stateExt:i active at tcp://2.2.2.50:10010
yarp: Sending output from /py/rpc:o to /controlboard/rpc:i using tcp
yarp: Sending output from /py/command:o to /controlboard/command:i using tcp
yarp: Receiving input from /controlboard/state:o to /py/state:i using udp
[INFO]created device <remote_controlboard>. See C++ class RemoteControlBoard for documentation.
Out[8]: True
In [9]: ienc = dd.viewIEncoders()
In [10]: ienc.getAxes()
Out[10]: 4
In [11]: v = yarp.DVector(4)
In [12]: ienc.getEncoders(v)
Out[12]: False
In [13]: v[0]
Out[13]: 0.0
In [14]: v[1]
Out[14]: 0.0
((these values should not be zero))

**Comment by traversaro** [comment]
This seems an incompatibility between the new `remote_controlboard` remote device and the old `controlboard` wrapper device used by `test_motor`, that has been superseeded by the new `controlboardwrapper2` wrapper device.
Until the issue is fixed, you can disable in CMake the option CBW2_USE_YARP_THRIFT, and you should get the old behaviour, with a working `getEncoders` even with the `controlboard` wrapper device.
cc @barbalberto

**Comment by jgvictores** [comment]
Okay, getEncoders works correctly with https://github.com/lornat75/fakebot (which instances a controlboardwrapper2). Maybe we could add a DEPRECIATED warning when using (or compiling, or cmaking; wherever it is easier to implement) the old controlboard wrapper?

**Comment by lornat75** [comment]
Sorry about this. From what I know the old control board wrapper is actually obsolete and I would vote for removing it.

In addition we should and must add some sort of protocol version and relative check to ensure client-server compatibility. Will do that.

**Comment by barbalberto** [comment]
We have a single remoteControlBoard for 2 controlBoardWrappers (1 and 2) which are now very different from each others. To keep the compatibility with both will be hard do to. I agree to deprecate/remove the old one.

@jgvictores : do you have issue on simulator / real robot beside the test_motor?

**Comment by jgvictores** [comment]
On my side, yes... many sim+real robots to update (humanoid TEO, and another robot video-game side-project...) but I understand the difficulties of bw/compat. I'm okay with moving on and removing the old controlboard.
A :+1:  on https://github.com/robotology/yarp/issues/310 :-)

**Comment by paulfitz** [comment]
There's quite a lot to fix all at once if remote_controlboard compatibility has been broken. I'd vote for a more graceful upgrade path. if controlboardwrapper uses a wire protocol with breaking changes, why not *add* a different remote device with it that matches, rather than breaking the existing one? Then the old one can be deprecated, and people can move across on their schedules. Remember people can have demos, be trying to graduate, etc.
Also :+1:  on https://github.com/robotology/yarp/issues/310

**Comment by jgvictores** [comment]
@paulfitz Yes, that's true, people have their agendas...

@all What would your opinion on having the following pairs for a while be?
* remote_controlboard <-> controlboard ((with a depreciated warning, maybe even indicating a planned removal date))
* remote_controlboard2 <-> controlboardwrapper2 ((I guess this would mean minor changes in icub-main))

At least until https://github.com/robotology/yarp/issues/310 and https://github.com/robotology/yarp/pull/347 are good to go...

**Comment by lornat75** [comment]
Thinking again about this. I am not sure I understand the incompatibility, the changes that have been introduced concern broadcast of information, but this happens on a new port (so the old port provides backward compatibility).

**Comment by barbalberto** [comment]
One solution could be: the remoteControlBoard check if the new port exists get the broadcasted value, if not it falls back on old behaviour and send request to the wrapper. Right now it is not like this, if the cmake flag for new port is on, then it simply assume the port do exists

**Comment by lornat75** [comment]
@barbalberto: this is what I had in mind

**Comment by barbalberto** [comment]
This could be a fix untill we decide to use the new port as a standard and drop the old one, in that case will the problem arises again?

**Comment by lornat75** [comment]
yes, but it allows a smoother transition as @jgvictores @paulfitz suggest. 

In addition it allows us to remove the old redundant devices.

**Comment by barbalberto** [comment]
Ok, I'll do it.

**Comment by barbalberto** [comment]
Done in CBW2_back_compatibility branch. Tested with the iCub_SIM and it works, if someone can do a test also on win platform I can merge it.

**Comment by jgvictores** [comment]
@barbalberto Did some win platform tests on your branch. Same remote_controlboard (positonMove, getAxes, and getEncoder methods) works okay against https://github.com/lornat75/fakebot (instances controlboardwrapper2) and against test_motor (instances controlboard). Upon connecting to the old controlboard instance, a recommendation to update message is displayed as intended. Thanks, I believe you can merge!

**Comment by jgvictores** [comment]
Tried branch against iCub_SIM on win platform, works ok too.

**Comment by barbalberto** [comment]
pushed the cangges in the master, I'll remove the branch
