### ISSUE TITLE
UDP in macOS

### ISSUE THREAD

**Issue by iron76** [robotology/yarp#35]
When connecting ports on MacOS there is an issue with UDP connections. A preliminary debug showed that connection is successful only if packet size is small enough. Examples:

yarpdev --device test_grabber
yarpview --name  /iron/read
yarp connect /grabber /iron/read udp

causes an immediate disconnection (tcp works instead). On the other hand, reducing size of images as follows:

yarpdev --device test_grabber --width 10  --height 10
yarpview --name  /iron/read
yarp connect /grabber /iron/read udp

works smoothly.

**Comment by drdanz** [comment]
@iron76 Is this still an issue or can we close this?

**Comment by drdanz** [comment]
Closing since no feedback was received in the last 6 months. Please re-open if this is still an issue.

**Comment by iron76** [comment]
Not an issue anymore.
