### ISSUE TITLE
Weird body of init() methods generated by Thrift

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#370]
Take a look at the following lines of a thrift-generated file:

[#777](https://github.com/robotology/icub-main/blob/master/src/idl_generated_code/src/depth2kin_IDL.cpp#L777), [#893](https://github.com/robotology/icub-main/blob/master/src/idl_generated_code/src/depth2kin_IDL.cpp#L893), [#967](https://github.com/robotology/icub-main/blob/master/src/idl_generated_code/src/depth2kin_IDL.cpp#L967), [#1118](https://github.com/robotology/icub-main/blob/master/src/idl_generated_code/src/depth2kin_IDL.cpp#L1118)

They're a bit weird...

**Comment by paulfitz** [comment]
5d19db3 may help, sorry for the delay responding.

**Comment by pattacini** [comment]
thanks @paulfitz
