### ISSUE TITLE
Set timestamp on bufferedport - Yarp bindings in C# - Error

### ISSUE THREAD

**Issue by vicentepedro** [robotology/yarp#372]
Hi all,

I tried to set a time stamp in a bufferedport. I'm using the yarp bindings for C#.

    Stamp ts = new Stamp(); 
    outputport.setEnvelope(ts);

I get the folowwing error:

    error CS1503: Argument #1 cannot convert `Stamp' expression to type `PortWriter'

@stephane-lallee @paulfitz, any idea?

**Comment by paulfitz** [comment]
@vicentepedro this should be fixed now, please reopen issue if not. Thanks for reporting the problem!
