### ISSUE TITLE
[C# bindings] adding MonoPixel16 stuff

### ISSUE THREAD

**Issue by vicentepedro** [robotology/yarp#379]
Hi all,

I think it would be great to have the PixelMono16 template translated for C#. (updating the yarp.i file, it's the best way?)

I manage to do it, but it would be great to have this on the yarp repository.

Regards,
Pedro

**Comment by paulfitz** [comment]
Updating the `yarp.i` file is the best way, yes. Have you time to make a pull request with your local fix? Otherwise I can do it.
