### ISSUE TITLE
Standard headers for MSVC

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#384]
We have these files for MSVC in YARP:
- `src/idls/thrift/msvc/inttypes.h`
- `src/idls/thrift/msvc/stdint.h`
- `src/libYARP_manager/include/yarp/manager/ymm-dir.h` (slightly modified version of `dirent.h`)
- `src/yarpdataplayer-gtk/include/msvc/dirent.h`
- `src/yarpdataplayer-qt/msvc/dirent.h`

`inttypes.h` and `stdint.h` are standard C99 headers, `dirent.h` is standard posix.

I think we should:
- [ ] Check if these are required for all MSVC version (including newer) and ensure that the compiler version is used when available.
- [ ] Move these files outside from the `src` directory (perhaps in `extern`), so that we can avoid duplicating these files.

**Comment by paulfitz** [comment]
Sounds good to me!

**Comment by drdanz** [comment]
`cinttypes` and `cstdint` are standard c++11 headers, so we can rely on them as soon as we require c++11

**Comment by traversaro** [comment]
FYI: A MIT-licensed dirent compatibility-layer is available at https://github.com/tronkko/dirent , and it has been recently packaged in vcpkg : https://github.com/Microsoft/vcpkg/pull/1345#event-1143223257 .

**Comment by drdanz** [comment]
in c++17 dirent should no longer be necessary 😆

**Comment by traversaro** [comment]
I guess YARP mantainers in 2024 will be very happy!

**Comment by drdanz** [comment]
`cstdint` and `cinttypes` are standard c++11, we can use them and remove these files, since all the supported MSVC versions have them.
Apparently, the only remaining issue is `dirent.h`, we should move it in extern. I think the origin of the file is this: https://github.com/tronkko/dirent

**Comment by drdanz** [comment]
Stupid github (or maybe it is the zenhub addon) hiding previous comment, I was pretty sure I wrote this in the past! 😆

**Comment by drdanz** [comment]
This is fixed in latest devel.

**Comment by drdanz** [comment]
Fixed by 5bf69878c1a6526b182d9838a74636db65719fc6
