### ISSUE TITLE
qtYarpmanager crashed 

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#385]
platform: `blackie`
version: `qt`

terminal output:
```
icub@icub15:~$ yarpmanager
||| did not find ymanager.ini
yarp: cannot read from ymanager.ini
||| did not find ymanager.ini
QString::arg: Argument missing: /inspect, /icub/inertial
QString::arg: Argument missing: /inspect, /icub/inertial
Segmentation fault
```

Shall we start adding more verbosity to `qtyarpmanager` in order to better track its behavior down?

**Comment by francesco-romano** [comment]
Maybe also compiling it in Debug mode?

**Comment by alecive** [comment]
Closing because difficult to reproduce without more information. I'd still add some verbosity to the manager in order to track its behavior down, though. @apaikan
