### ISSUE TITLE
IPositionControl2::checkMotionDone() over joints sub-set does not work

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#387]
I've tested the malfunction on the gaze controller where the `checkMotionDone()` is called over just the first 3 joints (out of 6).

**Comment by lornat75** [comment]
We should reproduce this problem in https://github.com/robotology/robot-testing before fixing it.

**Comment by barbalberto** [comment]
Shall we use the iCub_SIM, gazebo or fakebot or similar to reproduce it? The bug could be in the communication or in the driver implementation.
@ugo I guess you found it on the iCub, is it the same also on simulators?

**Comment by pattacini** [comment]
I didn't test it on the simulator because the blending of position and velocity commands was not available on iCub_SIM in the past and, however, I presume it is still to be validated.

**Comment by barbalberto** [comment]
The description in the header file was wrong so lead to a wrong usage, the function always return a single bool value also when called for a group of joints or all joints.
This is the only function which is asymmetric in the input/output: you ask for 3 joints and get 1 answer only and therefore is easy to forget this behaviour.
As @pattacini was pointing out, we also lose some information in the process, which joint has not complete the movement yet.

**Comment by pattacini** [comment]
thanks @barbalberto 
@lornat75, what do you think about asymmetry and loosing of details of the single joints?

**Comment by pattacini** [comment]
cc @AnneLaureM @gregoire-pointeau

**Comment by lornat75** [comment]
In the meanwhile I have added check for IPositionControl2 in robotology/robot-testing. 

Can we close this specific issue and open another one specific for the design of checkmotiondone?
