### ISSUE TITLE
occasional timeout in PortTest

### ISSUE THREAD

**Issue by paulfitz** [robotology/yarp#39]
One of the test machines is reporting occasional timeouts in PortTest, such as this one:
    http://dashboard.icub.org/testDetails.php?test=5947&build=17138

The last few lines before timing out are consistently:

    yarp: 0 | PortTest: check reader handler, bufferedport style...
    yarp: Port /out active at tcp://127.0.0.1:10012
    yarp: Port /in active at tcp://127.0.0.1:10002
    yarp: Receiving input from /out to /in using tcp
    yarp: Sending output from /out to /in using tcp
    yarp: 0 | PortTest:   [object came through] passed ok
    yarp: Removing output from /out to /in
    yarp: Removing input from /out to /in

**Comment by drdanz** [comment]
@paulfitz Is this still an issue or can we close this?
