### ISSUE TITLE
[yarpmanager] Integrate yarpdatadumper to the manager inspect menu item

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#391]
Currently, if I right-click on a port on `yarpmanager`, I can select the `inspect` item from the menu it appears, and I have these choices:
 * `yarpview`
 * `yarphear`
 * `yarpread`
 * `yarpscope`

It would be nice to have `yarpdatadumper` as well, to automatically dump a port if needed.

**Comment by alecive** [comment]
Commit c52e110 has let me modify the `yarpmanger (QT)` in order to integrate the feature and start the datadumper with a  right click on the port to dump. Now the problem is related to the closure of the aforementioned datadumper: after starting, the `datadumper` runs in background,  and I honestly don't know what would be the best solution. Any idea would be welcome!

**Comment by pattacini** [comment]
@alecive, you could send the "quit" request to the rpc port opened up by `yarpdatadumper`.

For example:
```
echo "quit" | yarp rpc /dump/rpc
```
