### ISSUE TITLE
problem to drag and close "yarpview --compact"

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#393]
When the yarpview is launched with `--compact` option, the `Atl+Drag` feature is not available on Windows and is not even possible to be closed up.

**Comment by pattacini** [comment]
Could we restore at least the `title bar`?

**Comment by alecive** [comment]
We agreed with @pattacini to have two options from now on:

 * `--compact` will keep the titlebar but get rid of the statusbars
 * `--minimal` will remove the titlebar as well, for more extreme uses (and users)

**Comment by alecive** [comment]
It should be fixed now.
@pattacini can you test the behavior of the new feature on windows?

**Comment by pattacini** [comment]
it works.

**Comment by alecive** [comment]
@pattacini what about putting the name of the yarpview port in the title bar instead of "YARP Qt image viewer" when in compact mode?

**Comment by pattacini** [comment]
yep, it'd be a nice plus
