### ISSUE TITLE
Connect BufferedPort with another port programmatically

### ISSUE THREAD

**Issue by Arikae** [robotology/yarp#401]
How can I connect a `BufferedPort<ImageOf<PixelRgb>> imagePort;` to another port?
I can connect this port via console with 'yarp connect' but I couldn't find a way to do this programmatically.
The intention is to access the cameras of the iCub and connect them with these ports.

**Comment by pattacini** [comment]
You can do that from within the code by calling [yarp::os::Network::connect](http://wiki.icub.org/yarpdoc/classyarp_1_1os_1_1NetworkBase.html#a272f49fa804b73b5aee0cd3186d4e4bd) method.

That being said, connections done internally are generally against the _observer_ paradigm we should adhere to for yarp programming ... however the cameras ports are deemed to be low-level resources, so it remains controversial.
