### ISSUE TITLE
Carriers.h should be moved out from impl

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#402]
Any 3rd party project using yarp should not use impl files, but in order to create carrier plugins, the yarp::os::impl::Carriers::addCarrierPrototype() is called by the template.

We should move ``yarp/os/impl/Carriers.h`` into ``yarp/os/Carriers.h`` and the class ``yarp::os::impl::Carriers`` to ``yarp::os::Carriers`` in order to solve this issue.

It shouldn't be hard to do, the only requirements is to use PIMPL to hide the usage of ``yarp::os::impl::PlatformVector<Carrier *>``.

**Comment by paulfitz** [comment]
or expose `addCarrierPrototype` elsewhere in the api, e.g. as a static method of `yarp::os::Carrier`?

**Comment by drdanz** [comment]
Both work for me, even if the I was suggesting to move it in analogy to ``yarp/dev/Drivers.h``
