### ISSUE TITLE
Qt yarpmanager does not use external_editor option from the config file

### ISSUE THREAD

**Issue by apaikan** [robotology/yarp#406]
### using yarpmanager (QT) 
- open a terminal and  `cd $YARP_ROOT/src/yarpmanager/tests` .
- modify the `external_editor` option from `ymanager.ini` and set to your desire editor (e.g., gvim).
- run the `yarpmanager` and from the application section double click on one of the xml file (e.g., eyesviewer-localhost.xml) 
- yarpmanager still using the default external editor (e.g., gedit) 

[side note]: the `yarpmanager-gtk` is fine!

**Comment by lornat75** [comment]
@aitek4iit: can you check this?

**Comment by aitek4iit** [comment]
Yes, I'll check it
