### ISSUE TITLE
Documentation on Qt5 dependencies on Ubuntu 14.04 is not correct

### ISSUE THREAD

**Issue by kt10aan** [robotology/yarp#424]
The Qt5 dependencies for Ubuntu Trusty listed at http://wiki.icub.org/yarpdoc/dependencies.html, are not sufficient.
With the above dependencies installed, I get the following error when running yarpview:
```
QQmlApplicationsEngine failed to load component
qrc:/qml/QtYARPView/main.qml:52 Type VideoSurface unavailable
qrc:/YARPView/VideoSurface.qml:14 module "QtQuick.Dialogs" is not installed
```

Since that was my first installation of Trusty that I used the ubuntu packages and not the Qt5 installer, I cannot seem to find which package is missing.

**Comment by drdanz** [comment]
@kt10aan The package should be qtdeclarative5-dialogs-plugin or something similar, can you check if it exists and if it fixes your issue?

**Comment by kt10aan** [comment]
@drdanz , thanks! Installing qtdeclarative5-dialogs-plugin fixed the issue :)

**Comment by drdanz** [comment]
@kt10aan Updated docs (will be online as soon as the documentation is re-generated), thanks for reporting.
