### ISSUE TITLE
Adding "true" and "false" strings to Bottle produces unwanted quotation marks

### ISSUE THREAD

**Issue by gsaponaro** [robotology/yarp#431]
I have a module that needs to add the words true/false (actual strings, not boolean values) to a Bottle. However I observed that adding the strings ```true``` and ```false``` to a Bottle then printing it on screen shows quotation marks around these words, while other strings show no quotes. I guess it has to do with true and false being reserved keywords in C++.

Example:

    Bottle bottle;
    bottle.addString("word1"); 
    bottle.addString("true");
    bottle.addString("any_other_word");
    cout << bottle.toString().c_str() << endl;

prints ```word1 "true" any_other_word``` <-- notice quotation marks around ```true```. Is it possible to obtain ```word1 true any_other_word``` instead?

**Comment by gsaponaro** [comment]
In the end, this is not really a problem for our project: the client that reads the Values from my Bottle works whether those quotation marks are present or not.

However, I am still curious about this behaviour, if is is expected of yarp to put those quotes around true/false, do you know @paulfitz @drdanz?

Please feel free to close this issue when you want.

**Comment by paulfitz** [comment]
I think this behavior is to keep unquoted true/false free for eventual json compatibility. When converting the entire bottle, each element is serialized in a way that lets it be read again as the original type.  You could ask `bot.get(1).asString()` if you expect a string, and there will be no quoting. Sorry for the confusion and delay responding.

**Comment by gsaponaro** [comment]
Thank you, no problem.

/cc #351
