### ISSUE TITLE
[yarp::os::Module] runModule calls exit(1) on return

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp#432]
The class `Module` calls `exit(1)` instead of returning from the `runModule` method. 
This terminates the application without any cleanup possible in the various destructors.

**Comment by pattacini** [comment]
`yarp::os::Module()` is _practically_ deprecated and replaced by `yarp::os::RFModule()`.
Closing.

**Comment by alecive** [comment]
@pattacini agreed, but do you know that one of the most used modules in the `icub-main` repo, i.e. the `pf3DTracker` uses `yarp::os::Module`? :smile:

**Comment by pattacini** [comment]
`pf3DTracker` needs to be updated then.
