### ISSUE TITLE
[yarpmanager] No about dialog any more

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#444]
Currently, if one clicks on the about (help->about), nothing happens. With `yarpmanager-gtk` instead there is a proper info window. @aitek4iit

**Comment by aitek4iit** [comment]
Fixed

**Comment by alecive** [comment]
@aitek4iit now it does not link any more (as you can see in #455 ).

**Comment by aitek4iit** [comment]
I think it is fixws now. I added some files but i did not update the cmake

**Comment by pattacini** [comment]
I realized that the copyright is ... wrong
we are no longer RBCS, we are `iCub Facility` :-)
could we check in all Qt applications if this info is reinforced?

**Comment by apaikan** [comment]
It seems this issue is fixed. Shall we close it?

**Comment by alecive** [comment]
Closing.
