### ISSUE TITLE
Appearance of yarpmotorgui-qt on linux systems is bad

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#460]
on windows yarpmotorgui-qt is ok, but on linux several widgets and labels are truncated
![yarpmotorgui](https://cloud.githubusercontent.com/assets/2869969/6866752/b12a1a06-d47b-11e4-8df8-fcb0a4ae33eb.jpg)

**Comment by alecive** [comment]
@randaz81 as a matter of fact, this happens on the debian machines on the clusters, but it does not happen on Ubuntu.

**Comment by randaz81** [comment]
@alecive tested on Ubuntu 14.04, the problem is the same.
@aitek4iit can you check this issue?

**Comment by aitek4iit** [comment]
I have to a set up an ubuntu environment. As soon as I can i'll check it. Howevere I think it's matter of fonts: I don't specify any fints, so each system uses it's own default fonts. I think that specifynig fonts and font size could solve the issue.

**Comment by lornat75** [comment]
if setting up an ubuntu system takes time consider coming up to visit us!

**Comment by drdanz** [comment]
That's very likely to be a problem with the qt5 style on debian and on some ubuntu... @alecive which Ubuntu version are you using?

**Comment by aitek4iit** [comment]
I have just committed a fix that could solve the problem. Can you check it please?

**Comment by alecive** [comment]
It is working for me. But we have to test it on the cluster. @aitek4iit what did you do? Did you specify a font?

**Comment by alecive** [comment]
Btw, I remember that this was also happening with other gui, such as `frameGrabberGui2`, but I have to investigate further.

**Comment by aitek4iit** [comment]
Yes, I specified a font and a font size: Actually is "Tahoma 8pt", that is the same as on windows. Linux uses a font bigger than windows by default.

**Comment by alecive** [comment]
Ok. Tahoma 8pt is not installed on linux systems (it is a windows font), so you might encounter more problems over the time because it fallbacks to some other fonts. But on my machine everything works (probably because it still uses the `8pt` directive), so it's ok. I'll keep you updated for the debian machines as soon as I get one.

**Comment by lornat75** [comment]
Maybe it falls back to a different font, but it keeps the size, this is why it works.

Anyway: is it possible to specify different fonts on windows and linux? in this case we could select a font that is available on both systems.

**Comment by aitek4iit** [comment]
Yes it is possible using #ifdefs

**Comment by lornat75** [comment]
@alecive any chance you tested it?

**Comment by alecive** [comment]
I did (sorry if I wasn't clear). As I said in my previous comment, on my machine behaves well, but it might be that on some other machines this is not the case. We can neither foresee nor test any possible user setting. Therefore, I suggest to use a more standard font, such as `Arial` or whatever suitable for the task (arial is not great for quite a number of reason, but it would fix the issue).

**Comment by aitek4iit** [comment]
I think we can specify only the point size of the font and not the family. This could solve the problem, and would let the software use the system default font.

**Comment by alecive** [comment]
@aitek4iit if that is the case, let's go with it :)

**Comment by aitek4iit** [comment]
Ok. Fixed. Can you give a try?

**Comment by alecive** [comment]
It works, thanks! Closing.
@aitek4iit for the future: it would be useful if you reference the issue you're fixing into your github commit message. In this way, we can better track your commits in the issues directly! Take a look at this https://guides.github.com/features/issues/#notifications
