### ISSUE TITLE
positionDirect mode not properly handled by yarpmotorgui

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#472]
if I start yarpmotorgui without the --direct option, joints previously set in direct mode (by other applications) are not properly handled (the control mode of the joint is not displayed at all).
The correct behaviour is to always display the control mode of the joint, and to the disable the command slider if the user does not uses the --direct option.

**Comment by aitek4iit** [comment]
Fixed

**Comment by lornat75** [comment]
@randaz81 can you verify this?

**Comment by alecive** [comment]
The issue has been fixed. Closing
