### ISSUE TITLE
yarpMotorGui - Calib_all button

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#476]
"Calibrate all" button should be disabled by default, unless program is started with --calib option.
It works for calib button on single joint, the same mechanism should be implemented also for upper button.
![calib_all_button](https://cloud.githubusercontent.com/assets/4061020/7181351/54b89b06-e44a-11e4-8cc6-eb6a96935594.jpg)

btw, I cannot see the icon for buttons located near that calibrate all button :'(

**Comment by pattacini** [comment]
The appearance of buttons might be related to #460

**Comment by aitek4iit** [comment]
Fixed The enable problem on the button

**Comment by alecive** [comment]
The appearance of icons is related to a missing library. You need to install `libqt5svg5` in order to see the new icons (that are in svg format). I updated the documentation some weeks ago, you can see it here: http://wiki.icub.org/yarpdoc/dependencies.html

**Comment by lornat75** [comment]
@mbrunettini

**Comment by barbalberto** [comment]
Great, both the issues are fixed,

thanks @aitek4iit  and @alecive
