### ISSUE TITLE
Namespace in thrift: generate header files in namespace-like location

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp#487]
When we generate code from a thrift file which defines a namespace, the resulting class is correctly enclosed in the namespace definition.
On the file system part, instead, the headers hierarchy is "flat": headers are added in the `include` folders. 
It would be nice if a proper hierarchy is added  in the file system. Unfortunately I know that there is no a standard way to do this. This example should explain better the issue.
(files taken from https://github.com/robotology/gazebo-yarp-plugins/tree/master/thrift/clock)
We have a thrift file like the following:

``` thrift
namespace yarp GazeboYarpPlugins

service ClockServer {
    /** Pause the simulation if it was running
     */
    oneway void pauseSimulation();
...
```

The class is correctly generated as the following:

``` cpp
namespace GazeboYarpPlugins {
  class ClockServer;
}


class GazeboYarpPlugins::ClockServer : public yarp::os::Wire {
...
```

But the filesystem hierarchy is: `include/ClockServer.h` while I had expected `include/GazeboYarpPlugins/ClockServer.h`.
With the latter it is possible to include the header file in the following way in an external library:

``` cpp
#include <GazeboYarpPlugins/ClockServer.h>
```

thus rendering explicit the library.

**Comment by francesco-romano** [comment]
Related in some way to https://github.com/robotology/yarp/issues/445

**Comment by elen4** [comment]
@francesco-romano in your example, can you try putting the `clock_rpc.thrift` file inside a `GazeboYarpPlugins` subdir? The `yarp_idl_to_dir` macro should then be called like this:

```cmake
yarp_idl_to_dir(GazeboYarpPlugins/clock_rpc.thrift ${CMAKE_CURRENT_SOURCE_DIR}/autogenerated CLOCKRPC_SRC CLOCKRPC_HEADERS CLOCKRPC_INCLUDES)
```

Does it work, or is there any other downside to this?

**Comment by francesco-romano** [comment]
Hi @elen4.

If I try in this way, I get everything generated in the `GazeboYarpPlugins` directories: meaning both `include/GazeboYarpPlugins/*.h` and `src/GazeboYarpPlugins/*.cpp`. 
Furthermore the `Config.cmake` file has as a name the whole filesystem structure (separated with `_`)

**Comment by traversaro** [comment]
The main problem (mostly aesthetic) of the solution suggested by @elen4 is that if you have [several headers files](https://github.com/robotology/gazebo-yarp-plugins/blob/master/thrift/worldinterface/autogenerated/include) like `Color.h`, `Pose.h`, this are included in the the files that uses them (such as `WorldInterfaceServer.h`) simply as `#include <Color.h>`, so any downstream project that includes them must include them as  `WorldInterfaceServer.h`.

**Comment by traversaro** [comment]
> The main problem (mostly aesthetic) of the solution suggested by @elen4 is that if you have [several headers files](https://github.com/robotology/gazebo-yarp-plugins/blob/master/thrift/worldinterface/autogenerated/include) like `Color.h`, `Pose.h`, this are included in the the files that uses them (such as `WorldInterfaceServer.h`) simply as `#include <Color.h>`, so any downstream project that includes them must include them as  `WorldInterfaceServer.h`.   

Actually I said something stupid, I did not check the correct files. All the files are correctly included with their new location.

**Comment by drdanz** [comment]
I think this has been fixed for a while now. Please reopen if it is not.
