### ISSUE TITLE
yarpdataplayer keyboard shortcuts do not work any more

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#488]
During the switch from `gtk` to `qt` , we lost one very useful feature that was available in `yarpdataplayer`, i.e. the ability to have shortcuts. In particular, `CTRL+O` in order to open files.

I'm on Ubuntu 14.04 for what matters :)

**Comment by vtikha** [comment]
Added the ability to open  `CTRL+O` and close  `CTRL+Q` in the yarpdataplayer
