### ISSUE TITLE
assertion failure while closing yarp module

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#492]
I often get an error:
`[FATAL]Assertion failure (finished==true)`
when closing a yarp module.

It probably comes from line 451 of PortCore.cpp (yarp):
`// We should be finished now.`
`stateMutex.wait();`
`yAssert(finished==true);`
`stateMutex.post();`

It happens only on windows.
This is NOT related to @barbalberto work on `add_abrt` branch

**Comment by randaz81** [comment]
Test case:
just running a simple yarp read e.g:
yarp read ... /icubSim/head/state:o
when I press Ctrl+C I get pure vitual function call + the error mentioned above.
The first time I saw this error was about 1-2 month ago, with the introduction of shared libraries plugins in yarp (even if I can't surely tell if this is really correlated or not)

**Comment by randaz81** [comment]
It was found that the environment variable YARP_FORWARD_LOG_ENABLE=1 is responsible for this issue (windows platform only)

**Comment by barbalberto** [comment]
This has been addressed in [PR 942](https://github.com/robotology/yarp/pull/942)

**Comment by randaz81** [comment]
Probably fixed by [PR 942](https://github.com/robotology/yarp/pull/942)
