### ISSUE TITLE
Neither interrupt nor close have effect on a blocking read if open was not called before on the port

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#502]
Corner case: if you forget to open a port but call `read`, the calling thread get blocked forever (neither `interrupt` nor `close` unblock it). 

Probably the problem is not in the behavior of `interrupt` or `close`, rather the `read` should return with an error if called on a port that was not correctly opened.

**Comment by apaikan** [comment]
closes on pull request #573.
