### ISSUE TITLE
yarpmanager admin toolset 

### ISSUE THREAD

**Issue by apaikan** [robotology/yarp#528]
It would be useful (as many other user asked) to have a set of admin tools in the `yarpmanager` for some of the yarp commands such as `yarp clean`, `yarp name list` and etc.

**Comment by pattacini** [comment]
I vote to not implement this.
Don't be lazy.

**Comment by apaikan** [comment]
Soon we will have another tool-set dealing with connections in yarp network (see https://github.com/robotology-playground/yarp-admins).

**Comment by pattacini** [comment]
:+1:
