### ISSUE TITLE
mjpeg carrier on windows

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#531]
- [ ] Which binary version of libjpeg should be used?
   * http://gnuwin32.sourceforge.net/packages/jpeg.htm
   * http://www.libjpeg-turbo.org/Documentation/OfficialBinaries
- [ ] Where should the libjpeg dlls be? Apparently having the library in PATH is not enough
- [ ] Using the gnuwin32 version of the library it does not build by default.

**Comment by randaz81** [comment]
My system is Windows 7, 64 bit, VS ultimate 20013.
I tested the second option, downloaded from http://sourceforge.net/projects/libjpeg-turbo/files/1.4.1/libjpeg-turbo-1.4.1-vc.exe/download

I installed the library in my robotology folder and I added `/robotology/libjpeg-turbo\bin` to `%PATH%` environment variable.

I added a `FindJPEG.cmake` file to the `yarp\conf` folder, with the following contents:
[FindJPEG.cmake | uploaded via ZenHub](https://files.zenhub.io/55acf6c59098e37a679252e7)
This ovverides the standard `FindJPEG.cmake` included by `C:\Program Files (x86)\CMake 2.8\share\cmake-2.8\Modules`

Additional notes:
* the above instructions work for the library `jpeg.lib`, which dynamically loads jpeg62.dll
* You can manually specify `jpeg-static.lib` in `JPEG_LIBRARY` cmake option to use the static version.
