### ISSUE TITLE
manager on windows opens a console when processes are executed on localhost

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#542]

**Comment by apaikan** [comment]
we can try this: http://www.codeproject.com/Articles/2537/Running-console-applications-silently

But i am not sure then the console apps can receive signals.

**Comment by lornat75** [comment]
StartupInfo.dwFlags = STARTF_USESHOWWINDOW;
	StartupInfo.wShowWindow = SW_HIDE;

This works, however I think it also affects the guis :(

I would like to see if we can actually take advantage of this and use the consoles for input/output....

**Comment by lornat75** [comment]
This fix caused shutdown problems. In windows when processes are created with their own console they no longer receive termination signals from parent (well, at least doing this is not obvious).
