### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by WurmD** [robotology/yarp#553]
at http://wiki.icub.org/yarp/specs/dox/user/html/install_yarp_windows.html

> If you have an older version of YARP you may find that you don't **that the yarpidl_rosmsg program used in this tutorial.**

Something seems to be missing there

**Comment by pattacini** [comment]
Hi @WurmD where exactly is that sentence? I couldn't find it in the page you linked.

**Comment by WurmD** [comment]
sorry, here 
http://wiki.icub.org/yarpdoc/yarp_with_ros.html
