### ISSUE TITLE
Windows installer for YARP does not update PATH environment variable when YARP is not selected

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#588]
System: Windows 7, Visual Studio 2012, installer: 
https://github.com/robotology/yarp/releases/download/v2.3.64/yarp_2.3.64_v12_x86_1.exe

PATH should be updated to incude:
ACE_ROOT/bin
Qt5_DIR/../../../bin

@mbrunettini

**Comment by lornat75** [comment]
We could not replicate this problem, closing for now.

**Comment by FrankOcean11** [comment]
which Yarp program should i download for my home built Humanoid ? and from where? [link?] for win8.1

**Comment by pattacini** [comment]
Hi @FrankOcean11
Yarp can be installed as binary package or compiled from sources; instructions for Windows are available here: http://wiki.icub.org/wiki/ICub_Software_Installation#Installation_on_Windows.

Btw, official Yarp documentation can be found at this link: http://wiki.icub.org/yarpdoc/index.html.

Should you have further questions/doubts, please consider next time opening a new issue and/or posting on [**`Q&A`**](https://github.com/robotology/QA).
