### ISSUE TITLE
Broken link to pdf manual

### ISSUE THREAD

**Issue by pauljurczak** [robotology/yarp#601]
The link to [official documentation in pdf](http://wiki.icub.org/yarp/specs/dox/min/latex/refman.pdf) on [yarp wiki page](http://wiki.icub.org/yarp/) is broken.

**Comment by pauljurczak** [comment]
*People* link is broken too.

**Comment by pattacini** [comment]
Thanks for reporting.
@mbrunettini could you please have a look into this?

**Comment by mbrunettini** [comment]
It seems that the PDF creation is missing in the doxygen makefile.
@drdanz : can you enable it again?

**Comment by traversaro** [comment]
That page ( http://wiki.icub.org/yarp/ ) has quite a lot of outdated links (bugs on sourceforge, source on sourceforge). Perhaps it make sense to just delete it and redirect it to http://wiki.icub.org/yarpdoc/ ?

**Comment by lornat75** [comment]
Indeed, @mbrunettini can you get access to the page and redirect it?

**Comment by mbrunettini** [comment]
Page redirected.
