### ISSUE TITLE
[OSX] yarpview and yarpscope .app bundle do not work

### ISSUE THREAD

**Issue by iron76** [robotology/yarp#604]
I am trying to use the new qt-based yarpview.app on Mac OsX 10.11. Launching the app via finder (double clicking on the icon) or via terminal (open ./yarpview.app) result in an instantaneous closure of the app with not further message. Other applications (e.g. yarpmotorgui.app) work.

**Comment by francesco-romano** [comment]
Yep.. this is a known issue: see here https://github.com/robotology/yarp/issues/580
 I think this should become more urgent now @drdanz

**Comment by francesco-romano** [comment]
Was fixed in 844949bce20ad1a2df2548225631c9abaf5caedc

**Comment by vtikha** [comment]
+10000000
