### ISSUE TITLE
All existing links to doxygen documentation are broken

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#605]
Links to the yarp doxygen documentation (such as [http://wiki.icub.org/yarp/specs/dox/user/html/yarpmanager.html](http://wiki.icub.org/yarp/specs/dox/user/html/yarpmanager.html) ) are broken. 
As far as I understand the `wiki.icub.org/yarp/specs/dox/user/html` part of the URL be substituted by `yarp.it`, and so [http://yarp.it/yarpmanager.html](http://yarp.it/yarpmanager.html) is correctly working.
Unfortunately apparently the [http://wiki.icub.org/yarp/specs/dox/user/html/yarpmanager.html](http://wiki.icub.org/yarp/specs/dox/user/html/yarpmanager.html) page is now redirected to [http://www.yarp.it/specs/dox/user/html/yarpmanager.html](http://www.yarp.it/specs/dox/user/html/yarpmanager.html), that gives 404 error.

cc @lornat75 @mbrunettini

**Comment by mbrunettini** [comment]
Fixed broken liks.
The old URL in documentation (links to wiki.icub.org) will be replaced with www.yarp.it
