### ISSUE TITLE
Wrong RPATH for Plugins

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#617]
Plugins are not installed in lib, but in lib/yarp, therefore the RPATH should be different.

**Comment by drdanz** [comment]
@barbalberto Can you please confirm that this is fixed?

**Comment by barbalberto** [comment]
Issue is fixed, repos that wants to use plugins have to add those lines in the cmakelists

```
add_install_rpath_support(LIB_DIRS "${CMAKE_INSTALL_FULL_LIBDIR}"                                   # Libraries
                          BIN_DIRS "${CMAKE_INSTALL_FULL_BINDIR}"                                   # Binaries
                                   "${CMAKE_INSTALL_PREFIX}/${{REPO_NAME}_DYNAMIC_PLUGINS_INSTALL_DIR}"     # Plugins
                          USE_LINK_PATH)
```

**Comment by drdanz** [comment]
@barbalberto Awesome! Should we update the documentation for creating plugins somewhere?

**Comment by barbalberto** [comment]
yes, I guess the right page is this one http://www.yarp.it/add_a_plugin.html
I'll do it soon
