### ISSUE TITLE
yarpdataplayer streams halved images

### ISSUE THREAD

**Issue by gsaponaro** [robotology/yarp#618]
Hi, I am trying to use some old datadumps (of Image type), but when I stream the images to a viewer, I can only see the top half:

![halved_image_issue](https://cloud.githubusercontent.com/assets/6716962/10665825/c07cd734-78c5-11e5-96ad-58a8860abe07.png)

**yarpdataplayer** (Qt version) is giving this warning:
````
your specific IPL format (BGR depth 8 -> bgr) does not match your YARP format ()
Making a copy instead of just wrapping...
````

Steps to reproduce the problem:
* with **yarpdataplayer**, play [this datadump](http://users.isr.ist.utl.pt/~gsaponaro/temp/dataset_for_halved_image_issue.zip) (7MB)
* start a **yarpview**
* connect the image stream to the viewer

Interestingly, the obsolete **yarpdataplayer-gtk** streams the images fine.

This could be related to https://github.com/robotology/yarp/commit/d268a75019985fb520d3fe92648de1fe9876adba.

**Comment by vtikha** [comment]
@gsaponaro 
I have just tried the dataset on a MacOSX and a Windows machine with the latest yarp and I have a full image in the stream. The frame rate is low but looking at the timestamps it seems expected. Furthermore I do not have the BGR warning reported. Do you have yarp updated? The **the obsolete yarpdataplayer-gtk** should not be used as it no longer supported. **yarpdataplayer** is back complatible with old datadumps. 

<img width="1280" alt="screen shot 2015-10-22 at 15 25 03" src="https://cloud.githubusercontent.com/assets/4537987/10666432/e12bfeae-78d1-11e5-87f7-eb37632ca952.png">

**Comment by gsaponaro** [comment]
I see. I tried it on two Linux machines with up-to-date yarp (Ubuntu 14.04) and I obtained the problem on both of them. I wonder if other Linux users can reproduce this problem, or the cause is elsewhere on my systems. :)

**Comment by vtikha** [comment]
@gsaponaro I do not think this has to do with the operating system. Are you using yarpdataplayer with opencv or with yarp image? I have just committed a change that informs the user upon playing which library it is using for reading and sending the images.

**Comment by gsaponaro** [comment]
OK: ````[INFO]USING OPENCV FOR SENDING THE IMAGES````.

Versions 2.4.9 (from source) and 2.4.8 (from Ubuntu packages) respectively.

**Comment by gsaponaro** [comment]
Hi @vtikha, would it be possible to further analyze this issue? As I mentioned in the previous messages, my **yarpdataplayer** is relying on **OpenCV**. Ideally I'd like to use my old dumps for some POETICON++ development (it is faster for me than using the real robot, which at the moment is also under repair / unavailable).

**Comment by vtikha** [comment]
commit 9a7d38a has fixed the halved images sent by ```yarpdataplayer``` on ubuntu 14.04

**Comment by gsaponaro** [comment]
Cool, confirmed working here, thanks.
