### ISSUE TITLE
templates are not ordered alphabetically on yarpmanager/builder.

### ISSUE THREAD

**Issue by tanismar** [robotology/yarp#625]
Search by typing works, but if several apps begin with the same letters, only the first one will appear, and unless you are lucky and it' s the one you are looking for, you still have to go through all the app templates by hand until you find yours. 
It is not a critical issue, but it would definitely remove a easily avoidable annoyance when using yarpmanager/builder.
Thanks in advance!
Tanis

**Comment by Nicogene** [comment]
I reopen this issue, as pointed out by @tanismar  the problem came back.
