### ISSUE TITLE
OS::ThreadTest fails if YARP_EXPERIMENTAL_CXX11 option is on 

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#632]
See https://travis-ci.org/robotology/yarp/jobs/88977045 and https://travis-ci.org/robotology/yarp/jobs/88977050 . 

cc @francesco-romano

**Comment by Tobias-Fischer** [comment]
Don't think this is still the case, is it @traversaro?

**Comment by drdanz** [comment]
I think I fixed this race some time ago, Let's close it, we ca always re-open it later if it happens again
