### ISSUE TITLE
Streaming ports get stuck

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#634]
While using `iKinGazeCtrl` with `saccades on`, the robot's head stops moving after a few commands.
What has been observed is either one of the two phenomena:
- `iKinGazeCtrl` stops sending commands getting stuck inside the `setPositions()`.
- iCub's `ControlBoardWrapper` stops processing streaming commands and therefore gets overwhelmed by streaming messages creating a very long queue (`>1000` messages). Even when the sender stops sending new commands, the queue is not consumed anymore.

Further, the process does not exit gracefully when closing; it has to be killed.

I found out that when removing the `strict` option the ports do not get stuck anymore, but of course the behavior is not correct.

From some preliminary tests, my guess is that the strict option is buggy, causing a deadlock sometime in the write (`iKinGazeCtrl` stops sending commands) or in the read (huge queue of message is created).

This is probably related to #583.

**Comment by pattacini** [comment]
Is there any test to verify this functionality?

It seems that several times in the past (see https://github.com/robotology/icub-main/issues/129) a problem on the `writeStrict` along with the `position-direct` mode has been responsible for quite a big impact on our high-level software and was also difficult to be narrowed down.

**Comment by barbalberto** [comment]
Not yet, I'll make one to use with the RTF asap

**Comment by pattacini** [comment]
:+1: 
I bet this new test will help us considerably. Thanks!

**Comment by lornat75** [comment]
It would be easier if you replicate the problem only using ports. In this case the test can go with the others in YARP.

**Comment by lorejam** [comment]
Just to reinforce that in our case this happens ALWAYS and after just ONE command is sent on the /xd:i port.
We tried it several times.

**Comment by pattacini** [comment]
@lorejam, yep the problem is deterministic: it does always happen, sometime on the sender side, other times on the receiver side.

**Comment by pattacini** [comment]
Any progress on this issue?

**Comment by pattacini** [comment]
@barbalberto could you deal with this tomorrow during **IFI Day 4**?

**Comment by barbalberto** [comment]
I made a test and I'm not able to reproduce it. I and Ugo tried also on the real robot and the problem didn't show up anymore. @loreJam, do you still experience this issue?

**Comment by pattacini** [comment]
Nasty heisenbug ...

**Comment by pattacini** [comment]
For completeness, I think @barbalberto also tried to reproduce the problem with a pure port-based approach, being the result the same: apparently, everything works properly.

**Comment by lorejam** [comment]
I can update YARP/iCub and test it...
...did you make relevant changes to YARP/iCub that could possibly have
solved the issue?
Otherwise, I bet the problem would still be there :)

On Fri, Nov 27, 2015 at 10:46 AM, Ugo Pattacini <notifications@github.com>
wrote:

> For completeness, I think @barbalberto <https://github.com/barbalberto>
> also tried to reproduce the problem with a pure port-based approach, being
> the result the same: apparently, everything works properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/yarp/issues/634#issuecomment-160111167>.
>



-- 
===================================================================

Lorenzo Jamone - Research Associate
http://lorejam.blogspot.pt/
ljamone@isr.tecnico.ulisboa.pt <Tecnicojasv@isr.tecnico.ulisboa.pt>

VisLab - http://vislab.isr.ist.utl.pt
Instituto Superior Técnico - http://tecnico.ulisboa.pt/

Institute for Systems and Robotics, Torre Norte (7th floor).
Av. Rovisco Pais, 1
1049-001 Lisbon, Portugal

Office (room 7.25): +351218418299
Laboratory (room 7.26): +351218418050

====================================================================

**Comment by lornat75** [comment]
it could be a strange interaction with the code in the remote control board...

**Comment by pattacini** [comment]
@barbalberto's guess is that there might be a deadlock in one of the mutex of the port; however, no commits have been done recently in this respect to justify the changed behavior.

Our main aim now is to try to make it happen again, otherwise debugging will be difficult.

**Comment by barbalberto** [comment]
This has been fixed by commit 2700fd4977b7247893a0df32ba73295a8c6ccebc
Bug was:  checkMotionDone took a mutex but never release it, so following request got stuck.

**Comment by pattacini** [comment]
Great! :tada:

**Comment by lorejam** [comment]
Yee!
I will test as soon as I can and confirm ;)

Lore
Em 15/12/2015 11:16, "Ugo Pattacini" <notifications@github.com> escreveu:

**Comment by lornat75** [comment]
Pretty serious bug, strange it did not cause deterministic, catastrophic effects... thanks for finding it!

**Comment by lornat75** [comment]
...but this means that two subsequent checkMotionDone would have caused a deadlock, for example MotorTest should have triggered a deadlock: https://robotology.github.io/icub-tests/doxygen/doc/html/classMotorTest.html

**Comment by barbalberto** [comment]
The point is that only group version was affected, and checkmotionDone group version is almost never used.

The mutex is shared among different functions, so this bug was *actually* creating a deadlock, just the blocked call was not the checkMotionDone but a different one using the same mutex. This made the bug a bit more subtle to spot.

Today me and @valegagge modified the test in order to use it, however a test dedicated to test only communication (all possible method) between wrapper and client would be nice to add and run before the testMotor.

**Comment by lornat75** [comment]
if you have added a test that triggers this bug, and that now with the commit passes I think it is good enough.

**Comment by gsaponaro** [comment]
We're a bit late to the party (this bug is already marked as solved), but we just wanted to report that this issue is solved on ```iCubLisboa01``` too: the gaze test with saccades described in https://github.com/robotology/icub-main/issues/238 works fine.

**Comment by barbalberto** [comment]
Thanks for the feedback!
