### ISSUE TITLE
yarplogger not taking in account the date

### ISSUE THREAD

**Issue by tanismar** [robotology/yarp#648]
Hi all, 
I was using yarplogger to see some printouts of my running processes, and in order to see the latest ones (i.e., the ones running) I sorted it out in cronological order ("last heard of"). I realised however that the running processes were not the first ones to appear, but rather those ones run the day before at a later hour in the day. My impression is that yarplogger only takes in account the time of the day to to sort the processes out, without taking in account the date. This is not a critical issue, but it would be helpful to be able to look directly at the last processes to control what is going on on running processes. 
Best, and thanks in advance!
Tanis

**Comment by drdanz** [comment]
Fixed in 2687413a2a3f9a3b1cf50dcee9a1cab2df48589d
