### ISSUE TITLE
Kernel Panic on yarp connect

### ISSUE THREAD

**Issue by nico202** [robotology/yarp#657]
Hi, I'm running yarp 2.3.63.8, kernel version 4.4.0-040400rc4-generic (happened with rc2 too, I'll try with other version as soon as I can to find the regression).
If I run `yarpserver` and then in another terminal emulator `yarp connect` I get a Kernel Panic. I don't know how to provide a backtrace for this, I'll follow istruction if someone can provide a link. (also, don't know if I have to report this here or on the kernel repo)
Thanks, Nicolò

EDIT 1: 4.3.1-040301-generic works correctly

**Comment by lornat75** [comment]
Dear nico22, it seems quite unlikely that yarp can cause kernel panic, I would blame a malfunctioning driver (the network card?). Are you sure your system is sane?

**Comment by nico202** [comment]
Quite sure, works well on 4.3 and older. Also, it's the only situation 
that triggers it.
If can run some test to be sure the system is sane I'll run it.
Thanks, Nicolò

Il giorno ven 11 dic 2015 alle 18:44, Lorenzo Natale 
<notifications@github.com> ha scritto:

**Comment by lornat75** [comment]
Closing as no more input was received. Feel free to re-open again.
