### ISSUE TITLE
Deprecate void yarp::os::Bottle::add(const char* txt)

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#659]
According to the [comments in the code](https://github.com/robotology/yarp/blob/master/src/libYARP_OS/include/yarp/os/Bottle.h#L140)

```c++
    // worked "accidentally", user code relies on this
    void add(const char* txt) {
        addString(txt);
    }
```

What do you think about deprecating this function in favour of ``yarp::os::Bottle::addString(const char* txt)``?

At least inside yarp I'm planning to replace all the calls with ``addString()``, since using this method just adds an extra function call...

@lornat75, @pattacini Do you have any idea about how much impact deprecating this method will have on the user code? (Note that it's not removed, just deprecated therefore it will just cause an extra warning if warnings are enabled).

**Comment by pattacini** [comment]
Fine with me :+1:

**Comment by traversaro** [comment]
:+1:

**Comment by lornat75** [comment]
Fine with me.
