### ISSUE TITLE
Lua bindings: cannot find libYARP

### ISSUE THREAD

**Issue by kt10aan** [robotology/yarp#682]
I was experimenting with the portmonitor feature on OS X, but trying to reproduce the setup in Linux (Debian 8), gives me errors. More specifically:

Running the ``$YARP_ROOT/bindings/example.lua``, results to:
``/usr/bin/lua: error loading module 'yarp' from file '/home/kostas/robotcub/yarp/install/lib/lua/5.1/yarp.so':``
       ``libYARP_OS.so.1: cannot open shared object file: No such file or directory``

As can be seen above, my ``$YARP_DIR`` is ``$YARP_ROOT/install`` and I use ``make install``.
I am not quite familiar with lua and its mechanisms but I was under the impression that, with RPATH on in YARP, there would be no linking issues. In OS X I used the homebrew formula so things got installed (or at least symlinked) in ``/usr/local/lib``

Also, to mention that I am using lua 5.1 and that I compiled the bindings from the main CMakeLists file (I did not go to ``$YARP_ROOT/bindings`` and run independently the CMakeLists file that is there.

**Comment by apaikan** [comment]
Hi @kt10aan 

I have few doubts too : :p 
- Did you compiled YARP as shared library (CREATE_SHARED_LIBRARY) ? it should be enabled by default. 

- Is the `lib/lua/5.1/yarp.so` is consitent with your current build of YARP? You do not have two different builds or cached Cmake which messed up the system? 

- Check that your lua parser executable has the same version (`lua -v`) of your liblua5.1-dev !

- did you build the binding directly from the YARP-build directory or you built it separetly within `yarp/bindings` ? 


We have been using Lua extensively on Linux and did not faced the same problem. I should say that I did not tried the installed version of the yarp!!!  


@drdanz  have you tried?

**Comment by kt10aan** [comment]
@apaikan, I am quite sure the fault is on my side but here are the answers to your questions:

- Yes, YARP was compiled as a shared library (as it is enabled by default).
- Yes, I retried after cleaning the ``build`` and ``install`` directories
- ``lua -v`` reports version ``5.1.5``. Standard installation from Debian 8 repositories
- I built the bindings directly from the YARP-build directory.

I am baffled :)

**Comment by kt10aan** [comment]
Update: I changed the ``LUA_CPATH`` to point to the in-build ``lib/lua/yarp.so`` and I can run the ``example.lua``.
So the problem for me arises when I use an installed version of YARP in an non-system directory (in my case, in ``$YARP_ROOT/install``. But in this case, shouldn't RPATH have taken care of that? Everything else in YARP works fine (including the python bindings), when installed in ``$YARP_ROOT/install``

**Comment by drdanz** [comment]
Confirming this. The library is installed in `<prefix>/lib/lua/5.2/yarp.so` and the RPATH is `$ORIGIN/:$ORIGIN/../lib:$ORIGIN/../` therefore it does not work yet.
I will fix it in a few minutes.

**Comment by drdanz** [comment]
@kt10aan It should be working now, can you test and confirm, please?

**Comment by kt10aan** [comment]
Everything works here now, thanks :)
