### ISSUE TITLE
Is there a way to introduce delay in a connection ?

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/yarp#685]
Hello.
Here is my problem.
I have a module (let's call it `A`) that streams information to a second module  (let's call it `B`).
I would like to introduce some delay between the `A` and `B`.
My idea would be to create a module `C` in the middle, that would get the Bottle from `A`, wait, and forward it to `B`.
I wonder if something like that already exists in `port monitor` or something equivalent ?

Thank you in advance !

**Comment by apaikan** [comment]
@gregoire-pointeau : I closed this issue and open it for you on our QA repo.
Please see https://github.com/robotology/QA/issues/99 for the answer!
