### ISSUE TITLE
changing yarp/src/modules folder's name to yarp/src/devices

### ISSUE THREAD

**Issue by apaikan** [robotology/yarp#695]
**THIS IS A MINOR ISSUE!**

The `yarp/src/modules` folder is a bit misunderstanding.  The folder contains yarp standard devices. 
In the Yarp terminology,  a _Module_  refers to an  actual Yarp _Component_.  This can be found in the  `RFModule` class, `Module description file (xml)`  from `yarpmanager` and respectively all the tutorials regarding the Yarp Module (components). 

So I guess the `devices` would be more appropriate for the  `yarp/src/modules`.

**Comment by drdanz** [comment]
A big +1 from me

**Comment by alecive** [comment]
+1000

**Comment by barbalberto** [comment]
what about src/libYARP_dev/src/module?
Shall we change that as well? Shall we merge the 2 folder together?
