### ISSUE TITLE
Fix version badge and link to releases instead of tags

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/yarp#704]
Hi all,

I noticed that the wrong version number of Yarp is shown on https://github.com/robotology/yarp

Also, the link guides to `tags` rather than `releases`, which I think is more correct.

Both can be fixed as follows:
```
diff --git a/README.md b/README.md
index b132ad4..98d8a12 100644
--- a/README.md
+++ b/README.md
@@ -8,7 +8,7 @@ YARP
 ====
 
 [![YARP Homepage](https://img.shields.io/badge/YARP-Yet_Another_Robot_Platform-orange.svg)](http://wiki.icub.org/yarpdoc/)
-[![Latest Release](https://img.shields.io/github/tag/robotology/yarp.svg?label=Latest Release)](https://github.com/robotology/yarp/tags)
+[![Latest Release](https://img.shields.io/github/release/robotology/yarp.svg?label=Latest Release)](https://github.com/robotology/yarp/releases)
 
 YARP is a library and toolkit for communication and device interfaces,
 used on everything from humanoids to embedded devices.
```

Best,
Tobi

**Comment by drdanz** [comment]
@Tobias-Fischer Thanks.
This seems to be the reason for this: https://github.com/badges/shields/issues/490
We have a tag `start` that probably confuses shields.io.

**Comment by drdanz** [comment]
FYI, badges/shields#490 is now fixes and  [![Latest Release](https://img.shields.io/github/tag/robotology/yarp.svg?label=Latest Release)](https://github.com/robotology/yarp/tags) should report the latest tag
