### ISSUE TITLE
CREATE_YARPROBOTINTERFACE has no effect

### ISSUE THREAD

**Issue by opendragon** [robotology/yarp#707]
Setting the option CREATE_YARPROBOTINTERFACE to 'Off' does not stop the build of yarprobotinterface, unlike the CREATE_YARPDATADUMPER option, which is used in src/yarpdatadumper/CMakeLists.txt to control whether yarpdatadump gets built.

**Comment by drdanz** [comment]
Should be fixed now, thanks for reporting this.
