### ISSUE TITLE
yarpserver used with --ros should not start if required carriers are not found/compiled

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#722]
yarpserver used with --ros option is meant to work together with roscore and therefore it requires the following carriers:
- rossrv
- tcpros
- xmlrpc

right now the server does not check if the plugins are available, and at the connection time it prints an error

yarp: Failed to find library support for carrier xmlrpc
yarp: Could not find carrier "xmlrpc"

which is kind of difficult to spot. 
IMHO it'd be better if the server does not start if the carriers are not available in order to catch the problem as soon as possible.

**Comment by drdanz** [comment]
Does it work with xmlrpc, but not rossrv and tcpros?

**Comment by aerydna** [comment]
also, if you start `yarpserver --ros` without such plugins and then you call `yarp plugin *anything*` yarpserver crash (segfault).
