### ISSUE TITLE
"yarp resource" stopped working?

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#723]
The command line utility **`yarp resource --context context-name --find file-name`** has somehow stopped working correctly after recent updates to yarp. Spotted on Purply and Blacky systems.

This is a quite useful tool to check which configuration file a module will load at start up.

cc @drdanz @randaz81 @vtikha @nunoguedelha @traversaro

**Comment by pattacini** [comment]
##### Side note

Even though `yarp resource` does not locate files according to yarp polcies, all the modules are loading their configurations correctly.

**Comment by pattacini** [comment]
I found the problem and committed a fix in a dedicated branch called `fix/yarp-resource`.
I pushed this branch but somehow - and very strangely - I cannot proceed with the relative PR.

The commit is there anyway: see https://github.com/robotology/yarp/compare/fix%2fyarp-resource?expand=1.

Any idea? First time I came across this weirdness; I might be missing something obvious.

**Comment by pattacini** [comment]
I've just logged into Blacky system and done `git fetch origin`. As a result, I can perfectly see `fix/yarp-resource` in the list of remote branches, but still I cannot find it here in GitHub: https://github.com/robotology/yarp/branches

This is driving me crazy...

**Comment by traversaro** [comment]
@pattacini I was able to create the PR at https://github.com/robotology/yarp/pull/724 ( I found normally the branch in https://github.com/robotology/yarp/branches ).

**Comment by pattacini** [comment]
It has just appeared here too... really don't know what happened; maybe a temporary problem with my browser ?!?
Thanks @traversaro

**Comment by pattacini** [comment]
Solved via #724
