### ISSUE TITLE
yarplogger in yarpmanager++

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#731]
It would be nice to have yarplogger integrated in yarpmanager++.

**Comment by traversaro** [comment]
Once the yarplogger is integreated in yarpmanager++, it would be nice to include support for it (in some way) also in the `yarpmanager` RTF plugin.

**Comment by randaz81** [comment]
Beware: this will be not an easy porting. Yarpmanager supports multiple instances on multiple machines. Yarplogger only supports one single instance on the whole cluster. Changing this will require major modifications the core engine and it is not recommended (risk of performance issues). Hence I'd suggest to keep it as a stand-alone executable.
