### ISSUE TITLE
Errors when compiling the carriers tutorial examples

### ISSUE THREAD

**Issue by gabrielenava** [robotology/yarp#734]
I tried to compile the carriers tutorial examples in the folder:

 yarp/example/carrier

but I get some cmake errors. Initially, the error was related to a wrong path to some libraries:

/home/gnava/yarp/example/carrier/carrier_human.cpp:10:34: fatal error: yarp/os/impl/Carrier.h: No such file or directory

I fixed this problem, but I get other cmake errors:

/home/gnava/yarp/example/carrier/carrier_human.cpp:151:33: error: cannot allocate an object of abstract type ‘HumanCarrier’
/home/gnava/yarp/example/carrier/carrier_human.cpp:251:53: error: ‘readLine’ is not a member of ‘yarp::os::NetType’
/home/gnava/yarp/example/carrier/carrier_human.cpp:332:39: error: cannot allocate an object of abstract type ‘HumanCarrier’
/home/gnava/yarp/example/carrier/carrier_human.cpp:338:15: error: call of overloaded ‘exit(int)’ is ambiguous
make[2]: **\* [CMakeFiles/carrier_human.dir/carrier_human.cpp.o] Error 1
make[1]: **\* [CMakeFiles/carrier_human.dir/all] Error 2
make: **\* [all] Error 2
**\* Failure: Exit code 2 ***

**Comment by vtikha** [comment]
@gabrielenava Please check the tests on the latest master
