### ISSUE TITLE
ASCII logo

### ISSUE THREAD

**Issue by orangefult** [robotology/yarp#737]
I redid your ascii logo... I know it's not a big deal, but it just bugged me how the R and P were pointing a different way that the "YA" 

https://gist.github.com/orangefult/f0a6e01854e3907d413a41107ce13730

**Comment by lornat75** [comment]
Thanks, looks good! Why not going with the == all the way until the end of the P?

**Comment by orangefult** [comment]
You could I guess. I just liked the way the "P" dropped down, kind of gives it an endpoint.

**Comment by drdanz** [comment]
Committed, with a few small changes.
Thanks
