### ISSUE TITLE
segfault on exit froml LUA scripts that use icub bindings

### ISSUE THREAD

**Issue by elen4** [robotology/yarp#74]
Debugging with gdb this LUA script:
--
#!/usr/bin/lua

require("yarp")
require("icub")

icub.init()
--
results in:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff61bf686 in DriversHelper::~DriversHelper (this=0x652270, 
    __in_chrg=<optimized out>)
    at <cut>/yarp/src/libYARP_dev/src/Drivers.cpp:43
43	            delete delegates[i];

(gdb) print i
$2 = 11
---------
Adding this line to the script:
print(yarp.Drivers_factory():toString())
shows that device 11 is:
Device "cartesiancontrollerserver", C++ class ServerCartesianController, wrapped by "cartesiancontrollerclient"
 which is the first of icubmod devices.

**Comment by drdanz** [comment]
@elen4 Is this still an issue or can we close this?

**Comment by elen4** [comment]
I don't know, and unfortunately I do not have a setup to test it now :worried:
I assume that nobody is using Lua bindings with the iCub at the moment and this issue is therefore not relevant, but unless drivers cleanup has been checked/fixed as a consequence of recent work on plugins, I don't think this has been addressed. I'd leave this open until someone ( @paulfitz ? :grinning: ) can test this.

**Comment by paulfitz** [comment]
Any icub-savvy person available to test? @apaikan?

**Comment by apaikan** [comment]
iCub Lua binding is not necessary any more and the robot can be directly controlled via Yarp interfaces using yarp-lua binding (i.e., lua/yarp.so). 

here is the example for opening a Cartesian controller interface with the robot using Lua: 

```lua
require("yarp")

-- initialize yarp network
yarp.Network()

option = yarp.Property()
option:put("device","cartesiancontrollerclient");
option:put("remote","/icubSim/cartesianController/right_arm");
option:put("local","/client/right_arm");
cartCtrl = yarp.PolyDriver(option)
...

```
