### ISSUE TITLE
yarpmanager++ crashes

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#740]
yarpmanager++ crashes when the user double clicks on one of the "folders" on the left: applications, modules etc.

It should not be difficult to fix, it happens deterministically on both Linux and Windows.

@aitek4iit 
@apaikan

**Comment by aitek4iit** [comment]
I have just committed a fix for the problem. This fix avoids to call open functions on parent nodes of the tree. Now the parent node of the tree will collapse or expand themself on doubleclick
