### ISSUE TITLE
yarpmanager save as... button does not seem to work

### ISSUE THREAD

**Issue by tanismar** [robotology/yarp#755]
Hi, 
the Save as... menu option of yarpmanager++ seems to not do anything, independently of whether the open application has been modified, or not and you just want to change the name. 
launching yarpmanager++ with sudo does not help either (actually, a different version of it is opened, which might be bug too).

**Comment by apaikan** [comment]
Different version?

**Comment by Nicogene** [comment]
Fixed by #1206
