### ISSUE TITLE
yarp::os::SystemInfo : missing implementation for Mac OS

### ISSUE THREAD

**Issue by apaikan** [robotology/yarp#781]
The class `yarp::os::SystemInfo` does not provide any system information for Mac Os. 

**Source of the problem:**
pre-processor macro `__linux__` has not been defined on Mac OS. Probably adding `__APPLE__` to all the relevant functions will solve  the problem! 

CC:  @claudiofantacci  (thanks!)

**Comment by francesco-romano** [comment]
I started adding some info for memory and Cpu.
It is just a "skeleton"...

**Comment by claudiofantacci** [comment]
Cool!
I didn't think it would have differ so much from the linux implementation.
We might also want to meet up to coordinate ourself to make the job done. Let me know.

**Comment by francesco-romano** [comment]
Well.. I'm not sure that in linux we cannot do the same (more or less), as `sysctl` exists also on linux I think.
The difference here is that in linux we are parsing some files, while here we are using system calls.

**Comment by francesco-romano** [comment]
@apaikan this is the branch: https://github.com/robotology/yarp/tree/fix/osx_system_info
It is based on `master`, so when we finish I think we can merge it in master (as bug fix) and devel

**Comment by francesco-romano** [comment]
@apaikan @claudiofantacci 
I've just implemented some other methods.

If you want take a look at it..
BTW: description of the structures should really be added. Some structure are not easy to understand (e.g. CpuLoad)

**Comment by claudiofantacci** [comment]
I didn't have the chance to work on it. Sorry about that. Seems fine to me.
Maybe @apaikan can do some test with his latest modules trying to parse OSX-related info.

**Comment by francesco-romano** [comment]
Ok. I open a PR (https://github.com/robotology/yarp/pull/799) to track this issue, otherwise it gets lost.

**Comment by francesco-romano** [comment]
Given that the PR has been merged I'd close this issue.
We can open it again if something is missing.
