### ISSUE TITLE
We do have real ports now...

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#783]
This is what `yarp read` uses to read from Ports.
I'll just leave this here, since I'm not sure how to describe this issue, and I don't know if this is an outdated comment or outdated code.

Mon Mar 13 12:52:42 2006 +0000 `src/libYARP_OS/src/Companion.cpp` 
![temporary_my_ass](https://cloud.githubusercontent.com/assets/1100056/15675270/7e050090-2741-11e6-9659-5a7b763f2c9d.png)

**Comment by lornat75** [comment]
Another good reason to refactor the yarp companion utility.
