### ISSUE TITLE
Modules and Connections stay selected after being refreshed

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/yarp#790]
Whenever I use `yarpmanager++` and I click the refresh button, all module and connection entries stay selected as if they where selected all together by hand.

Not a big deal, just a minor, yet annoying, issue since most of the time you are forced to click somewhere else on the GUI to unselect them all and to be able to properly use the manager.

cc @apaikan

**Comment by Nicogene** [comment]
Fixed by #1259
