### ISSUE TITLE
yarpscope: min and max values in plots

### ISSUE THREAD

**Issue by gsaponaro** [robotology/yarp#812]
Hi @drdanz @iron76, I've been using **[yarpscope](http://www.yarp.it/yarpscope.html)** successfully (thanks!) and I have a couple of comments:

* suggestion - in the documentation, initially it says that the ```--min``` and ```--max``` command-line parameters (Simple Mode) affect the X axis, while about the XML Mode at the end of the page it says that ```minval``` and ```maxval``` are the minimum and maximum values on the Y axes. I think that it should refer to Y axis in both cases because X is time, right? [EDIT: confirmed and merged, https://github.com/robotology/yarp/pull/813]
* issue - setting Y ranges to be different than the defaults has no effect for me. I tried both with the Simple Mode command-line parameters and with the XML minval/maxval tags like in the examples. I confirmed that the XML is correctly loaded and parsed by yarpscope - changes in the other fields affect the plot, but these Y ranges do not. For example, trying to force the Y axis between 0.0 and 1.0 (the range of the signal which I want to plot) has no effect when yarpscope is started:

![convplot](https://cloud.githubusercontent.com/assets/6716962/16455715/453dbf58-3e0d-11e6-87f8-90564262a651.png)

**Comment by drdanz** [comment]
@gsaponaro Thanks for the documentation patch.
About the second issue, when I run ``yarpscope --min 0.0 --max 1.0`` I get a window with the correct limits.
On which platform are you running it?
Are you using the Qt5 version, or still using the GTK2 version?
Can you show me the command line you are using?
Perhaps there is some rescaling involving when data is received?
Have you tried starting ``yarpscope`` without automatic connection, and connect it later?

**Comment by gsaponaro** [comment]
Hi @drdanz, thanks for the help.

My setup: Ubuntu 14.04, yarp 2.3.66, Qt5 GUIs.

I have a fairly complex yarpscope XML with many subplots, but I prepared a minimal example just for the sake of this issue.

To reproduce the problem, try running **yarpscope** in XML mode with [this file](https://gist.github.com/gsaponaro/7bc7a5fddb06b4f9bca7a855adba0337) that contains one plot with ```minval="0.0"``` and ```maxval="1.0"```:

```yarpscope --xml giovanni_yarpscope_debug2.xml```

Note that data is not yet received at this point (the port does not even exist), but I see a window with Y from 0.0 to 5.0 (where did this number come from?), like this:

![yarpscope_min_max](https://cloud.githubusercontent.com/assets/6716962/16595073/42f27284-42e5-11e6-9d70-97aa4cf6f832.png)

When I create ```/some_port_with_data_between_zero_and_one:o``` and write some numbers in there, **yarpscope** plots the values, but Y is still at 5.0 (which is expected since there was no rescaling).

**Comment by drdanz** [comment]
@gsaponaro I found the bug... the values were read as int instead of float, see #819

**Comment by gsaponaro** [comment]
Cool, works like a charm now. :+1:
