### ISSUE TITLE
Memory leak in yarp_OS [devel branch]: suspected cause OS_Contact refactoring

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#833]
There is a memory leak in yarp reproducible simply running gazebo with cer.
The memory used increase constantly untill the machine dies.

Last good commit is f9167ff871cd7e9a5d0f5d3aaea0c9d5447f8085 "YARP_name/BoostrapServer ..."
First bad commit is 0db7dc6ad6eef7243bff20ad69768aee1da77d5e "Merge pull request #829", but I guess the cause is in the previous "Merge branch 'OS_Contact_Refactor'  @drdanz can you check please?

**Comment by Tobias-Fischer** [comment]
I wrote a comment, I think there is a delete missing for the `mPriv` variable.
