### ISSUE TITLE
Problems displaying fonts in 4k monitors

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#837]
All guis have problems displaying fonts in high-res monitors. 

The problems is probably this one:
http://doc.qt.io/qt-5/highdpi.html

can be fixed by adding qputenv("QT_DEVICE_PIXEL_RATIO", QByteArray("2")); in the main.

Thanks @aitek4iit

**Comment by lornat75** [comment]
Checking the documentation more carefully we need to ensure that the line:

qputenv("QT_DEVICE_PIXEL_RATIO",QByteArray("2"));

does not cause problems to systems with low-resolution. More importantly this feature is deprecated in qt 5.6, so we need to make it version specific and remove it once we stop supporting qt 5.4 and (probably) 5.5.

**Comment by lornat75** [comment]
These commits have been reverted because did mess up the visualization on normal screens.

**Comment by lornat75** [comment]
Looks like the safest solution at the moment is to leave to the user to set the environment variable:

QT_DEVICE_PIXEL_RATIO = 2

This can be done at the system level (recommended) in the control panel or on each terminal.

**Comment by lornat75** [comment]
Proper fix should be done using new features in qt 5.6. 

@mbrunettini maybe in the next release of the binaries we should replae qt .5.4 with qt 5.6 .

@drdanz, @aitek4iit  what do you think?

**Comment by pattacini** [comment]
Quick update: together with @lornat75 we've tested that `QT_DEVICE_PIXEL_RATIO = auto` works for both high-res and normal systems.

**Comment by lornat75** [comment]
@pattacini I have updated the pull request, would you mind give it a try?

**Comment by pattacini** [comment]
@lornat75 it works nicely; just merged!

**Comment by mbrunettini** [comment]
Ok, I will update to Qt 5.6 where it is supported.

**Comment by aitek4iit** [comment]
Yes the AUTO flag should do the trick for both resolution and I think Qt 5.6 wolud manage better the high dpi resolutions beacuse in the 5.4 version this feature was only a beta.

**Comment by mbrunettini** [comment]
QT 5.6 is only avavilabe on windows with the following versions:
-VS 2013 (V12) 32 and 64 bit
-VS 2015 (V14) 32 and 64 bit

**Comment by claudiofantacci** [comment]
I'm writing here concerning about `QT_DEVICE_PIXEL_RATIO` qtputenv option.

Under macOS, QT version 5.7.0 (from brew), launching `yaprdataplayer`, `yaprview`, `yarpmotorgui`, the following warning is raised:
```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use: 
    QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors. 
    QT_SCREEN_SCALE_FACTORS to set per-screen factors. 
    QT_SCALE_FACTOR to set the application global scale factor.
```

Probably `QT_AUTO_SCREEN_SCALE_FACTOR` set to `1` (boolean true) will make the job done.

**Comment by drdanz** [comment]
@claudiofantacci Opened a new issue, see @1038

**Comment by Nicogene** [comment]
Changes introduced in #1200 should solve, for now I close this issue, if someone encounter some problems I will re-open it
