### ISSUE TITLE
Improve installation documentation

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp#848]
The installation documentation does not explain the various alternatives, it simply list them all.
While experienced users may be able to perform the correct choice, first time users can be confused and choose the wrong option.

**Comment by francesco-romano** [comment]
@claudia-lat

**Comment by drdanz** [comment]
@francesco-romano Was this fixed by #856 or do we need more work on this?

**Comment by francesco-romano** [comment]
The macOS documentation was fixed, yes. 
Given the high number of macOS users #856 improved the documentation we can think to port the same changes to the other OSes (I'm referring to linux of course).

Closing for now as the reason why I opened was to track #856
