### ISSUE TITLE
Fix remaining travis builds with integration tests due to timeouts

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/yarp#867]
Hi,
Some of the travis builds (e.g. https://travis-ci.org/robotology/yarp/jobs/151445802) which perform integration tests are sometimes timing out. I think there are ways around this, and it would be nice to always have the integration tests tested.
Ways around (I am not sure whether they are only applicable to travis.com or to .org as well):
https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out
-> prefix the command which does not produce outputs for a long time with `travis_wait` (20 minutes wait rather than the default 10 minutes) or `travis_wait X` where X are the minutes to wait (I guess the default maximum build time of 50 minutes still applies)
-> if this is only available on travis.com, we could use https://github.com/php-build/php-build/pull/240/files instead

I've also seen the cache archiving timing out (e.g. https://travis-ci.org/robotology/yarp/jobs/151730442), which can also be circumvented (https://docs.travis-ci.com/user/caching/#Setting-the-timeout). Here, the timeout is in seconds:
```
cache:
  timeout: 1000
```
Best, Tobi

PS: Is there already an issue regarding `thrift` with `XCode` (https://travis-ci.org/robotology/yarp/jobs/151730452)?

**Comment by drdanz** [comment]
> PS: Is there already an issue regarding thrift with XCode (https://travis-ci.org/robotology/yarp/jobs/151730452)?

I don't think there is one, and I don't think it is just XCode, but any multi-config CMake Generator (i.e. Visual Studio as well)

**Comment by Tobias-Fischer** [comment]
The tests still fail sometimes, now due to a timeout in `ctest`. It should be fairly easy to increase that timeout. Also, splitting the test in its shared and static components should half the test time ;) (well, the total time will be the same, obviously). I'll do it once I have some time to play around :P

**Comment by Tobias-Fischer** [comment]
Can close this after https://github.com/robotology/yarp/commit/69b59f5d724f3f75b4779867f43f743c60edae41
