### ISSUE TITLE
YARP `Microphone` module should be deprecated

### ISSUE THREAD

**Issue by barbalberto** [robotology/yarp#891]
For audio capture / play sounds the standard module in yarp is the portAudio device, but there is another device called Microphone in yarp/src/module with Windows and Linux implementation.

The linux implementation uses /dev/dsp device which is deprecated and replaced by ALSA (used by portaudio).

If portaudio is working well in windows then I suggest to deprecate the microphone device.

**Comment by vtikha** [comment]
👍 +1

**Comment by barbalberto** [comment]
On a quick test with @randaz81, we saw that compilation of the module fails on Windows.

On Linux it uses a deprecated version of linux driver. Furthermore, when I tried to run it the only output was:
```
WARNING: the MicrophoneDeviceDriver is just a cartoon
WARNING: it hasn't really been written yet
/dev/dsp: No such file or directory
```

I'll go forward to deprecated it in favor of portaudio.
@drdanz @randaz81 do you agree?

**Comment by randaz81** [comment]
👍

**Comment by EliseiFrederic** [comment]
Hi,

  As far as I remember, there are some linux packets (aoss or alsa-oss ?) to get /dev/dsp (belonging to the deprecated
oss interface) emulated on alsa. This might be the way to get the non-cartoon ?

  Anyway, the device driver used by our iCub already uses portaudio for the ear-microphones if I recall
correctly, so no problem here with bashing /dev/dsp.

Cheers,
Frederic

On Thu, Oct 27, 2016 at 01:57:54AM -0700, Alberto Cardellino wrote:
> On a quick test with @randaz81, we saw that compilation of the module fails on Windows.
> 
> On Linux it uses a deprecated version of linux driver. Furthermore, when I tried to run it the only output was:
> ```
> WARNING: the MicrophoneDeviceDriver is just a cartoon
> WARNING: it hasn't really been written yet
> /dev/dsp: No such file or directory
> ```
> 
> I'll go forward to deprecated it in favor of portaudio.
> @drdanz @randaz81 do you agree?
> 
> -- 
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/robotology/yarp/issues/891#issuecomment-256585842

-- 
Frederic ELISEI                    http://www.gipsa-lab.fr/~frederic.elisei/ 
(33-4) 76574539            mailto:/Frederic.Elisei@gipsa-lab.grenoble-inp.fr
