### ISSUE TITLE
Yarp for C# (sender) and Java(receiver) - robot control

### ISSUE THREAD

**Issue by abolfazlzaraki** [robotology/yarp#908]
Hello everybody,

I am going to make a network between C# and Java code as sender and receiver of an "String". I decided to use Yarp since it supports different platforms. Does anybody have a sample code or an instruction that helps on that?

Thanks in advance.

**Comment by Tobias-Fischer** [comment]
Hi,
First you need to compile the bindings for C# and Java, see http://www.yarp.it/yarp_swig.html
Then, there is example code for [Java](https://github.com/robotology/yarp/blob/master/bindings/src/Example1.java) and [C#](https://github.com/robotology/yarp/blob/master/bindings/example.cs)

For sending strings around, just adapt the very simple example [here](http://www.yarp.it/yarp_code_examples.html).

Hope that helps.

**Comment by drdanz** [comment]
@abolfazlzaraki Please let us know if @Tobias-Fischer reply is enough and if we can close this issue, or if you need more help.

**Comment by abolfazlzaraki** [comment]
Thanks @Tobias-Fischer. It works for me :)
