### ISSUE TITLE
Simplify process of saving whole body joint configuration from yarpmotorgui

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#912]
While saving an whole body position, a form for each part appears. It would be more convenient to have to need to insert the position name in only one form.

Furthermore, when the file is saved a `[ERROR]File saved and closed` error message is printed, that should be converted to `[INFO]`.

**Comment by randaz81** [comment]
Feature implemented by commit 71771142e4d439921dcd5ebba8778.
if user sets a file name in "Save all joints" dialog, the filename is propagated to all part sequences.
if user clicks on the cancel button, an individual dialog is opened for each part.
