### ISSUE TITLE
branch devel does not compile

### ISSUE THREAD

**Issue by davidetome** [robotology/yarp#928]
CMake Error at cmake/YarpFindDependencies.cmake:127 (message):
   Optional package GSL not found.  Please install it or disable the option
   "CREATE_LIB_MATH_USING_GSL" to build yarp.
 Call Stack (most recent call first):
   cmake/YarpFindDependencies.cmake:396 (check_optional_dependency)
   CMakeLists.txt:62 (include)

@drdanz

**Comment by pattacini** [comment]
Hi @davidetome 

Do you have `GSL` installed on you system?
It should be in the path pointed by `GSL_DIR` env variable.

**Comment by pattacini** [comment]
@davidetome one other possibility might be to purge the cmake cache and configure yarp from scratch.

**Comment by davidetome** [comment]
Ciao @pattacini ,
 I did but didn't work. Actually GSL_DIR is not set in .bashrc_iCub; switching to master it compiles.

**Comment by traversaro** [comment]
It is an Ubuntu 16.04 system?

**Comment by pattacini** [comment]
Ok you're on linux. Then, it's very likely that GSL is part of `icub-common`, thus you don't need to have GSL_DIR in the `.bashrc_iCub`.

**Comment by davidetome** [comment]
@traversaro yes, it is.
