### ISSUE TITLE
module does not close correctly when using logging functions

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#931]
**On WIN32 only, when the environment variable YARP_FORWARD_LOG_ENABLE is set to 1.**

A module does not closely correctly (freeze) if during its execution it used one of the yarp logging function (yDebug, yError etc)

**Comment by barbalberto** [comment]
This should be fixed by commit afdf5a5 on logForward_deInit branch (under testing)
On linux this was causing segfaults on closure

**Comment by barbalberto** [comment]
Can we close this issue?

**Comment by drdanz** [comment]
Closing. Please re-open is this is still an issue.
