### ISSUE TITLE
Non-deterministic memory leak in FrameTransformClientTest

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#953]
See #880

**Comment by claudiofantacci** [comment]
I suggest to set this to a (somewhat) "high priority" as it affects all the CI tests, and restarting them hoping for a lucky run is somewhat odd.

**Comment by drdanz** [comment]
Assigning @aerydna since he was already working on this.

**Comment by aerydna** [comment]
ok the test is fixed with the pr #960  but the issue is not. the problem was caused by the usage of tcp protocol for the streaming comunication between transformServer and Client. Details on the fresh related issue  #963
