### ISSUE TITLE
There's no unique way to pass a vector/matrix through a bottle

### ISSUE THREAD

**Issue by alecive** [robotology/yarp#96]
I'd like to have a port that handles some strings, doubles and vector(s), but currently it's not explicitly possible because a vector cannot be directly passed with something like a *bottle.addVector()* method.
I know that there are workarounds (e.g. *b.addString(v.toString())* or a for loop that adds *n* double to the bottle) but the vector/matrix are probably the most used classes on yarp, and they deserve a better way to be passed through bottles.
Even a *vector.asBottle()* should suffice.

**Comment by drdanz** [comment]
@alecive, @paulfitz Is this still an issue or can we close this?
