### ISSUE TITLE
Desactivate `CUDA` in cmake

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/yarp#981]
Hello, we are working on the cluster. We have the blades and the cuda machine that share the same sources.

While compiling `yarp` then `icub-main`, it works on the `cuda-machine` but on the blades we have a problem of cuda:

This is the `cmake`:
>CMAKE_BUILD_TYPE                 Release                                                               
 CMAKE_INSTALL_PREFIX             /usr/local                                                            
 CREATE_GUIS                      OFF                                                                   
 CREATE_LIB_MATH                  OFF                                                                   
 CREATE_SHARED_LIBRARY            ON                                                                    
 CREATE_YARPDATADUMPER            ON                                                                    
 CREATE_YARPMANAGER_CONSOLE       ON                                                                    
 CREATE_YARPROBOTINTERFACE        ON                                                                    
 CUDA_BUILD_CUBIN                 OFF                                                                   
 CUDA_BUILD_EMULATION             OFF                                                                   
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND                                            
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda                                                       
 CUDA_VERBOSE_BUILD               OFF                                                                   
 ENABLE_DASHBOARD_SUBMIT          OFF                                                                   
 OpenCV_DIR                       /usr/local/src/robot/opencv/build                                     
 YCM_DIR                          YCM_DIR-NOTFOUND                                                      

and this is the output:
>  CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
   Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
   version "4.2" (found /usr/local/cuda)
 Call Stack (most recent call first):
   /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:286 (_FPHSA_FAILURE_MESSAGE)
   /usr/share/cmake-2.8/Modules/FindCUDA.cmake:723 (find_package_handle_standard_args)
   /usr/local/src/robot/opencv/build/OpenCVConfig.cmake:48 (find_package)
   /usr/local/src/robot/opencv/build/OpenCVConfig.cmake:276 (find_host_package)
   cmake/ycm-0.2/find-modules/FindOpenCV.cmake:88 (find_package)
   cmake/YarpFindDependencies.cmake:363 (find_package)
   CMakeLists.txt:62 (include)

Is there a way to deactivate `cuda`?

Thank you

@AnneLaureM

**Comment by pattacini** [comment]
Issue moved to [robotology/QA #166](https://github.com/robotology/QA/issues/166) via [**ZenHub**](https://www.zenhub.com/)
