### ISSUE TITLE
documentation for channel prioritization 

### ISSUE THREAD

**Issue by lornat75** [robotology/yarp#986]
Channel prioritization is missing in the online documentation.

**Comment by lornat75** [comment]
@apaikan

**Comment by apaikan** [comment]
As it is for now, setting coonectionQos is done via: 
- yarp admin rpc command
-  application xml file (see documentation of yarpmanager)
- yarpviz tool
It would be useful to have also yarp companion for setting Qos too. Example: 
`yarp qos set /from /to (properties....)`

**Comment by drdanz** [comment]
Closing this, I opened a new one (#992) for the `yarp qos` command.
