### ISSUE TITLE
Extra comments may prevent thrift compilation

### ISSUE THREAD

**Issue by tanismar** [robotology/yarp#998]
Hi there, 

On some systems, extra comments on the thrift pages might prevent this files from compiling. As it is not an intuitive thing, and tricky to debug (as usually comments are skipped on debugging), it should be advised in the thrift documentation to keep the comments for function documentation only. 

Example: 
In my case, I had a thrift file with many functions, so I made some comment separators for easier reading, as in the following: 

```
    /*********************** FOOs ************************************/
    /**
     * Bla bla
     * @return true/false on success/failure
     */
    bool foo1(1: i32 x = 1);

    /*********************** FIIs ************************************/
    /**
     * Bli bli
     * @return true/false on success/failure to perform all actions
     */
    bool fii(1: i32 x, 2: i32 y = 0);
```

The separators had to be removed in order for the program to compile. 
```
/*********************** FXXs ************************************/ 
``` 

Best, 
Tanis

**Comment by pattacini** [comment]
Hi @tanismar 

What about creating a PR to fix this up? 😉 
Maybe at next IFI?

**Comment by drdanz** [comment]
We could also consider fixing this in the thrift compiler...
It annoys me to know that if I add some comment the file will not compile.

**Comment by drdanz** [comment]
This is a problem of the thrift parser which we just import but we do not want to modify, and therefore should eventually be fixed upstream.

Closing this.
